import type { Lesson } from './lessons'

// Parcours Cryptographie : César, Vigenère, fréquences, hachage, arithmétique modulaire, RSA jouet, Diffie–Hellman (Python pur, hors ligne). Pédagogique : jamais pour protéger de vraies données. Contenu original.
export const cryptoLessons: Lesson[] = [
  {
    id: "crypto-cesar", lang: 'py', group: "crypto",
    title: { fr: "Chiffre de César", en: "Caesar cipher" },
    explain: { fr: "Le chiffre de César décale chaque lettre de k positions dans l'alphabet (A→D pour k=3). Au bout de Z, on revient à A : c'est le MODULO 26. Les non-lettres restent intactes. Pour déchiffrer, on décale de −k. Il est trivial à casser (26 clés seulement), mais il pose les idées de base : une clé, un chiffrement, un déchiffrement inverse.", en: "The Caesar cipher shifts each letter by k positions in the alphabet (A→D for k=3). After Z we wrap to A: that is MODULO 26. Non-letters stay untouched. To decrypt, shift by −k. It is trivially breakable (only 26 keys), but it sets out the basic ideas: a key, encryption, and an inverse decryption." },
    example: "print(ord('A'), chr(65 + 3))",
    task: { fr: "Écris cesar(texte, k) pour les lettres majuscules A–Z (le reste est conservé) ; k peut être négatif.", en: "Write cesar(texte, k) for uppercase letters A–Z (everything else is kept); k may be negative." },
    starter: "def cesar(texte, k):\n    pass\n",
    hint: { fr: "Pour une lettre c : chr((ord(c) - 65 + k) % 26 + 65). Teste c.isalpha() et c.isupper() d'abord.", en: "For a letter c: chr((ord(c) - 65 + k) % 26 + 65). Test c.isupper() first." },
    solution: "def cesar(texte, k):\n    sortie = ''\n    for c in texte:\n        if 'A' <= c <= 'Z':\n            sortie += chr((ord(c) - 65 + k) % 26 + 65)\n        else:\n            sortie += c\n    return sortie",
    checks: ["cesar('ABC', 3) == 'DEF'", "cesar('XYZ', 3) == 'ABC'", "cesar('BONJOUR, MONDE !', 1) == 'CPOKPVS, NPOEF !'", "cesar(cesar('SECRET', 7), -7) == 'SECRET'", "cesar('ABC', 26) == 'ABC'", "cesar('ABC', -1) == 'ZAB'"],
  },
  {
    id: "crypto-vigenere", lang: 'py', group: "crypto",
    title: { fr: "Chiffre de Vigenère", en: "Vigenère cipher" },
    explain: { fr: "Vigenère améliore César : la clé est un MOT, et chaque lettre du texte est décalée par la lettre correspondante de la clé (A=0, B=1…), la clé étant répétée. Avec la clé « BAC », les lettres successives sont décalées de 1, 0, 2, 1, 0, 2… Un même caractère clair est chiffré différemment selon sa place, ce qui brouille les fréquences. Il a pourtant été cassé au XIXe siècle : la longueur de clé se devine par répétition.", en: "Vigenère improves on Caesar: the key is a WORD, and each text letter is shifted by the matching key letter (A=0, B=1…), the key being repeated. With key “BAC”, successive letters shift by 1, 0, 2, 1, 0, 2… The same plain letter encrypts differently depending on position, blurring frequencies. It was still broken in the 19th century: key length can be guessed from repetitions." },
    example: "cle = 'BAC'\nprint([ord(cle[i % 3]) - 65 for i in range(6)])",
    task: { fr: "Écris vigenere(texte, cle, sens=1) : majuscules A–Z seulement, la clé n'avance que sur les lettres. sens=-1 déchiffre.", en: "Write vigenere(texte, cle, sens=1): uppercase A–Z only, the key advances only on letters. sens=-1 decrypts." },
    starter: "def vigenere(texte, cle, sens=1):\n    pass\n",
    hint: { fr: "Garde un compteur i des lettres traitées ; décalage = ord(cle[i % len(cle)]) - 65 ; multiplie par sens.", en: "Keep a counter i of processed letters; shift = ord(cle[i % len(cle)]) - 65; multiply by sens." },
    solution: "def vigenere(texte, cle, sens=1):\n    sortie = ''\n    i = 0\n    for c in texte:\n        if 'A' <= c <= 'Z':\n            d = (ord(cle[i % len(cle)]) - 65) * sens\n            sortie += chr((ord(c) - 65 + d) % 26 + 65)\n            i += 1\n        else:\n            sortie += c\n    return sortie",
    checks: ["vigenere('AAA', 'BAC') == 'BAC'", "vigenere('ATTAQUE', 'CLE') == 'CEXCBYG'", "vigenere(vigenere('MESSAGE SECRET', 'LUNE'), 'LUNE', -1) == 'MESSAGE SECRET'", "vigenere('A B', 'BC') == 'B D'", "vigenere('AAAA', 'A') == 'AAAA'"],
  },
  {
    id: "crypto-frequences", lang: 'py', group: "crypto",
    title: { fr: "Casser César par les fréquences", en: "Breaking Caesar by frequency" },
    explain: { fr: "Dans un texte français, la lettre la plus fréquente est presque toujours E. Si un texte chiffré par César a pour lettre la plus fréquente, disons, H, c'est que E est devenu H : la clé est 3. Casser un chiffre sans la clé en exploitant les statistiques de la langue s'appelle l'ANALYSE FRÉQUENTIELLE. Elle marche mieux sur les longs textes.", en: "In French text, the most frequent letter is almost always E. If a Caesar-encrypted text's most frequent letter is, say, H, then E became H: the key is 3. Breaking a cipher without the key using language statistics is called FREQUENCY ANALYSIS. It works better on long texts." },
    example: "from collections import Counter\nprint(Counter('HELLO').most_common(1))",
    task: { fr: "Écris devine_cle(chiffre) : trouve la lettre majuscule la plus fréquente (en cas d'égalité, la première dans l'alphabet) et renvoie la clé k telle que cette lettre soit un E décalé de k (0 à 25).", en: "Write devine_cle(chiffre): find the most frequent uppercase letter (ties: first in the alphabet) and return the key k such that this letter is an E shifted by k (0 to 25)." },
    starter: "from collections import Counter\n\ndef devine_cle(chiffre):\n    pass\n",
    hint: { fr: "Counter des lettres A–Z ; max avec clé (-compte, lettre) ; k = (ord(lettre) - ord('E')) % 26.", en: "Counter of A–Z letters; max with key (-count, letter); k = (ord(letter) - ord('E')) % 26." },
    solution: "from collections import Counter\n\ndef devine_cle(chiffre):\n    c = Counter(x for x in chiffre if 'A' <= x <= 'Z')\n    lettre = min(c, key=lambda x: (-c[x], x))\n    return (ord(lettre) - ord('E')) % 26",
    checks: ["devine_cle('EEE AB') == 0", "devine_cle('HHH XY') == 3", "devine_cle('ZZZZ A') == 21", "devine_cle('AAB BB') == 23", "devine_cle('ee EE') == 0"],
  },
  {
    id: "crypto-hash", lang: 'py', group: "crypto",
    title: { fr: "Hachage : une empreinte", en: "Hashing: a fingerprint" },
    explain: { fr: "Une fonction de HACHAGE transforme n'importe quelle donnée en une empreinte de taille fixe. Propriétés voulues : même entrée → même empreinte ; changer UN caractère change tout (effet avalanche) ; remonter de l'empreinte à l'entrée est impraticable. On l'utilise pour vérifier l'intégrité d'un fichier, ranger des mots de passe (on stocke l'empreinte, jamais le mot de passe), et indexer. Ici, un hachage jouet (djb2) pour comprendre ; en vrai, on utilise SHA-256 ou mieux, jamais son propre hachage.", en: "A HASH function turns any data into a fixed-size fingerprint. Wanted properties: same input → same fingerprint; changing ONE character changes everything (avalanche effect); going from fingerprint back to input is impractical. Used to verify file integrity, store passwords (store the fingerprint, never the password), and index. Here, a toy hash (djb2) to understand; in reality, use SHA-256 or better, never your own hash." },
    example: "h = 5381\nfor c in 'ab':\n    h = (h * 33 + ord(c)) % 2**32\nprint(h)",
    task: { fr: "Écris djb2(texte) : h = 5381 ; pour chaque caractère h = (h × 33 + code) modulo 2³². Puis bits_differents(a, b) : nombre de bits qui diffèrent entre deux entiers.", en: "Write djb2(texte): h = 5381; for each character h = (h × 33 + code) modulo 2³². Then bits_differents(a, b): number of bits that differ between two integers." },
    starter: "def djb2(texte):\n    pass\n\ndef bits_differents(a, b):\n    pass\n",
    hint: { fr: "bits_differents : bin(a ^ b).count('1').", en: "bits_differents: bin(a ^ b).count('1')." },
    solution: "def djb2(texte):\n    h = 5381\n    for c in texte:\n        h = (h * 33 + ord(c)) % 2 ** 32\n    return h\n\ndef bits_differents(a, b):\n    return bin(a ^ b).count('1')",
    checks: ["djb2('') == 5381", "djb2('a') == 177670", "djb2('ab') == 5863208", "djb2('bonjour') == djb2('bonjour')", "djb2('bonjour') != djb2('bonjouR')", "bits_differents(0b1010, 0b0110) == 2", "bits_differents(7, 7) == 0"],
  },
  {
    id: "crypto-pgcd", lang: 'py', group: "crypto",
    title: { fr: "PGCD et inverse modulaire", en: "GCD and modular inverse" },
    explain: { fr: "L'arithmétique modulaire est le langage de la cryptographie moderne. Deux briques : le PGCD (plus grand commun diviseur) par l'algorithme d'Euclide — pgcd(a, b) = pgcd(b, a mod b) jusqu'à b = 0 — et l'INVERSE MODULAIRE : l'entier x tel que a·x ≡ 1 (mod m), qui existe seulement si pgcd(a, m) = 1. Par exemple 3 × 5 = 15 ≡ 1 (mod 7), donc 5 est l'inverse de 3 modulo 7.", en: "Modular arithmetic is the language of modern cryptography. Two building blocks: the GCD (greatest common divisor) via Euclid's algorithm — gcd(a, b) = gcd(b, a mod b) until b = 0 — and the MODULAR INVERSE: the integer x such that a·x ≡ 1 (mod m), which exists only if gcd(a, m) = 1. For example 3 × 5 = 15 ≡ 1 (mod 7), so 5 is the inverse of 3 modulo 7." },
    example: "print(15 % 7, (3 * 5) % 7)",
    task: { fr: "Écris pgcd(a, b) (Euclide) et inverse(a, m) : l'inverse de a modulo m (entre 1 et m−1), ou None s'il n'existe pas. (Sans pow(a, -1, m) : cherche par essais.)", en: "Write pgcd(a, b) (Euclid) and inverse(a, m): a's inverse modulo m (between 1 and m−1), or None if it doesn't exist. (Without pow(a, -1, m): search by trial.)" },
    starter: "def pgcd(a, b):\n    pass\n\ndef inverse(a, m):\n    pass\n",
    hint: { fr: "pgcd : while b: a, b = b, a % b. inverse : essaie x de 1 à m-1 et teste (a * x) % m == 1.", en: "pgcd: while b: a, b = b, a % b. inverse: try x from 1 to m-1 and test (a * x) % m == 1." },
    solution: "def pgcd(a, b):\n    while b:\n        a, b = b, a % b\n    return a\n\ndef inverse(a, m):\n    for x in range(1, m):\n        if (a * x) % m == 1:\n            return x\n    return None",
    checks: ["pgcd(12, 18) == 6", "pgcd(17, 5) == 1", "pgcd(0, 9) == 9", "inverse(3, 7) == 5", "inverse(2, 4) is None", "inverse(7, 40) == 23", "(lambda x: (7 * x) % 40)(inverse(7, 40)) == 1"],
  },
  {
    id: "crypto-puissance", lang: 'py', group: "crypto",
    title: { fr: "Exponentiation modulaire rapide", en: "Fast modular exponentiation" },
    explain: { fr: "RSA et Diffie–Hellman calculent des choses comme 7^123456 mod 1000003. Calculer d'abord 7^123456 (un nombre de 100 000 chiffres) puis réduire serait absurde. On réduit À CHAQUE ÉTAPE, et on utilise l'exponentiation rapide : b^e = (b²)^(e/2) si e est pair, b × b^(e−1) sinon. Il suffit d'environ log₂(e) étapes : quelques dizaines au lieu de millions.", en: "RSA and Diffie–Hellman compute things like 7^123456 mod 1000003. Computing 7^123456 first (a 100,000-digit number) then reducing would be absurd. Reduce AT EACH STEP, and use fast exponentiation: b^e = (b²)^(e/2) if e is even, b × b^(e−1) otherwise. About log₂(e) steps suffice: dozens instead of millions." },
    example: "print(pow(7, 10, 13))",
    task: { fr: "Écris puissance_mod(b, e, m) sans utiliser pow(…, …, …) : exponentiation rapide en boucle.", en: "Write puissance_mod(b, e, m) without using pow(…, …, …): fast exponentiation in a loop." },
    starter: "def puissance_mod(b, e, m):\n    pass\n",
    hint: { fr: "resultat = 1 ; tant que e > 0 : si e est impair, resultat = resultat * b % m ; b = b * b % m ; e //= 2.", en: "result = 1; while e > 0: if e is odd, result = result * b % m; b = b * b % m; e //= 2." },
    solution: "def puissance_mod(b, e, m):\n    resultat = 1\n    b = b % m\n    while e > 0:\n        if e % 2 == 1:\n            resultat = resultat * b % m\n        b = b * b % m\n        e //= 2\n    return resultat",
    checks: ["puissance_mod(2, 10, 1000) == 24", "puissance_mod(7, 0, 13) == 1", "puissance_mod(7, 123456, 1000003) == pow(7, 123456, 1000003)", "puissance_mod(3, 200, 13) == pow(3, 200, 13)", "puissance_mod(10, 1, 7) == 3", "puissance_mod(5, 10 ** 18, 1000000007) == pow(5, 10 ** 18, 1000000007)"],
  },
  {
    id: "crypto-rsa", lang: 'py', group: "crypto",
    title: { fr: "RSA jouet", en: "Toy RSA" },
    explain: { fr: "RSA, c'est la cryptographie à clé publique : tout le monde peut chiffrer avec la clé publique, seul le détenteur de la clé privée peut déchiffrer. Construction : deux nombres premiers p et q ; n = p·q ; φ = (p−1)(q−1) ; un exposant public e premier avec φ ; la clé privée d est l'inverse de e modulo φ. Chiffrer : c = mᵉ mod n. Déchiffrer : m = cᵈ mod n. Ici avec de TOUT PETITS nombres pour comprendre : un vrai RSA utilise des nombres de plusieurs centaines de chiffres et du remplissage ; ne jamais utiliser ce code pour protéger quoi que ce soit.", en: "RSA is public-key cryptography: anyone can encrypt with the public key, only the private-key holder can decrypt. Construction: two primes p and q; n = p·q; φ = (p−1)(q−1); a public exponent e coprime to φ; the private key d is the inverse of e modulo φ. Encrypt: c = mᵉ mod n. Decrypt: m = cᵈ mod n. Here with TINY numbers to understand: real RSA uses numbers hundreds of digits long plus padding; never use this code to protect anything." },
    example: "p, q = 5, 11\nprint(p * q, (p - 1) * (q - 1))",
    task: { fr: "Écris cles(p, q, e) → ((e, n), (d, n)), puis chiffre(m, cle) et dechiffre(c, cle) (même formule : x^exposant mod n). Utilise pow(x, expo, n) et pow(e, -1, phi).", en: "Write cles(p, q, e) → ((e, n), (d, n)), then chiffre(m, cle) and dechiffre(c, cle) (same formula: x^exponent mod n). Use pow(x, expo, n) and pow(e, -1, phi)." },
    starter: "def cles(p, q, e):\n    pass\n\ndef chiffre(m, cle):\n    pass\n\ndef dechiffre(c, cle):\n    pass\n",
    hint: { fr: "n = p*q ; phi = (p-1)*(q-1) ; d = pow(e, -1, phi) ; chiffre/dechiffre : pow(x, cle[0], cle[1]).", en: "n = p*q; phi = (p-1)*(q-1); d = pow(e, -1, phi); chiffre/dechiffre: pow(x, cle[0], cle[1])." },
    solution: "def cles(p, q, e):\n    n = p * q\n    phi = (p - 1) * (q - 1)\n    d = pow(e, -1, phi)\n    return (e, n), (d, n)\n\ndef chiffre(m, cle):\n    return pow(m, cle[0], cle[1])\n\ndef dechiffre(c, cle):\n    return pow(c, cle[0], cle[1])",
    checks: ["cles(5, 11, 3) == ((3, 55), (27, 55))", "chiffre(8, (3, 55)) == 17", "dechiffre(17, (27, 55)) == 8", "(lambda pub, pri: all(dechiffre(chiffre(m, pub), pri) == m for m in range(1, 3233)))(*cles(61, 53, 17))", "cles(61, 53, 17)[1][0] == 2753"],
  },
  {
    id: "crypto-dh", lang: 'py', group: "crypto",
    title: { fr: "Échange de clés Diffie–Hellman", en: "Diffie–Hellman key exchange" },
    explain: { fr: "Comment Alice et Bob peuvent-ils se mettre d'accord sur un secret commun en parlant devant tout le monde ? Diffie–Hellman : on publie un grand nombre premier p et une base g. Alice choisit un secret a et envoie A = gᵃ mod p ; Bob choisit b et envoie B = gᵇ mod p. Alice calcule Bᵃ mod p, Bob calcule Aᵇ mod p : c'est le MÊME nombre, gᵃᵇ mod p. Un espion voit p, g, A, B mais retrouver a ou b est (pour de grands p) très difficile. Petits nombres ici, pour comprendre.", en: "How can Alice and Bob agree on a shared secret while talking in front of everyone? Diffie–Hellman: publish a large prime p and a base g. Alice picks a secret a and sends A = gᵃ mod p; Bob picks b and sends B = gᵇ mod p. Alice computes Bᵃ mod p, Bob computes Aᵇ mod p: it is the SAME number, gᵃᵇ mod p. An eavesdropper sees p, g, A, B but recovering a or b is (for large p) very hard. Small numbers here, to understand." },
    example: "print(pow(5, 6, 23), pow(5, 15, 23))",
    task: { fr: "Écris publique(g, secret, p) et secret_commun(publique_autre, secret, p). Puis un test : les deux côtés obtiennent la même valeur.", en: "Write publique(g, secret, p) and secret_commun(publique_autre, secret, p). Then a test: both sides get the same value." },
    starter: "def publique(g, secret, p):\n    pass\n\ndef secret_commun(publique_autre, secret, p):\n    pass\n",
    hint: { fr: "Les deux sont pow(base, exposant, p).", en: "Both are pow(base, exponent, p)." },
    solution: "def publique(g, secret, p):\n    return pow(g, secret, p)\n\ndef secret_commun(publique_autre, secret, p):\n    return pow(publique_autre, secret, p)",
    checks: ["publique(5, 6, 23) == 8", "publique(5, 15, 23) == 19", "secret_commun(19, 6, 23) == 2", "secret_commun(8, 15, 23) == 2", "secret_commun(publique(5, 4, 23), 9, 23) == secret_commun(publique(5, 9, 23), 4, 23)"],
  },
]
