import type { Lesson } from './lessons'

// Parcours Théorie des jeux : meilleure réponse, équilibre de Nash, jeu répété (donnant-donnant), stratégies mixtes. Contenu original.
export const jeuxLessons: Lesson[] = [
  {
    id: "jeu-dilemme", lang: 'py', group: "jeux",
    title: { fr: "Le dilemme du prisonnier : la meilleure réponse", en: "The prisoner's dilemma: the best response" },
    explain: { fr: "La THÉORIE DES JEUX étudie les décisions quand le résultat dépend aussi des choix des autres. Exemple célèbre : deux joueurs peuvent COOPÉRER ou TRAHIR. Coopérer à deux rapporte 3 chacun ; trahir seul rapporte 5 (l'autre a 0) ; trahir à deux, 1 chacun. La MEILLEURE RÉPONSE est le coup qui rapporte le plus face à un coup adverse donné. Ici, trahir est toujours la meilleure réponse… et pourtant, à deux, on finit moins bien qu'en coopérant.", en: "GAME THEORY studies decisions when the outcome also depends on others' choices. Famous example: two players can COOPERATE or BETRAY. Both cooperating gives 3 each; betraying alone gives 5 (the other gets 0); both betraying, 1 each. The BEST RESPONSE is the move that pays most against a given opponent move. Here, betraying is always the best response… and yet together they end up worse than cooperating." },
    example: "# Gains (joueur 1, joueur 2) : 'C' = coopérer, 'T' = trahir.\nGAINS = {('C', 'C'): (3, 3), ('C', 'T'): (0, 5), ('T', 'C'): (5, 0), ('T', 'T'): (1, 1)}\nprint(GAINS[('T', 'C')][0])",
    task: { fr: "Écris meilleure_reponse(gains, coup_adverse, coups=('C', 'T')) → le coup du joueur 1 qui lui rapporte le plus face à coup_adverse. Puis dominante(gains, coups=('C', 'T')) → le coup qui est la meilleure réponse à TOUS les coups adverses, sinon None. Puis optimum_social(gains, coups=('C', 'T')) → la paire de coups dont la somme des gains est la plus grande.", en: "Write meilleure_reponse(gains, coup_adverse, coups=('C', 'T')) → player 1's move that pays them most against coup_adverse. Then dominante(gains, coups=('C', 'T')) → the move that is the best response to ALL opponent moves, else None. Then optimum_social(gains, coups=('C', 'T')) → the pair of moves with the largest total payoff." },
    starter: "# Gains (joueur 1, joueur 2) : 'C' = coopérer, 'T' = trahir.\nGAINS = {('C', 'C'): (3, 3), ('C', 'T'): (0, 5), ('T', 'C'): (5, 0), ('T', 'T'): (1, 1)}\n\ndef meilleure_reponse(gains, coup_adverse, coups=('C', 'T')):\n    pass\n\ndef dominante(gains, coups=('C', 'T')):\n    pass\n\ndef optimum_social(gains, coups=('C', 'T')):\n    pass\n",
    hint: { fr: "max(coups, key=lambda c: gains[(c, coup_adverse)][0]). Pour l'optimum : max sur toutes les paires (a, b) de sum(gains[(a, b)]).", en: "max(coups, key=lambda c: gains[(c, coup_adverse)][0]). For the optimum: max over all pairs (a, b) of sum(gains[(a, b)])." },
    solution: "# Gains (joueur 1, joueur 2) : 'C' = coopérer, 'T' = trahir.\nGAINS = {('C', 'C'): (3, 3), ('C', 'T'): (0, 5), ('T', 'C'): (5, 0), ('T', 'T'): (1, 1)}\n\ndef meilleure_reponse(gains, coup_adverse, coups=('C', 'T')):\n    return max(coups, key=lambda c: gains[(c, coup_adverse)][0])\n\ndef dominante(gains, coups=('C', 'T')):\n    reps = {meilleure_reponse(gains, a, coups) for a in coups}\n    return reps.pop() if len(reps) == 1 else None\n\ndef optimum_social(gains, coups=('C', 'T')):\n    return max(((a, b) for a in coups for b in coups), key=lambda p: sum(gains[p]))",
    checks: ["meilleure_reponse(GAINS, 'C') == 'T' and meilleure_reponse(GAINS, 'T') == 'T'", "dominante(GAINS) == 'T'", "optimum_social(GAINS) == ('C', 'C')", "dominante({('A', 'A'): (2, 2), ('A', 'B'): (0, 0), ('B', 'A'): (0, 0), ('B', 'B'): (1, 1)}, ('A', 'B')) is None", "meilleure_reponse({('A', 'A'): (2, 2), ('A', 'B'): (0, 0), ('B', 'A'): (0, 0), ('B', 'B'): (1, 1)}, 'B', ('A', 'B')) == 'B'"],
  },
  {
    id: "jeu-nash", lang: 'py', group: "jeux",
    title: { fr: "Personne ne veut changer : l'équilibre de Nash", en: "Nobody wants to switch: the Nash equilibrium" },
    explain: { fr: "Un ÉQUILIBRE DE NASH est une paire de coups où AUCUN joueur ne gagnerait à changer seul de coup. Dans le dilemme du prisonnier, c'est (trahir, trahir). Certains jeux en ont plusieurs (se retrouver au même endroit), d'autres aucun en coups « purs » (pierre-feuille-ciseaux). On les trouve en vérifiant, pour chaque case, que chacun joue une meilleure réponse à l'autre.", en: "A NASH EQUILIBRIUM is a pair of moves where NO player would gain by switching alone. In the prisoner's dilemma, it is (betray, betray). Some games have several (meeting at the same place), others none in “pure” moves (rock-paper-scissors). Find them by checking, for each cell, that each player plays a best response to the other." },
    example: "# Gains (joueur 1, joueur 2) : 'C' = coopérer, 'T' = trahir.\nGAINS = {('C', 'C'): (3, 3), ('C', 'T'): (0, 5), ('T', 'C'): (5, 0), ('T', 'T'): (1, 1)}\nprint(max(g[0] for (a, b), g in GAINS.items() if b == 'T'))",
    task: { fr: "Écris equilibres(gains, coups1, coups2) → liste triée des paires (a, b) où gains[(a, b)][0] est le maximum de gains[(x, b)][0] pour x dans coups1 ET gains[(a, b)][1] le maximum de gains[(a, y)][1] pour y dans coups2.", en: "Write equilibres(gains, coups1, coups2) → sorted list of pairs (a, b) where gains[(a, b)][0] is the maximum of gains[(x, b)][0] over x in coups1 AND gains[(a, b)][1] is the maximum of gains[(a, y)][1] over y in coups2." },
    starter: "# Gains (joueur 1, joueur 2) : 'C' = coopérer, 'T' = trahir.\nGAINS = {('C', 'C'): (3, 3), ('C', 'T'): (0, 5), ('T', 'C'): (5, 0), ('T', 'T'): (1, 1)}\n\ndef equilibres(gains, coups1, coups2):\n    pass\n",
    hint: { fr: "Double boucle ; deux conditions avec max(...). sorted(...) à la fin.", en: "Double loop; two conditions with max(...). sorted(...) at the end." },
    solution: "# Gains (joueur 1, joueur 2) : 'C' = coopérer, 'T' = trahir.\nGAINS = {('C', 'C'): (3, 3), ('C', 'T'): (0, 5), ('T', 'C'): (5, 0), ('T', 'T'): (1, 1)}\n\ndef equilibres(gains, coups1, coups2):\n    res = []\n    for a in coups1:\n        for b in coups2:\n            ok1 = gains[(a, b)][0] == max(gains[(x, b)][0] for x in coups1)\n            ok2 = gains[(a, b)][1] == max(gains[(a, y)][1] for y in coups2)\n            if ok1 and ok2:\n                res.append((a, b))\n    return sorted(res)",
    checks: ["equilibres(GAINS, 'CT', 'CT') == [('T', 'T')]", "equilibres({('A', 'A'): (2, 2), ('A', 'B'): (0, 0), ('B', 'A'): (0, 0), ('B', 'B'): (1, 1)}, 'AB', 'AB') == [('A', 'A'), ('B', 'B')]", "(lambda R: equilibres({(a, b): (R[a][b], -R[a][b]) for a in 'PFC' for b in 'PFC'}, 'PFC', 'PFC') == [])({'P': {'P': 0, 'F': -1, 'C': 1}, 'F': {'P': 1, 'F': 0, 'C': -1}, 'C': {'P': -1, 'F': 1, 'C': 0}})", "equilibres({('H', 'G'): (3, 1), ('H', 'D'): (0, 0), ('B', 'G'): (0, 0), ('B', 'D'): (1, 3)}, 'HB', 'GD') == [('B', 'D'), ('H', 'G')]"],
  },
  {
    id: "jeu-repete", lang: 'py', group: "jeux",
    title: { fr: "Jouer plusieurs fois : donnant-donnant", en: "Playing many times: tit-for-tat" },
    explain: { fr: "Si l'on rejoue le dilemme plusieurs fois, la confiance devient possible. Dans les tournois organisés par Robert Axelrod (1980), une stratégie très simple a gagné : DONNANT-DONNANT — coopérer au premier tour, puis copier le dernier coup de l'adversaire. Elle est gentille, réplique à la trahison et pardonne. Une stratégie est une fonction qui reçoit l'historique des coups adverses et renvoie 'C' ou 'T'.", en: "If the dilemma is replayed many times, trust becomes possible. In the tournaments run by Robert Axelrod (1980), a very simple strategy won: TIT-FOR-TAT — cooperate on the first round, then copy the opponent's last move. It is nice, retaliates against betrayal and forgives. A strategy is a function that receives the opponent's move history and returns 'C' or 'T'." },
    example: "toujours_trahir = lambda historique: 'T'\nprint(toujours_trahir(['C', 'C']))",
    task: { fr: "Écris donnant_donnant(historique) et rancunier(historique) (coopère jusqu'à la première trahison adverse, puis trahit toujours). Puis jouer(s1, s2, tours, gains=GAINS) → (score1, score2) après tours manches ; chaque stratégie reçoit la liste des coups PASSÉS de l'autre.", en: "Write donnant_donnant(historique) and rancunier(historique) (cooperates until the opponent's first betrayal, then always betrays). Then jouer(s1, s2, tours, gains=GAINS) → (score1, score2) after tours rounds; each strategy receives the list of the other's PAST moves." },
    starter: "# Gains (joueur 1, joueur 2) : 'C' = coopérer, 'T' = trahir.\nGAINS = {('C', 'C'): (3, 3), ('C', 'T'): (0, 5), ('T', 'C'): (5, 0), ('T', 'T'): (1, 1)}\n\ndef toujours_trahir(historique):\n    return 'T'\n\ndef toujours_cooperer(historique):\n    return 'C'\n\ndef donnant_donnant(historique):\n    pass\n\ndef rancunier(historique):\n    pass\n\ndef jouer(s1, s2, tours, gains=GAINS):\n    pass\n",
    hint: { fr: "Garde h1 et h2 (coups de chacun). À chaque manche : a = s1(h2[:]), b = s2(h1[:]), ajoute gains[(a, b)] aux scores, puis h1.append(a), h2.append(b).", en: "Keep h1 and h2 (each player's moves). Each round: a = s1(h2[:]), b = s2(h1[:]), add gains[(a, b)] to the scores, then h1.append(a), h2.append(b)." },
    solution: "# Gains (joueur 1, joueur 2) : 'C' = coopérer, 'T' = trahir.\nGAINS = {('C', 'C'): (3, 3), ('C', 'T'): (0, 5), ('T', 'C'): (5, 0), ('T', 'T'): (1, 1)}\n\ndef toujours_trahir(historique):\n    return 'T'\n\ndef toujours_cooperer(historique):\n    return 'C'\n\ndef donnant_donnant(historique):\n    return historique[-1] if historique else 'C'\n\ndef rancunier(historique):\n    return 'T' if 'T' in historique else 'C'\n\ndef jouer(s1, s2, tours, gains=GAINS):\n    h1, h2, sc1, sc2 = [], [], 0, 0\n    for _ in range(tours):\n        a, b = s1(h2[:]), s2(h1[:])\n        g1, g2 = gains[(a, b)]\n        sc1 += g1\n        sc2 += g2\n        h1.append(a)\n        h2.append(b)\n    return sc1, sc2",
    checks: ["donnant_donnant([]) == 'C' and donnant_donnant(['C', 'T']) == 'T'", "rancunier(['C', 'T', 'C']) == 'T' and rancunier([]) == 'C'", "jouer(donnant_donnant, donnant_donnant, 10) == (30, 30)", "jouer(donnant_donnant, toujours_trahir, 10) == (9, 14)", "jouer(toujours_trahir, toujours_cooperer, 3) == (15, 0)", "jouer(rancunier, donnant_donnant, 5) == (15, 15)"],
  },
  {
    id: "jeu-mixte", lang: 'py', group: "jeux",
    title: { fr: "Rester imprévisible : l'équilibre en stratégies mixtes", en: "Staying unpredictable: mixed-strategy equilibrium" },
    explain: { fr: "À pierre-feuille-ciseaux ou au tir au but, être prévisible fait perdre. On joue alors au HASARD avec des probabilités bien choisies : c'est une STRATÉGIE MIXTE. Dans un jeu 2×2, le joueur 1 choisit sa probabilité p de jouer son premier coup pour que l'ADVERSAIRE soit INDIFFÉRENT entre ses deux coups (il n'a alors aucun moyen d'en profiter). John Nash a montré qu'un tel équilibre existe toujours.", en: "In rock-paper-scissors or a penalty kick, being predictable makes you lose. So you play at RANDOM with well-chosen probabilities: a MIXED STRATEGY. In a 2×2 game, player 1 picks the probability p of playing their first move so that the OPPONENT is INDIFFERENT between their two moves (they then have no way to exploit it). John Nash proved such an equilibrium always exists." },
    example: "B = [[-1, 1], [1, -1]]  # gains du joueur 2\np = 0.5\nprint(p * B[0][0] + (1 - p) * B[1][0], p * B[0][1] + (1 - p) * B[1][1])",
    task: { fr: "B[i][j] est le gain du joueur 2 quand le joueur 1 joue i et le joueur 2 joue j. Écris gain_attendu(p, B, j) → p·B[0][j] + (1 − p)·B[1][j]. Puis p_indifference(B) → le p qui rend égaux gain_attendu(p, B, 0) et gain_attendu(p, B, 1), ou None s'il n'existe pas entre 0 et 1 (ou si le dénominateur est nul).", en: "B[i][j] is player 2's payoff when player 1 plays i and player 2 plays j. Write gain_attendu(p, B, j) → p·B[0][j] + (1 − p)·B[1][j]. Then p_indifference(B) → the p making gain_attendu(p, B, 0) and gain_attendu(p, B, 1) equal, or None if it doesn't exist between 0 and 1 (or the denominator is zero)." },
    starter: "def gain_attendu(p, B, j):\n    pass\n\ndef p_indifference(B):\n    pass\n",
    hint: { fr: "Égalise : p·(B00 − B01) + (1 − p)·(B10 − B11) = 0 → p = (B11 − B10) / ((B00 − B01) − (B10 − B11)).", en: "Set equal: p·(B00 − B01) + (1 − p)·(B10 − B11) = 0 → p = (B11 − B10) / ((B00 − B01) − (B10 − B11))." },
    solution: "def gain_attendu(p, B, j):\n    return p * B[0][j] + (1 - p) * B[1][j]\n\ndef p_indifference(B):\n    den = (B[0][0] - B[0][1]) - (B[1][0] - B[1][1])\n    if den == 0:\n        return None\n    p = (B[1][1] - B[1][0]) / den\n    return p if 0 <= p <= 1 else None",
    checks: ["gain_attendu(0.5, [[-1, 1], [1, -1]], 0) == 0", "p_indifference([[-1, 1], [1, -1]]) == 0.5", "(lambda B: abs(gain_attendu(p_indifference(B), B, 0) - gain_attendu(p_indifference(B), B, 1)) < 1e-12)([[1, 0], [0, 3]])", "abs(p_indifference([[1, 0], [0, 3]]) - 0.75) < 1e-12", "p_indifference([[1, 1], [1, 1]]) is None", "p_indifference([[2, 0], [3, 1]]) is None"],
  },
]
