import type { Lesson } from './lessons'

// Parcours C++ : lire et prédire (réponses vérifiées avec g++ à la génération). Contenu original.
export const cppLessons: Lesson[] = [
  {
    id: "cpp-cout", lang: 'py', langue: "cpp", group: "cpp",
    title: { fr: "C++ : cout et string", en: "C++: cout and string" },
    explain: { fr: "Le C++ ajoute au C des outils de haut niveau tout en restant très rapide (jeux vidéo, finance, robotique, navigateurs). std::cout << affiche, std::endl ou '\\n' passe à la ligne. std::string est un vrai type texte : on peut concaténer avec + et connaître sa taille avec .size(). (Dans le navigateur on ne compile pas encore le C++ : ici tu apprends à le LIRE. La réponse a été vérifiée avec un vrai compilateur.)", en: "C++ adds high-level tools to C while staying very fast (video games, finance, robotics, browsers). std::cout << prints, std::endl or '\\n' starts a new line. std::string is a real text type: concatenate with + and get its length with .size(). (The browser does not compile C++ yet: here you learn to READ it. The answer was checked with a real compiler.)" },
    example: '',
    task: { fr: 'Que va afficher ce programme ?', en: 'What will this program print?' },
    starter: '',
    hint: { fr: "Compte aussi l'espace.", en: "Count the space too." },
    solution: "Finjaro Learn\n13 Fin",
    checks: [],
    predict: { code: "#include <iostream>\n#include <string>\n\nint main() {\n    std::string nom = \"Finjaro\";\n    std::string s = nom + \" Learn\";\n    std::cout << s << '\\n';\n    std::cout << s.size() << \" \" << s.substr(0, 3) << '\\n';\n    return 0;\n}", answer: "Finjaro Learn\n13 Fin", why: { fr: "Concaténation : « Finjaro Learn » (13 caractères avec l'espace). substr(0, 3) : les 3 premiers caractères, « Fin ».", en: "Concatenation: “Finjaro Learn” (13 characters including the space). substr(0, 3): the first 3 characters, “Fin”." } },
  },
  {
    id: "cpp-references", lang: 'py', langue: "cpp", group: "cpp",
    title: { fr: "C++ : les références", en: "C++: references" },
    explain: { fr: "Une RÉFÉRENCE (int& r = x) est un autre nom pour la même variable : modifier r modifie x. En paramètre (void f(int& n)), elle permet à une fonction de modifier l'original sans écrire de pointeurs. const int& permet de lire sans copier et sans risque de modifier. (Dans le navigateur on ne compile pas encore le C++ : ici tu apprends à le LIRE. La réponse a été vérifiée avec un vrai compilateur.)", en: "A REFERENCE (int& r = x) is another name for the same variable: changing r changes x. As a parameter (void f(int& n)), it lets a function change the original without writing pointers. const int& lets you read without copying and without any risk of modifying. (The browser does not compile C++ yet: here you learn to READ it. The answer was checked with a real compiler.)" },
    example: '',
    task: { fr: 'Que va afficher ce programme ?', en: 'What will this program print?' },
    starter: '',
    hint: { fr: "Le & dans le paramètre fait toute la différence.", en: "The & in the parameter makes all the difference." },
    solution: "10",
    checks: [],
    predict: { code: "#include <iostream>\n\nvoid ajoute(int& n, int k) { n += k; }\nvoid ajoute_copie(int n, int k) { n += k; }\n\nint main() {\n    int x = 5;\n    int& r = x;\n    r = 7;\n    ajoute(x, 3);\n    ajoute_copie(x, 100);\n    std::cout << x << '\\n';\n    return 0;\n}", answer: "10", why: { fr: "r est x : x = 7. ajoute reçoit une référence : x = 10. ajoute_copie travaille sur une copie : x reste 10.", en: "r is x: x = 7. ajoute gets a reference: x = 10. ajoute_copie works on a copy: x stays 10." } },
  },
  {
    id: "cpp-vector", lang: 'py', langue: "cpp", group: "cpp",
    title: { fr: "C++ : vector", en: "C++: vector" },
    explain: { fr: "std::vector est un tableau qui grandit tout seul : push_back ajoute à la fin, size() donne le nombre d'éléments, et la boucle for (int v : t) parcourt tous les éléments. C'est la structure la plus utilisée du C++, l'équivalent des listes Python. (Dans le navigateur on ne compile pas encore le C++ : ici tu apprends à le LIRE. La réponse a été vérifiée avec un vrai compilateur.)", en: "std::vector is an array that grows by itself: push_back appends, size() gives the number of elements, and the loop for (int v : t) walks all the elements. It is the most used C++ structure, the equivalent of Python lists. (The browser does not compile C++ yet: here you learn to READ it. The answer was checked with a real compiler.)" },
    example: '',
    task: { fr: 'Que va afficher ce programme ?', en: 'What will this program print?' },
    starter: '',
    hint: { fr: "push_back ajoute à la fin.", en: "push_back appends at the end." },
    solution: "5 14 5",
    checks: [],
    predict: { code: "#include <iostream>\n#include <vector>\n\nint main() {\n    std::vector<int> t = {3, 1, 4};\n    t.push_back(1);\n    t.push_back(5);\n    int s = 0;\n    for (int v : t) s += v;\n    std::cout << t.size() << \" \" << s << \" \" << t.back() << '\\n';\n    return 0;\n}", answer: "5 14 5", why: { fr: "Après deux push_back : {3, 1, 4, 1, 5} — 5 éléments, somme 14, dernier élément (back) 5.", en: "After two push_back: {3, 1, 4, 1, 5} — 5 elements, sum 14, last element (back) 5." } },
  },
  {
    id: "cpp-classes", lang: 'py', langue: "cpp", group: "cpp",
    title: { fr: "C++ : classes et constructeurs", en: "C++: classes and constructors" },
    explain: { fr: "Une classe regroupe des données (attributs) et des actions (méthodes). Le CONSTRUCTEUR initialise l'objet à sa création. private cache les données : on ne les modifie que par les méthodes, ce qui garantit que l'objet reste cohérent (ici, un solde jamais négatif). (Dans le navigateur on ne compile pas encore le C++ : ici tu apprends à le LIRE. La réponse a été vérifiée avec un vrai compilateur.)", en: "A class groups data (attributes) and actions (methods). The CONSTRUCTOR initialises the object when it is created. private hides the data: it can only be changed through methods, which guarantees the object stays consistent (here, a balance never negative). (The browser does not compile C++ yet: here you learn to READ it. The answer was checked with a real compiler.)" },
    example: '',
    task: { fr: 'Que va afficher ce programme ?', en: 'What will this program print?' },
    starter: '',
    hint: { fr: "cout affiche true comme 1 et false comme 0.", en: "cout prints true as 1 and false as 0." },
    solution: "1 0 70",
    checks: [],
    predict: { code: "#include <iostream>\n\nclass Compte {\n    int solde;\npublic:\n    Compte(int depart) : solde(depart) {}\n    bool retire(int m) {\n        if (m > solde) return false;\n        solde -= m;\n        return true;\n    }\n    int lire() const { return solde; }\n};\n\nint main() {\n    Compte c(100);\n    std::cout << c.retire(30) << \" \" << c.retire(80) << \" \" << c.lire() << '\\n';\n    return 0;\n}", answer: "1 0 70", why: { fr: "100 − 30 = 70 : premier retrait accepté (1). 80 > 70 : refusé (0). Solde final 70. Un bool s'affiche 1 ou 0 avec cout.", en: "100 − 30 = 70: first withdrawal accepted (1). 80 > 70: refused (0). Final balance 70. A bool prints as 1 or 0 with cout." } },
  },
  {
    id: "cpp-raii", lang: 'py', langue: "cpp", group: "cpp",
    title: { fr: "C++ : destructeurs et RAII", en: "C++: destructors and RAII" },
    explain: { fr: "Quand un objet sort de sa portée (fin d'un bloc { }), son DESTRUCTEUR (~Nom) est appelé automatiquement, dans l'ordre INVERSE de création. C'est le principe RAII : une ressource (fichier, mémoire, verrou) est libérée automatiquement, même en cas d'erreur. Plus besoin d'oublier un free. (Dans le navigateur on ne compile pas encore le C++ : ici tu apprends à le LIRE. La réponse a été vérifiée avec un vrai compilateur.)", en: "When an object goes out of scope (end of a { } block), its DESTRUCTOR (~Name) is called automatically, in REVERSE order of creation. That's the RAII principle: a resource (file, memory, lock) is released automatically, even on error. No more forgotten free. (The browser does not compile C++ yet: here you learn to READ it. The answer was checked with a real compiler.)" },
    example: '',
    task: { fr: 'Que va afficher ce programme ?', en: 'What will this program print?' },
    starter: '',
    hint: { fr: "Les destructeurs s'appellent dans l'ordre inverse, à la fin de chaque bloc.", en: "Destructors run in reverse order, at the end of each block." },
    solution: "+A\n+B\n+C\n-C\n-B\nfin\n-A",
    checks: [],
    predict: { code: "#include <iostream>\n#include <string>\n\nstruct Trace {\n    std::string n;\n    Trace(std::string s) : n(s) { std::cout << \"+\" << n << '\\n'; }\n    ~Trace() { std::cout << \"-\" << n << '\\n'; }\n};\n\nint main() {\n    Trace a(\"A\");\n    {\n        Trace b(\"B\");\n        Trace c(\"C\");\n    }\n    std::cout << \"fin\" << '\\n';\n    return 0;\n}", answer: "+A\n+B\n+C\n-C\n-B\nfin\n-A", why: { fr: "A, B, C sont créés. À la fin du bloc intérieur, C puis B sont détruits (ordre inverse). Puis « fin », et enfin A est détruit en sortant de main.", en: "A, B, C are created. At the end of the inner block, C then B are destroyed (reverse order). Then “fin”, and finally A is destroyed when leaving main." } },
  },
  {
    id: "cpp-templates", lang: 'py', langue: "cpp", group: "cpp",
    title: { fr: "C++ : templates", en: "C++: templates" },
    explain: { fr: "Un TEMPLATE écrit une fonction une seule fois pour TOUS les types : template <typename T> T plus_grand(T a, T b). Le compilateur fabrique une version pour int, une pour double, une pour std::string… La bibliothèque standard (vector, map, sort) est entièrement faite de templates. (Dans le navigateur on ne compile pas encore le C++ : ici tu apprends à le LIRE. La réponse a été vérifiée avec un vrai compilateur.)", en: "A TEMPLATE writes a function once for ALL types: template <typename T> T plus_grand(T a, T b). The compiler generates a version for int, one for double, one for std::string… The standard library (vector, map, sort) is built entirely from templates. (The browser does not compile C++ yet: here you learn to READ it. The answer was checked with a real compiler.)" },
    example: '',
    task: { fr: 'Que va afficher ce programme ?', en: 'What will this program print?' },
    starter: '',
    hint: { fr: "Entre deux textes, > compare l'ordre alphabétique.", en: "Between two strings, > compares alphabetical order." },
    solution: "9\n2.5\npomme",
    checks: [],
    predict: { code: "#include <iostream>\n#include <string>\n\ntemplate <typename T>\nT plus_grand(T a, T b) { return a > b ? a : b; }\n\nint main() {\n    std::cout << plus_grand(3, 9) << '\\n';\n    std::cout << plus_grand(2.5, 1.5) << '\\n';\n    std::cout << plus_grand(std::string(\"pomme\"), std::string(\"banane\")) << '\\n';\n    return 0;\n}", answer: "9\n2.5\npomme", why: { fr: "Pour les nombres, le plus grand ; pour les textes, l'ordre alphabétique : « pomme » vient après « banane », donc il est « plus grand ».", en: "For numbers, the larger one; for text, alphabetical order: “pomme” comes after “banane”, so it is “greater”." } },
  },
  {
    id: "cpp-stl", lang: 'py', langue: "cpp", group: "cpp",
    title: { fr: "C++ : la bibliothèque standard", en: "C++: the standard library" },
    explain: { fr: "La STL fournit des structures et des algorithmes prêts à l'emploi et très rapides : std::sort trie, std::map associe des clés triées à des valeurs (comme un dictionnaire, mais parcouru dans l'ordre des clés), std::count compte. Les connaître évite de réécrire (et de rater) ce qui existe déjà. (Dans le navigateur on ne compile pas encore le C++ : ici tu apprends à le LIRE. La réponse a été vérifiée avec un vrai compilateur.)", en: "The STL provides ready-made, very fast structures and algorithms: std::sort sorts, std::map maps sorted keys to values (like a dictionary, but walked in key order), std::count counts. Knowing them avoids rewriting (and getting wrong) what already exists. (The browser does not compile C++ yet: here you learn to READ it. The answer was checked with a real compiler.)" },
    example: '',
    task: { fr: 'Que va afficher ce programme ?', en: 'What will this program print?' },
    starter: '',
    hint: { fr: "Les trois nombres sont affichés sans espace entre eux.", en: "The three numbers are printed with no space between them." },
    solution: "228 2\nane=1 chat=2 ",
    checks: [],
    predict: { code: "#include <algorithm>\n#include <iostream>\n#include <map>\n#include <string>\n#include <vector>\n\nint main() {\n    std::vector<int> v = {5, 2, 8, 2};\n    std::sort(v.begin(), v.end());\n    std::cout << v[0] << v[1] << v[3] << \" \" << std::count(v.begin(), v.end(), 2) << '\\n';\n    std::map<std::string, int> m;\n    for (std::string mot : {\"chat\", \"ane\", \"chat\"}) m[mot]++;\n    for (auto& [cle, n] : m) std::cout << cle << \"=\" << n << \" \";\n    std::cout << '\\n';\n    return 0;\n}", answer: "228 2\nane=1 chat=2 ", why: { fr: "Trié : {2, 2, 5, 8} → v[0] v[1] v[3] = 2 2 8 collés (228), et 2 apparaît 2 fois. La map compte les mots et les parcourt dans l'ordre alphabétique : ane=1 puis chat=2 (avec un espace final).", en: "Sorted: {2, 2, 5, 8} → v[0] v[1] v[3] = 2 2 8 stuck together (228), and 2 appears twice. The map counts words and walks them alphabetically: ane=1 then chat=2 (with a trailing space)." } },
  },
]
