import type { Lesson } from './lessons'

// Parcours Maths pour l'IA : vecteurs, matrices, dérivées, gradient, probabilités, entropie, softmax (Python pur, hors ligne). Contenu original.
export const mathsLessons: Lesson[] = [
  {
    id: "maths-dot", lang: 'py', group: "maths",
    title: { fr: "Vecteurs : produit scalaire et norme", en: "Vectors: dot product and norm" },
    explain: { fr: "Un vecteur est une liste de nombres : un point, une flèche, ou les « caractéristiques » d'un objet. Deux opérations sont partout en IA. Le PRODUIT SCALAIRE : on multiplie terme à terme puis on additionne (a·b = a1·b1 + a2·b2 + …). La NORME : la longueur du vecteur, √(a·a). Un neurone artificiel calcule justement un produit scalaire entre ses entrées et ses poids.", en: "A vector is a list of numbers: a point, an arrow, or an object's “features”. Two operations are everywhere in AI. The DOT PRODUCT: multiply term by term then add (a·b = a1·b1 + a2·b2 + …). The NORM: the vector's length, √(a·a). An artificial neuron computes exactly a dot product between its inputs and its weights." },
    example: "a = [1, 2]\nb = [3, 4]\nprint(sum(x * y for x, y in zip(a, b)))",
    task: { fr: "Écris produit_scalaire(a, b) et norme(a) (la racine carrée avec math.sqrt).", en: "Write produit_scalaire(a, b) and norme(a) (square root with math.sqrt)." },
    starter: "import math\n\ndef produit_scalaire(a, b):\n    pass\n\ndef norme(a):\n    pass\n",
    hint: { fr: "zip(a, b) donne les paires ; norme(a) = math.sqrt(produit_scalaire(a, a)).", en: "zip(a, b) gives the pairs; norme(a) = math.sqrt(produit_scalaire(a, a))." },
    solution: "import math\n\ndef produit_scalaire(a, b):\n    return sum(x * y for x, y in zip(a, b))\n\ndef norme(a):\n    return math.sqrt(produit_scalaire(a, a))",
    checks: ["produit_scalaire([1, 2], [3, 4]) == 11", "produit_scalaire([1, 0], [0, 1]) == 0", "norme([3, 4]) == 5.0", "norme([0, 0, 0]) == 0", "produit_scalaire([2, -1, 3], [1, 4, 0]) == -2"],
  },
  {
    id: "maths-cos", lang: 'py', group: "maths",
    title: { fr: "Similarité cosinus", en: "Cosine similarity" },
    explain: { fr: "Comment savoir si deux textes (représentés par des vecteurs, les « embeddings ») se ressemblent ? On regarde l'ANGLE entre eux : cos θ = (a·b) / (‖a‖·‖b‖). Résultat entre −1 et 1 : 1 = même direction, 0 = sans rapport (perpendiculaires), −1 = opposés. C'est la mesure qu'utilisent la recherche sémantique et le RAG. La longueur des vecteurs ne compte pas, seulement leur direction.", en: "How do you tell whether two texts (represented as vectors, “embeddings”) are alike? Look at the ANGLE between them: cos θ = (a·b) / (‖a‖·‖b‖). Result between −1 and 1: 1 = same direction, 0 = unrelated (perpendicular), −1 = opposite. This is what semantic search and RAG use. Length doesn't matter, only direction." },
    example: "import math\nprint(math.sqrt(2) / 2)",
    task: { fr: "Écris cosinus(a, b). Si l'un des vecteurs est nul, renvoie 0.0.", en: "Write cosinus(a, b). If either vector is zero, return 0.0." },
    starter: "import math\n\ndef cosinus(a, b):\n    pass\n",
    hint: { fr: "produit scalaire / (norme a × norme b) ; teste d'abord les normes nulles.", en: "dot / (norm a × norm b); test zero norms first." },
    solution: "import math\n\ndef cosinus(a, b):\n    na = math.sqrt(sum(x * x for x in a))\n    nb = math.sqrt(sum(x * x for x in b))\n    if na == 0 or nb == 0:\n        return 0.0\n    return sum(x * y for x, y in zip(a, b)) / (na * nb)",
    checks: ["abs(cosinus([1, 0], [1, 0]) - 1) < 1e-9", "abs(cosinus([1, 0], [0, 1])) < 1e-9", "abs(cosinus([1, 2], [-1, -2]) + 1) < 1e-9", "abs(cosinus([1, 2], [10, 20]) - 1) < 1e-9", "cosinus([0, 0], [1, 2]) == 0.0", "abs(cosinus([1, 1], [1, 0]) - 0.7071067811865476) < 1e-9"],
  },
  {
    id: "maths-matmul", lang: 'py', group: "maths",
    title: { fr: "Produit de matrices", en: "Matrix product" },
    explain: { fr: "Une matrice est un tableau de nombres ; une couche de réseau de neurones, c'est une multiplication de matrices. La case (i, j) du produit A×B est le produit scalaire de la ligne i de A avec la colonne j de B. Condition : le nombre de colonnes de A égale le nombre de lignes de B. Une matrice 2×3 fois une 3×2 donne une 2×2.", en: "A matrix is a table of numbers; a neural network layer is a matrix multiplication. Cell (i, j) of A×B is the dot product of row i of A with column j of B. Condition: A's number of columns equals B's number of rows. A 2×3 times a 3×2 gives a 2×2." },
    example: "A = [[1, 2], [3, 4]]\nprint(A[0], [row[0] for row in A])",
    task: { fr: "Écris produit_matrices(A, B) (listes de listes) sans NumPy.", en: "Write produit_matrices(A, B) (lists of lists) without NumPy." },
    starter: "def produit_matrices(A, B):\n    pass\n",
    hint: { fr: "Pour chaque ligne de A et chaque colonne j de B : sum(a * b[j] for a, b in zip(ligne, B)).", en: "For each row of A and each column j of B: sum(a * b[j] for a, b in zip(row, B))." },
    solution: "def produit_matrices(A, B):\n    colonnes = len(B[0])\n    return [[sum(a * b[j] for a, b in zip(ligne, B)) for j in range(colonnes)] for ligne in A]",
    checks: ["produit_matrices([[1, 2], [3, 4]], [[5, 6], [7, 8]]) == [[19, 22], [43, 50]]", "produit_matrices([[1, 2, 3]], [[1], [2], [3]]) == [[14]]", "produit_matrices([[1, 0], [0, 1]], [[9, 8], [7, 6]]) == [[9, 8], [7, 6]]", "produit_matrices([[1, 2, 3], [4, 5, 6]], [[1, 0], [0, 1], [1, 1]]) == [[4, 5], [10, 11]]"],
  },
  {
    id: "maths-deriv", lang: 'py', group: "maths",
    title: { fr: "Dérivée : la pente", en: "Derivative: the slope" },
    explain: { fr: "La dérivée d'une fonction en un point est sa PENTE : de combien f varie quand x bouge un tout petit peu. On peut l'approcher sans formule : f'(x) ≈ (f(x+h) − f(x−h)) / (2h) avec h très petit (1e-5). C'est la base de l'apprentissage : pour savoir dans quel sens changer un poids, on regarde la pente de l'erreur.", en: "A function's derivative at a point is its SLOPE: how much f changes when x moves a tiny bit. It can be approximated without a formula: f'(x) ≈ (f(x+h) − f(x−h)) / (2h) with h very small (1e-5). It is the basis of learning: to know which way to change a weight, look at the slope of the error." },
    example: "f = lambda x: x ** 2\nh = 1e-5\nprint((f(3 + h) - f(3 - h)) / (2 * h))",
    task: { fr: "Écris derivee(f, x, h=1e-5) : la pente numérique centrée.", en: "Write derivee(f, x, h=1e-5): the centered numerical slope." },
    starter: "def derivee(f, x, h=1e-5):\n    pass\n",
    hint: { fr: "(f(x + h) - f(x - h)) / (2 * h)", en: "(f(x + h) - f(x - h)) / (2 * h)" },
    solution: "def derivee(f, x, h=1e-5):\n    return (f(x + h) - f(x - h)) / (2 * h)",
    checks: ["abs(derivee(lambda x: x ** 2, 3) - 6) < 1e-6", "abs(derivee(lambda x: 5 * x + 1, 10) - 5) < 1e-6", "abs(derivee(lambda x: x ** 3, 2) - 12) < 1e-4", "abs(derivee(lambda x: 7, 4)) < 1e-9", "abs(derivee(lambda x: x ** 2, 0)) < 1e-9"],
  },
  {
    id: "maths-descente", lang: 'py', group: "maths",
    title: { fr: "Descente de gradient", en: "Gradient descent" },
    explain: { fr: "Pour minimiser une fonction, on descend la pente : x ← x − taux × f'(x). Pente positive → on recule, négative → on avance ; la pente s'aplatit près du minimum, donc les pas raccourcissent d'eux-mêmes. Le TAUX d'apprentissage règle la taille des pas : trop petit, c'est lent ; trop grand, on rebondit et on diverge. Entraîner un réseau, c'est exactement ça, avec des millions de x.", en: "To minimize a function, walk down the slope: x ← x − rate × f'(x). Positive slope → step back, negative → step forward; the slope flattens near the minimum, so steps shrink by themselves. The learning RATE sets the step size: too small is slow; too big and you bounce and diverge. Training a network is exactly this, with millions of x." },
    example: "x = 5.0\nfor _ in range(3):\n    x = x - 0.1 * (2 * x)\nprint(x)",
    task: { fr: "Écris descente(derivee, x0, taux, pas) : part de x0, applique « pas » mises à jour x = x − taux × derivee(x), renvoie x.", en: "Write descente(derivee, x0, taux, pas): start at x0, apply “pas” updates x = x − taux × derivee(x), return x." },
    starter: "def descente(derivee, x0, taux, pas):\n    pass\n",
    hint: { fr: "Une boucle for _ in range(pas) qui met à jour x.", en: "A loop for _ in range(pas) updating x." },
    solution: "def descente(derivee, x0, taux, pas):\n    x = x0\n    for _ in range(pas):\n        x = x - taux * derivee(x)\n    return x",
    checks: ["abs(descente(lambda x: 2 * x, 5.0, 0.1, 100)) < 1e-6", "abs(descente(lambda x: 2 * (x - 3), 0.0, 0.1, 200) - 3) < 1e-6", "descente(lambda x: 2 * x, 5.0, 0.1, 0) == 5.0", "abs(descente(lambda x: 2 * x, 1.0, 0.5, 1)) < 1e-9", "abs(descente(lambda x: 2 * x, 1.0, 1.5, 10)) > 100"],
  },
  {
    id: "maths-moyenne", lang: 'py', group: "maths",
    title: { fr: "Moyenne, variance, écart-type", en: "Mean, variance, standard deviation" },
    explain: { fr: "La MOYENNE résume le centre d'une série. La VARIANCE mesure sa dispersion : la moyenne des carrés des écarts à la moyenne. L'ÉCART-TYPE est sa racine carrée, dans la même unité que les données. Deux séries de même moyenne peuvent être très différentes : [5, 5, 5] et [0, 5, 10] ont toutes deux la moyenne 5. Normaliser (retirer la moyenne, diviser par l'écart-type) est la première étape de presque tout apprentissage.", en: "The MEAN summarizes a series' center. The VARIANCE measures its spread: the mean of squared deviations from the mean. The STANDARD DEVIATION is its square root, in the data's unit. Two series with the same mean can be very different: [5, 5, 5] and [0, 5, 10] both have mean 5. Normalizing (subtract the mean, divide by the standard deviation) is the first step of almost all learning." },
    example: "xs = [2, 4, 6]\nm = sum(xs) / len(xs)\nprint(m, sum((x - m) ** 2 for x in xs) / len(xs))",
    task: { fr: "Écris moyenne(xs), variance(xs) (population : on divise par n) et ecart_type(xs).", en: "Write moyenne(xs), variance(xs) (population: divide by n) and ecart_type(xs)." },
    starter: "import math\n\ndef moyenne(xs):\n    pass\n\ndef variance(xs):\n    pass\n\ndef ecart_type(xs):\n    pass\n",
    hint: { fr: "variance = moyenne des (x - m) ** 2 ; ecart_type = racine de la variance.", en: "variance = mean of (x - m) ** 2; ecart_type = square root of the variance." },
    solution: "import math\n\ndef moyenne(xs):\n    return sum(xs) / len(xs)\n\ndef variance(xs):\n    m = moyenne(xs)\n    return sum((x - m) ** 2 for x in xs) / len(xs)\n\ndef ecart_type(xs):\n    return math.sqrt(variance(xs))",
    checks: ["moyenne([2, 4, 6]) == 4", "variance([2, 4, 6]) == 8 / 3", "variance([5, 5, 5]) == 0", "moyenne([0, 5, 10]) == 5", "abs(ecart_type([0, 5, 10]) - 4.08248290463863) < 1e-9", "ecart_type([1, 1]) == 0"],
  },
  {
    id: "maths-bayes", lang: 'py', group: "maths",
    title: { fr: "Probabilités : le théorème de Bayes", en: "Probability: Bayes theorem" },
    explain: { fr: "Un test médical est fiable à 99 % : s'il est positif, vous êtes malade à 99 % ? Non — tout dépend de la RARETÉ de la maladie. Bayes : P(A|B) = P(B|A) × P(A) / P(B), où P(B) = P(B|A)·P(A) + P(B|non A)·P(non A). Il corrige l'intuition et fonde le filtre anti-spam, le diagnostic, et une grande famille de modèles.", en: "A medical test is 99% reliable: if positive, are you 99% likely to be ill? No — it depends on how RARE the illness is. Bayes: P(A|B) = P(B|A) × P(A) / P(B), where P(B) = P(B|A)·P(A) + P(B|not A)·P(not A). It corrects intuition and underlies spam filters, diagnosis, and a large family of models." },
    example: "print(0.9 * 0.1 + 0.2 * 0.9)",
    task: { fr: "Écris bayes(p_a, p_b_si_a, p_b_si_non_a) : renvoie P(A|B).", en: "Write bayes(p_a, p_b_si_a, p_b_si_non_a): return P(A|B)." },
    starter: "def bayes(p_a, p_b_si_a, p_b_si_non_a):\n    pass\n",
    hint: { fr: "Calcule d'abord p_b = p_b_si_a * p_a + p_b_si_non_a * (1 - p_a).", en: "First compute p_b = p_b_si_a * p_a + p_b_si_non_a * (1 - p_a)." },
    solution: "def bayes(p_a, p_b_si_a, p_b_si_non_a):\n    p_b = p_b_si_a * p_a + p_b_si_non_a * (1 - p_a)\n    return p_b_si_a * p_a / p_b",
    checks: ["abs(bayes(0.5, 0.5, 0.5) - 0.5) < 1e-12", "abs(bayes(0.01, 0.99, 0.01) - 0.5) < 1e-12", "abs(bayes(0.1, 0.9, 0.2) - 0.09 / 0.27) < 1e-12", "bayes(0.3, 1.0, 0.0) == 1.0", "bayes(0.001, 0.99, 0.05) < 0.02"],
  },
  {
    id: "maths-esperance", lang: 'py', group: "maths",
    title: { fr: "Espérance et simulation", en: "Expected value and simulation" },
    explain: { fr: "L'ESPÉRANCE d'une variable aléatoire est sa moyenne « à long terme » : Σ valeur × probabilité. Un dé à 6 faces : (1+2+…+6)/6 = 3,5, même si aucun lancer ne donne 3,5. La loi des grands nombres dit que la moyenne de beaucoup de tirages s'en approche — c'est pourquoi on peut estimer par simulation (Monte-Carlo) ce qu'on ne sait pas calculer.", en: "The EXPECTED VALUE of a random variable is its “long-run” mean: Σ value × probability. A 6-sided die: (1+2+…+6)/6 = 3.5, even though no roll gives 3.5. The law of large numbers says the mean of many draws approaches it — which is why we can estimate by simulation (Monte Carlo) what we can't compute." },
    example: "import random\nrandom.seed(0)\nprint(sum(random.randint(1, 6) for _ in range(1000)) / 1000)",
    task: { fr: "Écris esperance(valeurs, probas) et simule(valeurs, probas, n, graine) : moyenne de n tirages (random.choices avec random.seed(graine)).", en: "Write esperance(valeurs, probas) and simule(valeurs, probas, n, graine): mean of n draws (random.choices with random.seed(graine))." },
    starter: "import random\n\ndef esperance(valeurs, probas):\n    pass\n\ndef simule(valeurs, probas, n, graine):\n    pass\n",
    hint: { fr: "esperance = sum(v * p ...) ; simule : random.seed(graine) puis random.choices(valeurs, weights=probas, k=n).", en: "esperance = sum(v * p ...); simule: random.seed(graine) then random.choices(valeurs, weights=probas, k=n)." },
    solution: "import random\n\ndef esperance(valeurs, probas):\n    return sum(v * p for v, p in zip(valeurs, probas))\n\ndef simule(valeurs, probas, n, graine):\n    random.seed(graine)\n    tirages = random.choices(valeurs, weights=probas, k=n)\n    return sum(tirages) / n",
    checks: ["abs(esperance([1, 2, 3, 4, 5, 6], [1/6] * 6) - 3.5) < 1e-9", "esperance([0, 10], [0.9, 0.1]) == 1.0", "abs(simule([1, 2, 3, 4, 5, 6], [1/6] * 6, 20000, 0) - 3.5) < 0.1", "abs(simule([0, 10], [0.9, 0.1], 20000, 1) - 1.0) < 0.2", "simule([7], [1.0], 10, 3) == 7"],
  },
  {
    id: "maths-entropie", lang: 'py', group: "maths",
    title: { fr: "Entropie : mesurer l'incertitude", en: "Entropy: measuring uncertainty" },
    explain: { fr: "L'ENTROPIE mesure l'incertitude d'une distribution : H = −Σ p·log₂(p), en bits. Une pièce équilibrée : 1 bit (on ne peut rien prédire). Une pièce truquée presque toujours « face » : proche de 0. Un dé équilibré : log₂ 6 ≈ 2,58 bits. On convient que 0·log 0 = 0. C'est la base de la compression des données et de la perte d'entropie croisée des classifieurs.", en: "ENTROPY measures a distribution's uncertainty: H = −Σ p·log₂(p), in bits. A fair coin: 1 bit (nothing predictable). A coin almost always “heads”: near 0. A fair die: log₂ 6 ≈ 2.58 bits. By convention 0·log 0 = 0. It underlies data compression and the cross-entropy loss of classifiers." },
    example: "import math\nprint(-sum(p * math.log2(p) for p in [0.5, 0.5]))",
    task: { fr: "Écris entropie(probas) en bits, en ignorant les probabilités nulles.", en: "Write entropie(probas) in bits, ignoring zero probabilities." },
    starter: "import math\n\ndef entropie(probas):\n    pass\n",
    hint: { fr: "-sum(p * math.log2(p) for p in probas if p > 0)", en: "-sum(p * math.log2(p) for p in probas if p > 0)" },
    solution: "import math\n\ndef entropie(probas):\n    return -sum(p * math.log2(p) for p in probas if p > 0)",
    checks: ["abs(entropie([0.5, 0.5]) - 1) < 1e-12", "entropie([1.0]) == 0", "entropie([1.0, 0.0]) == 0", "abs(entropie([0.25] * 4) - 2) < 1e-12", "abs(entropie([1/6] * 6) - 2.584962500721156) < 1e-9", "entropie([0.9, 0.1]) < entropie([0.5, 0.5])"],
  },
  {
    id: "maths-softmax", lang: 'py', group: "maths",
    title: { fr: "Softmax et perte d'entropie croisée", en: "Softmax and cross-entropy loss" },
    explain: { fr: "Un classifieur produit des scores bruts (« logits »). SOFTMAX les transforme en probabilités positives de somme 1 : p_i = e^{z_i} / Σ e^{z_j}. Astuce de stabilité : soustraire le maximum avant l'exponentielle, sinon e^1000 déborde ; le résultat est identique. La PERTE d'entropie croisée mesure l'écart avec la bonne classe : −log(p_bonne). Proche de 0 si le modèle est sûr et juste, énorme s'il est sûr et faux.", en: "A classifier outputs raw scores (“logits”). SOFTMAX turns them into positive probabilities summing to 1: p_i = e^{z_i} / Σ e^{z_j}. Stability trick: subtract the maximum before the exponential, otherwise e^1000 overflows; the result is identical. The cross-entropy LOSS measures the gap with the right class: −log(p_right). Near 0 if the model is sure and right, huge if sure and wrong." },
    example: "import math\nz = [2.0, 1.0]\nprint([math.exp(v) for v in z])",
    task: { fr: "Écris softmax(z) (stable) et perte(z, i) = −log de la probabilité de la classe i.", en: "Write softmax(z) (stable) and perte(z, i) = −log of class i's probability." },
    starter: "import math\n\ndef softmax(z):\n    pass\n\ndef perte(z, i):\n    pass\n",
    hint: { fr: "m = max(z) ; e = [math.exp(v - m) for v in z] ; divise par sum(e). perte = -math.log(softmax(z)[i]).", en: "m = max(z); e = [math.exp(v - m) for v in z]; divide by sum(e). perte = -math.log(softmax(z)[i])." },
    solution: "import math\n\ndef softmax(z):\n    m = max(z)\n    e = [math.exp(v - m) for v in z]\n    s = sum(e)\n    return [v / s for v in e]\n\ndef perte(z, i):\n    return -math.log(softmax(z)[i])",
    checks: ["abs(sum(softmax([1, 2, 3])) - 1) < 1e-12", "softmax([0, 0]) == [0.5, 0.5]", "abs(softmax([1000, 1000])[0] - 0.5) < 1e-12", "softmax([1, 2, 3]) == sorted(softmax([1, 2, 3]))", "abs(perte([0, 0], 0) - 0.6931471805599453) < 1e-9", "perte([10, 0], 0) < 0.001", "perte([10, 0], 1) > 9"],
  },
]
