import type { Lesson } from './lessons'

// Parcours Ordinateurs : portes logiques, additionneur, complément à deux, UAL, mini-processeur (Python pur, hors ligne). Contenu original.
export const archiLessons: Lesson[] = [
  {
    id: "archi-nand", lang: 'py', group: "archi",
    title: { fr: "Portes logiques : tout avec NAND", en: "Logic gates: everything from NAND" },
    explain: { fr: "Un processeur est fait de portes logiques : des circuits qui prennent des bits (0 ou 1) et en renvoient un. NAND (NON-ET) donne 0 seulement si les deux entrées valent 1. Découverte fondamentale : avec NAND SEULE on reconstruit toutes les autres portes. NON(a) = NAND(a, a) ; ET(a, b) = NON(NAND(a, b)) ; OU(a, b) = NAND(NON(a), NON(b)). Les puces réelles s'appuient sur cette idée d'universalité.", en: "A processor is built from logic gates: circuits that take bits (0 or 1) and return one. NAND (NOT-AND) gives 0 only if both inputs are 1. A fundamental discovery: with NAND ALONE you can rebuild every other gate. NOT(a) = NAND(a, a); AND(a, b) = NOT(NAND(a, b)); OR(a, b) = NAND(NOT(a), NOT(b)). Real chips rely on this universality." },
    example: "def nand(a, b):\n    return 0 if (a and b) else 1\nprint([nand(a, b) for a in (0, 1) for b in (0, 1)])",
    task: { fr: "À partir de nand (fournie), écris non_, et_, ou_ en n'utilisant QUE nand.", en: "From nand (provided), write non_, et_, ou_ using ONLY nand." },
    starter: "def nand(a, b):\n    return 0 if (a and b) else 1\n\ndef non_(a):\n    pass\n\ndef et_(a, b):\n    pass\n\ndef ou_(a, b):\n    pass\n",
    hint: { fr: "non_(a) = nand(a, a) ; et_ = non_(nand(a, b)) ; ou_ = nand(non_(a), non_(b)).", en: "non_(a) = nand(a, a); et_ = non_(nand(a, b)); ou_ = nand(non_(a), non_(b))." },
    solution: "def nand(a, b):\n    return 0 if (a and b) else 1\n\ndef non_(a):\n    return nand(a, a)\n\ndef et_(a, b):\n    return non_(nand(a, b))\n\ndef ou_(a, b):\n    return nand(non_(a), non_(b))",
    checks: ["[non_(0), non_(1)] == [1, 0]", "[et_(a, b) for a in (0, 1) for b in (0, 1)] == [0, 0, 0, 1]", "[ou_(a, b) for a in (0, 1) for b in (0, 1)] == [0, 1, 1, 1]"],
  },
  {
    id: "archi-xor", lang: 'py', group: "archi",
    title: { fr: "Le OU exclusif (XOR)", en: "The exclusive OR (XOR)" },
    explain: { fr: "XOR vaut 1 quand les deux bits sont DIFFÉRENTS. C'est la porte de l'addition : 0+0=0, 0+1=1, 1+0=1, et 1+1=0 (avec retenue 1). On le construit avec ET, OU et NON : a XOR b = (a OU b) ET NON(a ET b) — « l'un ou l'autre, mais pas les deux ». Les portes se composent : c'est ainsi qu'on bâtit des circuits complexes à partir de briques simples.", en: "XOR is 1 when the two bits DIFFER. It is the addition gate: 0+0=0, 0+1=1, 1+0=1, and 1+1=0 (carry 1). Build it from AND, OR and NOT: a XOR b = (a OR b) AND NOT(a AND b) — “one or the other, but not both”. Gates compose: that is how complex circuits are built from simple bricks." },
    example: "print([a ^ b for a in (0, 1) for b in (0, 1)])",
    task: { fr: "Écris xor_(a, b) avec les portes et_, ou_, non_ fournies (sans l'opérateur ^).", en: "Write xor_(a, b) with the provided gates et_, ou_, non_ (without the ^ operator)." },
    starter: "def non_(a): return 1 - a\ndef et_(a, b): return a & b\ndef ou_(a, b): return a | b\n\ndef xor_(a, b):\n    pass\n",
    hint: { fr: "et_(ou_(a, b), non_(et_(a, b)))", en: "et_(ou_(a, b), non_(et_(a, b)))" },
    solution: "def non_(a): return 1 - a\ndef et_(a, b): return a & b\ndef ou_(a, b): return a | b\n\ndef xor_(a, b):\n    return et_(ou_(a, b), non_(et_(a, b)))",
    checks: ["[xor_(a, b) for a in (0, 1) for b in (0, 1)] == [0, 1, 1, 0]", "xor_(1, 1) == 0", "xor_(0, 0) == 0"],
  },
  {
    id: "archi-additionneur", lang: 'py', group: "archi",
    title: { fr: "Additionneur complet", en: "Full adder" },
    explain: { fr: "Additionner deux bits donne une SOMME et une RETENUE : le demi-additionneur (somme = a XOR b, retenue = a ET b). Mais dès la deuxième colonne il faut aussi ajouter la retenue entrante : c'est l'ADDITIONNEUR COMPLET, à trois entrées (a, b, retenue_in) et deux sorties (somme, retenue_out). Somme = a XOR b XOR r ; retenue_out = 1 si au moins deux des trois entrées valent 1.", en: "Adding two bits gives a SUM and a CARRY: the half adder (sum = a XOR b, carry = a AND b). But from the second column you also must add the incoming carry: the FULL ADDER, with three inputs (a, b, carry_in) and two outputs (sum, carry_out). Sum = a XOR b XOR c; carry_out = 1 if at least two of the three inputs are 1." },
    example: "a, b, r = 1, 1, 1\nprint(a + b + r)",
    task: { fr: "Écris additionneur(a, b, r) → (somme, retenue) en utilisant les opérateurs de bits ^, & et |.", en: "Write additionneur(a, b, r) → (sum, carry) using the bit operators ^, & and |." },
    starter: "def additionneur(a, b, r):\n    pass\n",
    hint: { fr: "somme = a ^ b ^ r ; retenue = (a & b) | (r & (a ^ b)).", en: "sum = a ^ b ^ r; carry = (a & b) | (r & (a ^ b))." },
    solution: "def additionneur(a, b, r):\n    somme = a ^ b ^ r\n    retenue = (a & b) | (r & (a ^ b))\n    return somme, retenue",
    checks: ["additionneur(0, 0, 0) == (0, 0)", "additionneur(1, 0, 0) == (1, 0)", "additionneur(1, 1, 0) == (0, 1)", "additionneur(1, 1, 1) == (1, 1)", "additionneur(0, 1, 1) == (0, 1)", "all(a + b + r == additionneur(a, b, r)[0] + 2 * additionneur(a, b, r)[1] for a in (0, 1) for b in (0, 1) for r in (0, 1))"],
  },
  {
    id: "archi-binaire", lang: 'py', group: "archi",
    title: { fr: "Additionner des nombres de n bits", en: "Adding n-bit numbers" },
    explain: { fr: "En chaînant des additionneurs complets, la retenue de l'un entrant dans le suivant, on additionne des nombres entiers : c'est l'ADDITIONNEUR À PROPAGATION DE RETENUE. Un nombre est une liste de bits, du poids FAIBLE au poids fort (le bit 0 d'abord) : 6 = [0, 1, 1]. Si la retenue finale vaut 1 sur n bits, le résultat déborde : c'est le dépassement (overflow) d'entier, source de vrais bugs.", en: "By chaining full adders, each carry feeding the next, you add whole numbers: the RIPPLE-CARRY ADDER. A number is a list of bits, from LEAST significant to most (bit 0 first): 6 = [0, 1, 1]. If the final carry is 1 on n bits, the result overflows: integer overflow, a source of real bugs." },
    example: "print(bin(6), int('110', 2))",
    task: { fr: "Écris additionne(a, b) : listes de bits de même longueur (poids faible d'abord) ; renvoie (bits_somme, retenue_finale).", en: "Write additionne(a, b): equal-length lists of bits (least significant first); return (sum_bits, final_carry)." },
    starter: "def additionne(a, b):\n    pass\n",
    hint: { fr: "Parcours les paires avec une retenue r qui démarre à 0 ; à chaque bit : s = x ^ y ^ r ; r = (x & y) | (r & (x ^ y)).", en: "Walk the pairs with a carry r starting at 0; at each bit: s = x ^ y ^ r; r = (x & y) | (r & (x ^ y))." },
    solution: "def additionne(a, b):\n    r = 0\n    somme = []\n    for x, y in zip(a, b):\n        somme.append(x ^ y ^ r)\n        r = (x & y) | (r & (x ^ y))\n    return somme, r",
    checks: ["additionne([1, 1, 0], [1, 0, 1]) == ([0, 0, 0], 1)", "additionne([1, 0, 1], [1, 1, 0]) == ([0, 0, 0], 1)", "additionne([0, 1], [1, 0]) == ([1, 1], 0)", "additionne([0, 0, 0], [0, 0, 0]) == ([0, 0, 0], 0)", "additionne([1, 1, 1, 1], [1, 0, 0, 0]) == ([0, 0, 0, 0], 1)", "additionne([1, 1, 0, 1], [1, 0, 1, 0]) == ([0, 0, 0, 0], 1)"],
  },
  {
    id: "archi-deux", lang: 'py', group: "archi",
    title: { fr: "Complément à deux : les négatifs", en: "Two's complement: negatives" },
    explain: { fr: "Comment un ordinateur représente-t-il −5 avec seulement des bits ? Par le COMPLÉMENT À DEUX sur n bits : on garde la valeur modulo 2ⁿ. Sur 8 bits, −5 est 256 − 5 = 251 = 11111011. Astuce : inverser tous les bits puis ajouter 1. Le bit de poids fort sert de signe (1 = négatif). Avantage décisif : l'additionneur est le MÊME pour les positifs et les négatifs. Plage sur n bits : de −2ⁿ⁻¹ à 2ⁿ⁻¹ − 1.", en: "How does a computer represent −5 using only bits? With TWO'S COMPLEMENT on n bits: keep the value modulo 2ⁿ. On 8 bits, −5 is 256 − 5 = 251 = 11111011. Trick: invert all bits then add 1. The top bit acts as sign (1 = negative). A decisive advantage: the adder is the SAME for positives and negatives. Range on n bits: −2ⁿ⁻¹ to 2ⁿ⁻¹ − 1." },
    example: "print(-5 % 256, format(-5 % 256, '08b'))",
    task: { fr: "Écris vers_bits(x, n) (chaîne de n caractères '0'/'1') et depuis_bits(s) (entier signé, d'après le bit de poids fort).", en: "Write vers_bits(x, n) (string of n '0'/'1' characters) and depuis_bits(s) (signed integer, from the top bit)." },
    starter: "def vers_bits(x, n):\n    pass\n\ndef depuis_bits(s):\n    pass\n",
    hint: { fr: "vers_bits : format(x % 2**n, f'0{n}b'). depuis_bits : v = int(s, 2) ; si s[0] == '1', retire 2**len(s).", en: "vers_bits: format(x % 2**n, f'0{n}b'). depuis_bits: v = int(s, 2); if s[0] == '1', subtract 2**len(s)." },
    solution: "def vers_bits(x, n):\n    return format(x % 2 ** n, f'0{n}b')\n\ndef depuis_bits(s):\n    v = int(s, 2)\n    if s[0] == '1':\n        v -= 2 ** len(s)\n    return v",
    checks: ["vers_bits(5, 8) == '00000101'", "vers_bits(-5, 8) == '11111011'", "vers_bits(-1, 4) == '1111'", "depuis_bits('11111011') == -5", "depuis_bits('0111') == 7", "depuis_bits('1000') == -8", "all(depuis_bits(vers_bits(x, 8)) == x for x in range(-128, 128))"],
  },
  {
    id: "archi-alu", lang: 'py', group: "archi",
    title: { fr: "Une mini-UAL", en: "A mini ALU" },
    explain: { fr: "L'UNITÉ ARITHMÉTIQUE ET LOGIQUE (UAL, « ALU ») est le calculateur du processeur : elle reçoit deux nombres et un CODE D'OPÉRATION, et renvoie le résultat plus des DRAPEAUX (flags) : Z = le résultat vaut zéro ; N = il est négatif. Les instructions de comparaison et de saut (« si égal, sauter ») s'appuient sur ces drapeaux. Ici sur 8 bits signés : toute valeur est ramenée dans l'intervalle −128 à 127 (débordement).", en: "The ARITHMETIC AND LOGIC UNIT (ALU) is the processor's calculator: it receives two numbers and an OPERATION CODE, and returns the result plus FLAGS: Z = the result is zero; N = it is negative. Compare and jump instructions (“if equal, jump”) rely on these flags. Here on signed 8 bits: every value is wrapped into −128 to 127 (overflow)." },
    example: "x = 100 + 100\nprint((x + 128) % 256 - 128)",
    task: { fr: "Écris ual(op, a, b) → (resultat, Z, N). Opérations : 'ADD', 'SUB', 'ET', 'OU', 'XOR'. Le résultat est ramené sur 8 bits signés : (r + 128) % 256 - 128. Z = 1 si résultat 0, N = 1 si < 0 (sinon 0).", en: "Write ual(op, a, b) → (result, Z, N). Operations: 'ADD', 'SUB', 'ET', 'OU', 'XOR'. The result is wrapped to signed 8 bits: (r + 128) % 256 - 128. Z = 1 if result is 0, N = 1 if < 0 (else 0)." },
    starter: "def ual(op, a, b):\n    pass\n",
    hint: { fr: "Calcule r selon op (a + b, a - b, a & b, a | b, a ^ b), ramène-le, puis déduis Z et N.", en: "Compute r from op (a + b, a - b, a & b, a | b, a ^ b), wrap it, then derive Z and N." },
    solution: "def ual(op, a, b):\n    r = {'ADD': a + b, 'SUB': a - b, 'ET': a & b, 'OU': a | b, 'XOR': a ^ b}[op]\n    r = (r + 128) % 256 - 128\n    return r, int(r == 0), int(r < 0)",
    checks: ["ual('ADD', 3, 4) == (7, 0, 0)", "ual('SUB', 5, 5) == (0, 1, 0)", "ual('SUB', 3, 5) == (-2, 0, 1)", "ual('ADD', 100, 100) == (-56, 0, 1)", "ual('ET', 12, 10) == (8, 0, 0)", "ual('OU', 12, 10) == (14, 0, 0)", "ual('XOR', 6, 6) == (0, 1, 0)"],
  },
  {
    id: "archi-cpu", lang: 'py', group: "archi",
    title: { fr: "Un processeur minuscule", en: "A tiny processor" },
    explain: { fr: "Un processeur répète sans cesse : LIRE l'instruction à l'adresse du compteur de programme (PC), l'EXÉCUTER, avancer le PC. Les données vivent dans des REGISTRES (petites cases ultra-rapides). Voici une machine à 4 instructions : ('SET', r, v) met v dans le registre r ; ('ADD', r1, r2) fait r1 = r1 + r2 ; ('JNZ', r, cible) saute à l'instruction « cible » si le registre r n'est pas nul ; ('SUBI', r, v) retire v au registre r. Avec ça, on programme une boucle — donc, en principe, n'importe quel calcul.", en: "A processor endlessly repeats: FETCH the instruction at the program counter (PC) address, EXECUTE it, advance the PC. Data lives in REGISTERS (tiny ultra-fast cells). Here is a 4-instruction machine: ('SET', r, v) puts v in register r; ('ADD', r1, r2) does r1 = r1 + r2; ('JNZ', r, target) jumps to instruction “target” if register r is not zero; ('SUBI', r, v) subtracts v from register r. With that you program a loop — so, in principle, any computation." },
    example: "programme = [('SET', 'a', 2)]\nprint(programme[0][0])",
    task: { fr: "Écris execute(programme) : registres dans un dict (0 par défaut), PC qui démarre à 0 et s'arrête quand il dépasse la fin ; renvoie le dict des registres. Protège-toi contre les boucles infinies : au plus 10 000 instructions exécutées.", en: "Write execute(programme): registers in a dict (default 0), PC starting at 0 and stopping when it passes the end; return the registers dict. Guard against infinite loops: at most 10,000 instructions executed." },
    starter: "def execute(programme):\n    pass\n",
    hint: { fr: "while pc < len(programme) and n < 10000 : lis (op, x, y) ; selon op modifie reg ou pc ; sinon pc += 1.", en: "while pc < len(programme) and n < 10000: read (op, x, y); per op change reg or pc; otherwise pc += 1." },
    solution: "def execute(programme):\n    reg = {}\n    pc = 0\n    n = 0\n    while pc < len(programme) and n < 10000:\n        op, x, y = programme[pc]\n        n += 1\n        if op == 'SET':\n            reg[x] = y\n        elif op == 'ADD':\n            reg[x] = reg.get(x, 0) + reg.get(y, 0)\n        elif op == 'SUBI':\n            reg[x] = reg.get(x, 0) - y\n        elif op == 'JNZ':\n            if reg.get(x, 0) != 0:\n                pc = y\n                continue\n        pc += 1\n    return reg",
    checks: ["execute([('SET', 'a', 2), ('SET', 'b', 3), ('ADD', 'a', 'b')]) == {'a': 5, 'b': 3}", "execute([]) == {}", "execute([('SET', 'n', 4), ('SET', 's', 0), ('ADD', 's', 'n'), ('SUBI', 'n', 1), ('JNZ', 'n', 2)]) == {'n': 0, 's': 10}", "execute([('SET', 'x', 1), ('JNZ', 'x', 0)]) == {'x': 1}", "execute([('SET', 'a', 7), ('SUBI', 'a', 7), ('JNZ', 'a', 0)]) == {'a': 0}"],
  },
]
