import type { Lesson } from './lessons'

// Parcours C : lire et prédire (réponses vérifiées avec gcc à la génération). Contenu original.
export const cLessons: Lesson[] = [
  {
    id: "c-printf", lang: 'py', langue: "c", group: "c",
    title: { fr: "C : afficher et calculer", en: "C: printing and computing" },
    explain: { fr: "Le C est le langage des systèmes : Linux, les microcontrôleurs, les moteurs de jeux. Chaque programme commence par main(). printf affiche du texte ; %d y insère un entier, %f un nombre à virgule, \\n passe à la ligne. Attention : entre deux entiers, / fait une division ENTIÈRE (7 / 2 vaut 3). (Dans le navigateur on ne compile pas encore le C : ici tu apprends à le LIRE. La réponse a été vérifiée avec un vrai compilateur.)", en: "C is the systems language: Linux, microcontrollers, game engines. Every program starts with main(). printf prints text; %d inserts an integer, %f a decimal number, \\n starts a new line. Careful: between two integers, / is INTEGER division (7 / 2 is 3). (The browser does not compile C yet: here you learn to READ it. The answer was checked with a real compiler.)" },
    example: '',
    task: { fr: 'Que va afficher ce programme ?', en: 'What will this program print?' },
    starter: '',
    hint: { fr: "Une ligne par printf. Pense à la division entière.", en: "One line per printf. Remember integer division." },
    solution: "3\n1\n3.5",
    checks: [],
    predict: { code: "#include <stdio.h>\n\nint main(void) {\n    int a = 7, b = 2;\n    printf(\"%d\\n\", a / b);\n    printf(\"%d\\n\", a % b);\n    printf(\"%.1f\\n\", a / 2.0);\n    return 0;\n}", answer: "3\n1\n3.5", why: { fr: "7 / 2 entre entiers donne 3 ; le reste 7 % 2 vaut 1 ; avec 2.0 (un nombre à virgule) la division est réelle : 3.5, affiché avec une décimale grâce à %.1f.", en: "7 / 2 between integers gives 3; the remainder 7 % 2 is 1; with 2.0 (a decimal) the division is real: 3.5, shown with one decimal thanks to %.1f." } },
  },
  {
    id: "c-boucles", lang: 'py', langue: "c", group: "c",
    title: { fr: "C : boucles for et while", en: "C: for and while loops" },
    explain: { fr: "La boucle for du C regroupe trois parties : départ ; condition ; pas. for (int i = 0; i < 3; i++) répète avec i = 0, 1, 2. while répète tant que la condition est vraie. printf sans \\n reste sur la même ligne. (Dans le navigateur on ne compile pas encore le C : ici tu apprends à le LIRE. La réponse a été vérifiée avec un vrai compilateur.)", en: "C's for loop gathers three parts: start; condition; step. for (int i = 0; i < 3; i++) repeats with i = 0, 1, 2. while repeats as long as the condition holds. printf without \\n stays on the same line. (The browser does not compile C yet: here you learn to READ it. The answer was checked with a real compiler.)" },
    example: '',
    task: { fr: 'Que va afficher ce programme ?', en: 'What will this program print?' },
    starter: '',
    hint: { fr: "Attention à l'espace après le dernier carré : il fait partie de la ligne.", en: "Mind the space after the last square: it is part of the line." },
    solution: "1 4 9 16 \n6\n2\n0",
    checks: [],
    predict: { code: "#include <stdio.h>\n\nint main(void) {\n    for (int i = 1; i <= 4; i++) {\n        printf(\"%d \", i * i);\n    }\n    printf(\"\\n\");\n    int n = 20;\n    while (n > 1) {\n        n = n / 3;\n        printf(\"%d\\n\", n);\n    }\n    return 0;\n}", answer: "1 4 9 16 \n6\n2\n0", why: { fr: "Les carrés de 1 à 4 sur une ligne (avec un espace final), puis 20/3 = 6, 6/3 = 2, 2/3 = 0 : la boucle s'arrête quand n n'est plus > 1.", en: "The squares of 1 to 4 on one line (with a trailing space), then 20/3 = 6, 6/3 = 2, 2/3 = 0: the loop stops when n is no longer > 1." } },
  },
  {
    id: "c-tableaux", lang: 'py', langue: "c", group: "c",
    title: { fr: "C : tableaux", en: "C: arrays" },
    explain: { fr: "Un tableau C a une taille FIXE, choisie à la déclaration : int t[5]. Les cases vont de t[0] à t[4]. Le C ne vérifie pas les bornes : lire t[5] est une erreur grave (comportement indéfini) que le compilateur ne signale pas toujours. sizeof(t) / sizeof(t[0]) donne le nombre de cases. (Dans le navigateur on ne compile pas encore le C : ici tu apprends à le LIRE. La réponse a été vérifiée avec un vrai compilateur.)", en: "A C array has a FIXED size, chosen at declaration: int t[5]. Cells go from t[0] to t[4]. C does not check bounds: reading t[5] is a serious error (undefined behaviour) the compiler doesn't always report. sizeof(t) / sizeof(t[0]) gives the number of cells. (The browser does not compile C yet: here you learn to READ it. The answer was checked with a real compiler.)" },
    example: '',
    task: { fr: 'Que va afficher ce programme ?', en: 'What will this program print?' },
    starter: '',
    hint: { fr: "Compte les cases, additionne-les.", en: "Count the cells, add them up." },
    solution: "5 66\n19",
    checks: [],
    predict: { code: "#include <stdio.h>\n\nint main(void) {\n    int t[] = {4, 8, 15, 16, 23};\n    int n = sizeof(t) / sizeof(t[0]);\n    int somme = 0;\n    for (int i = 0; i < n; i++) {\n        somme += t[i];\n    }\n    printf(\"%d %d\\n\", n, somme);\n    printf(\"%d\\n\", t[n - 1] - t[0]);\n    return 0;\n}", answer: "5 66\n19", why: { fr: "5 cases ; 4+8+15+16+23 = 66 ; la dernière case moins la première : 23 − 4 = 19.", en: "5 cells; 4+8+15+16+23 = 66; last cell minus first: 23 − 4 = 19." } },
  },
  {
    id: "c-chaines", lang: 'py', langue: "c", group: "c",
    title: { fr: "C : chaînes de caractères", en: "C: strings" },
    explain: { fr: "En C, un texte est un tableau de char terminé par le caractère nul '\\0'. \"Finjaro\" occupe donc 8 octets : 7 lettres + le zéro final. strlen compte les lettres sans le zéro. Chaque char est aussi un petit nombre : 'A' vaut 65, et 'A' + 2 donne 'C'. (Dans le navigateur on ne compile pas encore le C : ici tu apprends à le LIRE. La réponse a été vérifiée avec un vrai compilateur.)", en: "In C, text is a char array ended by the null character '\\0'. \"Finjaro\" therefore takes 8 bytes: 7 letters + the final zero. strlen counts the letters without the zero. Each char is also a small number: 'A' is 65, and 'A' + 2 gives 'C'. (The browser does not compile C yet: here you learn to READ it. The answer was checked with a real compiler.)" },
    example: '',
    task: { fr: 'Que va afficher ce programme ?', en: 'What will this program print?' },
    starter: '',
    hint: { fr: "Le tableau compte aussi le caractère nul final.", en: "The array also counts the final null character." },
    solution: "7 8\nFo\nC 65",
    checks: [],
    predict: { code: "#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    char mot[] = \"Finjaro\";\n    printf(\"%zu %zu\\n\", strlen(mot), sizeof(mot));\n    printf(\"%c%c\\n\", mot[0], mot[strlen(mot) - 1]);\n    printf(\"%c %d\\n\", 'A' + 2, 'A');\n    return 0;\n}", answer: "7 8\nFo\nC 65", why: { fr: "strlen = 7 lettres, sizeof = 8 octets (avec \\0). Première lettre F, dernière o. 'A' + 2 = 'C' ; 'A' en nombre vaut 65.", en: "strlen = 7 letters, sizeof = 8 bytes (with \\0). First letter F, last o. 'A' + 2 = 'C'; 'A' as a number is 65." } },
  },
  {
    id: "c-pointeurs", lang: 'py', langue: "c", group: "c",
    title: { fr: "C : les pointeurs", en: "C: pointers" },
    explain: { fr: "Un POINTEUR contient l'ADRESSE d'une variable en mémoire. &x donne l'adresse de x ; si p = &x, alors *p désigne x lui-même : modifier *p modifie x. C'est la notion clé du C — et la source de beaucoup de bugs. Les tableaux se manipulent aussi par pointeurs : *(t + 2) est t[2]. (Dans le navigateur on ne compile pas encore le C : ici tu apprends à le LIRE. La réponse a été vérifiée avec un vrai compilateur.)", en: "A POINTER holds the ADDRESS of a variable in memory. &x gives x's address; if p = &x, then *p means x itself: changing *p changes x. This is C's key notion — and the source of many bugs. Arrays are also handled through pointers: *(t + 2) is t[2]. (The browser does not compile C yet: here you learn to READ it. The answer was checked with a real compiler.)" },
    example: '',
    task: { fr: 'Que va afficher ce programme ?', en: 'What will this program print?' },
    starter: '',
    hint: { fr: "*p, c'est la variable pointée. q++ avance d'une case.", en: "*p is the pointed variable. q++ moves one cell forward." },
    solution: "15\n2 4",
    checks: [],
    predict: { code: "#include <stdio.h>\n\nint main(void) {\n    int x = 10;\n    int *p = &x;\n    *p = *p + 5;\n    printf(\"%d\\n\", x);\n    int t[] = {1, 2, 3, 4};\n    int *q = t;\n    q++;\n    printf(\"%d %d\\n\", *q, *(q + 2));\n    return 0;\n}", answer: "15\n2 4", why: { fr: "*p = *p + 5 modifie x à travers son adresse : 15. q pointe d'abord sur t[0], q++ le fait avancer à t[1] = 2 ; q + 2 désigne t[3] = 4.", en: "*p = *p + 5 changes x through its address: 15. q first points at t[0], q++ moves it to t[1] = 2; q + 2 means t[3] = 4." } },
  },
  {
    id: "c-fonctions", lang: 'py', langue: "c", group: "c",
    title: { fr: "C : passage par valeur ou par adresse", en: "C: passing by value or by address" },
    explain: { fr: "En C, une fonction reçoit une COPIE de ses arguments : la modifier ne change pas l'original. Pour qu'une fonction modifie une variable de l'appelant, on lui passe son ADRESSE (un pointeur). C'est ainsi qu'on écrit une fonction « échange ». (Dans le navigateur on ne compile pas encore le C : ici tu apprends à le LIRE. La réponse a été vérifiée avec un vrai compilateur.)", en: "In C, a function receives a COPY of its arguments: changing it does not change the original. For a function to change a caller's variable, you pass its ADDRESS (a pointer). That's how you write a “swap” function. (The browser does not compile C yet: here you learn to READ it. The answer was checked with a real compiler.)" },
    example: '',
    task: { fr: 'Que va afficher ce programme ?', en: 'What will this program print?' },
    starter: '',
    hint: { fr: "Seules les fonctions qui reçoivent une adresse (&) peuvent modifier x.", en: "Only functions receiving an address (&) can change x." },
    solution: "3\n6\n8 6",
    checks: [],
    predict: { code: "#include <stdio.h>\n\nvoid double_copie(int n) { n = n * 2; }\nvoid double_vrai(int *n) { *n = *n * 2; }\nvoid echange(int *a, int *b) { int t = *a; *a = *b; *b = t; }\n\nint main(void) {\n    int x = 3, y = 8;\n    double_copie(x);\n    printf(\"%d\\n\", x);\n    double_vrai(&x);\n    printf(\"%d\\n\", x);\n    echange(&x, &y);\n    printf(\"%d %d\\n\", x, y);\n    return 0;\n}", answer: "3\n6\n8 6", why: { fr: "double_copie travaille sur une copie : x reste 3. double_vrai reçoit l'adresse : x devient 6. echange inverse x et y : 8 6.", en: "double_copie works on a copy: x stays 3. double_vrai gets the address: x becomes 6. echange swaps x and y: 8 6." } },
  },
  {
    id: "c-struct", lang: 'py', langue: "c", group: "c",
    title: { fr: "C : structures", en: "C: structs" },
    explain: { fr: "Une struct regroupe plusieurs valeurs sous un même nom, comme une petite fiche : struct Point { int x; int y; }. On accède aux champs avec un point (p.x) ; à travers un pointeur, avec une flèche (pp->x, qui veut dire (*pp).x). Copier une struct copie tous ses champs. (Dans le navigateur on ne compile pas encore le C : ici tu apprends à le LIRE. La réponse a été vérifiée avec un vrai compilateur.)", en: "A struct groups several values under one name, like a small record: struct Point { int x; int y; }. Access fields with a dot (p.x); through a pointer, with an arrow (pp->x, meaning (*pp).x). Copying a struct copies all its fields. (The browser does not compile C yet: here you learn to READ it. The answer was checked with a real compiler.)" },
    example: '',
    task: { fr: 'Que va afficher ce programme ?', en: 'What will this program print?' },
    starter: '',
    hint: { fr: "b = a fait une copie indépendante.", en: "b = a makes an independent copy." },
    solution: "11 2\n1 9",
    checks: [],
    predict: { code: "#include <stdio.h>\n\nstruct Point { int x; int y; };\n\nvoid deplace(struct Point *pp, int dx) { pp->x += dx; }\n\nint main(void) {\n    struct Point a = {1, 2};\n    struct Point b = a;\n    b.y = 9;\n    deplace(&a, 10);\n    printf(\"%d %d\\n\", a.x, a.y);\n    printf(\"%d %d\\n\", b.x, b.y);\n    return 0;\n}", answer: "11 2\n1 9", why: { fr: "b est une COPIE de a : changer b.y ne touche pas a. deplace reçoit l'adresse de a et ajoute 10 à a.x : a = (11, 2), b = (1, 9).", en: "b is a COPY of a: changing b.y doesn't affect a. deplace gets a's address and adds 10 to a.x: a = (11, 2), b = (1, 9)." } },
  },
  {
    id: "c-debordement", lang: 'py', langue: "c", group: "c",
    title: { fr: "C : la mémoire et ses limites", en: "C: memory and its limits" },
    explain: { fr: "Un unsigned char tient sur 8 bits : de 0 à 255. Au-delà, il « fait le tour » : 255 + 1 donne 0 (débordement). La mémoire dynamique se réserve avec malloc et DOIT être rendue avec free : l'oublier crée une fuite de mémoire ; s'en servir après free est une faille de sécurité classique. (Dans le navigateur on ne compile pas encore le C : ici tu apprends à le LIRE. La réponse a été vérifiée avec un vrai compilateur.)", en: "An unsigned char fits in 8 bits: 0 to 255. Beyond that it “wraps around”: 255 + 1 gives 0 (overflow). Dynamic memory is reserved with malloc and MUST be given back with free: forgetting creates a memory leak; using it after free is a classic security flaw. (The browser does not compile C yet: here you learn to READ it. The answer was checked with a real compiler.)" },
    example: '',
    task: { fr: 'Que va afficher ce programme ?', en: 'What will this program print?' },
    starter: '',
    hint: { fr: "Un unsigned char repart à 0 après 255.", en: "An unsigned char wraps back to 0 after 255." },
    solution: "4\n400",
    checks: [],
    predict: { code: "#include <stdio.h>\n#include <stdlib.h>\n\nint main(void) {\n    unsigned char c = 250;\n    c = c + 10;\n    printf(\"%d\\n\", c);\n    int *t = malloc(3 * sizeof(int));\n    if (t == NULL) return 1;\n    for (int i = 0; i < 3; i++) t[i] = (i + 1) * 100;\n    printf(\"%d\\n\", t[0] + t[2]);\n    free(t);\n    return 0;\n}", answer: "4\n400", why: { fr: "250 + 10 = 260, qui ne tient pas sur 8 bits : 260 − 256 = 4. Le tableau réservé contient 100, 200, 300 : 100 + 300 = 400.", en: "250 + 10 = 260, which doesn't fit in 8 bits: 260 − 256 = 4. The reserved array holds 100, 200, 300: 100 + 300 = 400." } },
  },
]
