import type { Lesson } from './lessons'

// Parcours Informatique quantique : qubit, portes, mesures, deux qubits, intrication, Grover (simulés avec NumPy). Contenu original.
export const quantLessons: Lesson[] = [
  {
    id: "quant-qubit", lang: 'py', group: "quant",
    packages: ["numpy"],
    title: { fr: "Un qubit et sa mesure", en: "A qubit and its measurement" },
    explain: { fr: "Un bit vaut 0 OU 1. Un QUBIT est décrit par deux nombres (amplitudes) α et β : l'état α|0⟩ + β|1⟩, qu'on range dans un vecteur [α, β]. Tant qu'on ne le regarde pas, il est dans les deux à la fois (superposition). Quand on le MESURE, on obtient 0 avec la probabilité |α|² et 1 avec |β|² — et la somme fait toujours 1. Ici, on simule avec NumPy : aucun ordinateur quantique nécessaire pour comprendre.", en: "A bit is 0 OR 1. A QUBIT is described by two numbers (amplitudes) α and β: the state α|0⟩ + β|1⟩, stored in a vector [α, β]. Until you look, it is in both at once (superposition). When you MEASURE it, you get 0 with probability |α|² and 1 with |β|² — and they always sum to 1. Here we simulate with NumPy: no quantum computer needed to understand." },
    example: "import numpy as np\netat = np.array([0.6, 0.8])\nprint(np.abs(etat) ** 2)",
    task: { fr: "Écris probas(etat) → tableau des probabilités de mesure, et est_valide(etat) → True si la somme des probabilités vaut 1 (à 1e-9 près).", en: "Write probas(etat) → array of measurement probabilities, and est_valide(etat) → True if probabilities sum to 1 (within 1e-9)." },
    starter: "import numpy as np\n\ndef probas(etat):\n    pass\n\ndef est_valide(etat):\n    pass\n",
    hint: { fr: "np.abs(etat) ** 2 ; abs(probas(etat).sum() - 1) < 1e-9.", en: "np.abs(etat) ** 2; abs(probas(etat).sum() - 1) < 1e-9." },
    solution: "import numpy as np\n\ndef probas(etat):\n    return np.abs(np.asarray(etat)) ** 2\n\ndef est_valide(etat):\n    return bool(abs(probas(etat).sum() - 1) < 1e-9)",
    checks: ["np.allclose(probas(np.array([0.6, 0.8])), [0.36, 0.64])", "np.allclose(probas(np.array([1, 0])), [1, 0])", "est_valide(np.array([0.6, 0.8])) == True", "est_valide(np.array([1, 1])) == False", "np.allclose(probas(np.array([1j, 0])), [1, 0])"],
  },
  {
    id: "quant-portes", lang: 'py', group: "quant",
    packages: ["numpy"],
    title: { fr: "Portes quantiques : X et Hadamard", en: "Quantum gates: X and Hadamard" },
    explain: { fr: "On agit sur un qubit avec des PORTES, qui sont des matrices 2×2 : nouvel état = porte @ état. La porte X échange |0⟩ et |1⟩ (c'est le NON quantique). La porte de HADAMARD H = (1/√2)·[[1, 1], [1, −1]] crée la superposition : depuis |0⟩, on obtient 50 % / 50 %. Appliquée deux fois, H ramène à l'état de départ : les amplitudes négatives s'annulent — c'est l'INTERFÉRENCE, la vraie source de la puissance quantique.", en: "We act on a qubit with GATES, which are 2×2 matrices: new state = gate @ state. The X gate swaps |0⟩ and |1⟩ (the quantum NOT). The HADAMARD gate H = (1/√2)·[[1, 1], [1, −1]] creates superposition: from |0⟩ you get 50% / 50%. Applied twice, H returns to the start: negative amplitudes cancel — that is INTERFERENCE, the real source of quantum power." },
    example: "import numpy as np\nX = np.array([[0, 1], [1, 0]])\nprint(X @ np.array([1, 0]))",
    task: { fr: "Définis X et H (tableaux NumPy) et applique(portes, etat) qui applique les portes dans l'ordre de la liste.", en: "Define X and H (NumPy arrays) and applique(portes, etat) which applies the gates in list order." },
    starter: "import numpy as np\n\nX = None\nH = None\n\ndef applique(portes, etat):\n    pass\n",
    hint: { fr: "H = np.array([[1, 1], [1, -1]]) / np.sqrt(2). Boucle : etat = p @ etat.", en: "H = np.array([[1, 1], [1, -1]]) / np.sqrt(2). Loop: etat = p @ etat." },
    solution: "import numpy as np\n\nX = np.array([[0, 1], [1, 0]])\nH = np.array([[1, 1], [1, -1]]) / np.sqrt(2)\n\ndef applique(portes, etat):\n    for p in portes:\n        etat = p @ etat\n    return etat",
    checks: ["np.allclose(applique([X], np.array([1, 0])), [0, 1])", "np.allclose(np.abs(applique([H], np.array([1, 0]))) ** 2, [0.5, 0.5])", "np.allclose(applique([H, H], np.array([1, 0])), [1, 0])", "np.allclose(applique([H, X, H], np.array([1, 0])), [1, 0])", "np.allclose(applique([], np.array([0, 1])), [0, 1])"],
  },
  {
    id: "quant-mesure", lang: 'py', group: "quant",
    packages: ["numpy"],
    title: { fr: "Simuler des mesures", en: "Simulating measurements" },
    explain: { fr: "Une seule mesure ne dit presque rien : on obtient 0 ou 1. Pour connaître un état, on PRÉPARE et MESURE de nombreuses fois, puis on compte. C'est exactement ce que font les vrais ordinateurs quantiques (des milliers de « shots »). Avec une graine aléatoire fixe, la simulation est reproductible.", en: "A single measurement says almost nothing: you get 0 or 1. To know a state, you PREPARE and MEASURE many times, then count. That is exactly what real quantum computers do (thousands of “shots”). With a fixed random seed, the simulation is reproducible." },
    example: "import numpy as np\nrng = np.random.default_rng(0)\nprint(rng.choice(2, size=5, p=[0.5, 0.5]))",
    task: { fr: "Écris mesure(etat, n, graine) : renvoie la liste des comptes [nb de 0, nb de 1] sur n mesures, avec rng = np.random.default_rng(graine) et rng.choice.", en: "Write mesure(etat, n, graine): return the counts [number of 0s, number of 1s] over n measurements, with rng = np.random.default_rng(graine) and rng.choice." },
    starter: "import numpy as np\n\ndef mesure(etat, n, graine):\n    pass\n",
    hint: { fr: "p = np.abs(etat) ** 2 ; r = rng.choice(len(etat), size=n, p=p) ; puis [int((r == k).sum()) for k in range(len(etat))].", en: "p = np.abs(etat) ** 2; r = rng.choice(len(etat), size=n, p=p); then [int((r == k).sum()) for k in range(len(etat))]." },
    solution: "import numpy as np\n\ndef mesure(etat, n, graine):\n    rng = np.random.default_rng(graine)\n    p = np.abs(np.asarray(etat)) ** 2\n    r = rng.choice(len(etat), size=n, p=p / p.sum())\n    return [int((r == k).sum()) for k in range(len(etat))]",
    checks: ["mesure(np.array([1, 0]), 100, 0) == [100, 0]", "sum(mesure(np.array([0.6, 0.8]), 1000, 1)) == 1000", "abs(mesure(np.array([1, 1]) / np.sqrt(2), 10000, 2)[0] - 5000) < 300", "abs(mesure(np.array([0.6, 0.8]), 10000, 3)[1] - 6400) < 300"],
  },
  {
    id: "quant-deux", lang: 'py', group: "quant",
    packages: ["numpy"],
    title: { fr: "Deux qubits : le produit tensoriel", en: "Two qubits: the tensor product" },
    explain: { fr: "Deux qubits forment un système à 4 amplitudes : |00⟩, |01⟩, |10⟩, |11⟩. L'état commun de deux qubits indépendants est leur PRODUIT TENSORIEL, np.kron(a, b). De même, appliquer une porte P au premier qubit seulement, c'est appliquer np.kron(P, I) où I est l'identité. Avec n qubits, il faut 2ⁿ amplitudes : c'est pourquoi simuler 50 qubits épuise un ordinateur classique.", en: "Two qubits form a system with 4 amplitudes: |00⟩, |01⟩, |10⟩, |11⟩. The joint state of two independent qubits is their TENSOR PRODUCT, np.kron(a, b). Likewise, applying a gate P to the first qubit only means applying np.kron(P, I), I being the identity. With n qubits you need 2ⁿ amplitudes: that's why simulating 50 qubits exhausts a classical computer." },
    example: "import numpy as np\nprint(np.kron([1, 0], [0, 1]))",
    task: { fr: "Écris etat2(a, b) (produit tensoriel), sur_premier(P) (matrice 4×4 qui applique P au premier qubit) et sur_second(P).", en: "Write etat2(a, b) (tensor product), sur_premier(P) (4×4 matrix applying P to the first qubit) and sur_second(P)." },
    starter: "import numpy as np\nI = np.eye(2)\n\ndef etat2(a, b):\n    pass\n\ndef sur_premier(P):\n    pass\n\ndef sur_second(P):\n    pass\n",
    hint: { fr: "np.kron(a, b) ; np.kron(P, I) ; np.kron(I, P).", en: "np.kron(a, b); np.kron(P, I); np.kron(I, P)." },
    solution: "import numpy as np\nI = np.eye(2)\n\ndef etat2(a, b):\n    return np.kron(a, b)\n\ndef sur_premier(P):\n    return np.kron(P, I)\n\ndef sur_second(P):\n    return np.kron(I, P)",
    checks: ["np.allclose(etat2(np.array([1, 0]), np.array([0, 1])), [0, 1, 0, 0])", "np.allclose(etat2(np.array([0, 1]), np.array([0, 1])), [0, 0, 0, 1])", "np.allclose(sur_premier(np.array([[0, 1], [1, 0]])) @ np.array([1, 0, 0, 0]), [0, 0, 1, 0])", "np.allclose(sur_second(np.array([[0, 1], [1, 0]])) @ np.array([1, 0, 0, 0]), [0, 1, 0, 0])", "sur_premier(np.eye(2)).shape == (4, 4)"],
  },
  {
    id: "quant-bell", lang: 'py', group: "quant",
    packages: ["numpy"],
    title: { fr: "Intrication : l'état de Bell", en: "Entanglement: the Bell state" },
    explain: { fr: "La porte CNOT agit sur deux qubits : si le premier vaut 1, elle inverse le second. Hadamard sur le premier qubit, puis CNOT, donne l'état de BELL (|00⟩ + |11⟩)/√2. Les deux qubits sont INTRIQUÉS : chacun, seul, est aléatoire ; mais mesurés ensemble, ils donnent toujours le même résultat (00 ou 11, jamais 01 ni 10). Aucun produit tensoriel de deux qubits séparés ne donne cet état.", en: "The CNOT gate acts on two qubits: if the first is 1, it flips the second. Hadamard on the first qubit, then CNOT, gives the BELL state (|00⟩ + |11⟩)/√2. The two qubits are ENTANGLED: each alone is random; but measured together, they always agree (00 or 11, never 01 or 10). No tensor product of two separate qubits gives this state." },
    example: "import numpy as np\nCNOT = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]])\nprint(CNOT @ np.array([0, 0, 1, 0]))",
    task: { fr: "Définis CNOT, puis bell() qui part de |00⟩ = [1, 0, 0, 0], applique H au premier qubit puis CNOT, et renvoie l'état.", en: "Define CNOT, then bell() starting from |00⟩ = [1, 0, 0, 0], applying H to the first qubit then CNOT, and returning the state." },
    starter: "import numpy as np\nH = np.array([[1, 1], [1, -1]]) / np.sqrt(2)\nI = np.eye(2)\nCNOT = None\n\ndef bell():\n    pass\n",
    hint: { fr: "etat = np.kron(H, I) @ etat, puis CNOT @ etat.", en: "etat = np.kron(H, I) @ etat, then CNOT @ etat." },
    solution: "import numpy as np\nH = np.array([[1, 1], [1, -1]]) / np.sqrt(2)\nI = np.eye(2)\nCNOT = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]])\n\ndef bell():\n    etat = np.array([1, 0, 0, 0])\n    etat = np.kron(H, I) @ etat\n    return CNOT @ etat",
    checks: ["np.allclose(bell(), np.array([1, 0, 0, 1]) / np.sqrt(2))", "np.allclose(np.abs(bell()) ** 2, [0.5, 0, 0, 0.5])", "np.allclose(CNOT @ np.array([0, 0, 1, 0]), [0, 0, 0, 1])", "np.allclose(CNOT @ np.array([0, 1, 0, 0]), [0, 1, 0, 0])"],
  },
  {
    id: "quant-grover", lang: 'py', group: "quant",
    packages: ["numpy"],
    title: { fr: "Recherche de Grover sur 2 qubits", en: "Grover search on 2 qubits" },
    explain: { fr: "Chercher un élément parmi N sans index prend en moyenne N/2 essais. L'algorithme de GROVER le fait en environ √N étapes. Sur 2 qubits (4 cases), UNE seule itération suffit : (1) superposition uniforme avec H⊗H ; (2) l'ORACLE inverse le signe de l'amplitude de la case cherchée ; (3) la DIFFUSION reflète toutes les amplitudes autour de leur moyenne (a ← 2·moyenne − a). L'interférence concentre alors toute la probabilité sur la bonne case.", en: "Searching one item among N without an index takes N/2 tries on average. GROVER's algorithm does it in about √N steps. On 2 qubits (4 cells), ONE iteration suffices: (1) uniform superposition with H⊗H; (2) the ORACLE flips the sign of the target cell's amplitude; (3) DIFFUSION reflects all amplitudes around their mean (a ← 2·mean − a). Interference then concentrates all the probability on the right cell." },
    example: "import numpy as np\na = np.array([0.5, 0.5, -0.5, 0.5])\nprint(2 * a.mean() - a)",
    task: { fr: "Écris grover(cible) (cible entre 0 et 3) : renvoie le vecteur des probabilités après une itération.", en: "Write grover(cible) (target between 0 and 3): return the probability vector after one iteration." },
    starter: "import numpy as np\n\ndef grover(cible):\n    pass\n",
    hint: { fr: "etat = np.full(4, 0.5) (c'est H⊗H|00⟩) ; etat[cible] *= -1 ; etat = 2 * etat.mean() - etat ; return np.abs(etat) ** 2.", en: "etat = np.full(4, 0.5) (that is H⊗H|00⟩); etat[cible] *= -1; etat = 2 * etat.mean() - etat; return np.abs(etat) ** 2." },
    solution: "import numpy as np\n\ndef grover(cible):\n    H = np.array([[1, 1], [1, -1]]) / np.sqrt(2)\n    etat = np.kron(H, H) @ np.array([1.0, 0, 0, 0])\n    etat[cible] *= -1\n    etat = 2 * etat.mean() - etat\n    return np.abs(etat) ** 2",
    checks: ["np.allclose(grover(2), [0, 0, 1, 0])", "np.allclose(grover(0), [1, 0, 0, 0])", "all(np.argmax(grover(c)) == c for c in range(4))", "abs(grover(3).sum() - 1) < 1e-9"],
  },
]
