import type { Lesson } from './lessons'

// Parcours Data science (Python dans le navigateur : NumPy, pandas). Contenu original.
// Les vérifications sont des expressions Python évaluées après le code de l'élève.
export const dataLessons: Lesson[] = [
  {
    id: "ds-np-array", lang: 'py', group: "ds-numpy",
    packages: ["numpy"],
    title: { fr: "NumPy : tableaux et normalisation", en: "NumPy: arrays and normalization" },
    explain: { fr: "NumPy est la bibliothèque de base du calcul scientifique en Python. Un tableau np.array([1, 2, 3]) se calcule en bloc : pas de boucle, on écrit x * 2, x.mean(), x.std(). Normaliser (« z-score ») recentre les données sur 0 et les met à l'échelle de 1 : (x - moyenne) / écart-type. C'est l'une des premières étapes de presque tout projet d'apprentissage automatique.", en: "NumPy is the base library for scientific computing in Python. An array np.array([1, 2, 3]) is computed in bulk: no loop, just x * 2, x.mean(), x.std(). Normalizing (“z-score”) recentres data on 0 and scales it to 1: (x - mean) / std. It is one of the first steps of almost every machine learning project." },
    example: "import numpy as np\nx = np.array([1.0, 2.0, 3.0])\nprint(x * 2, x.mean(), x.std())",
    task: { fr: "Écris normaliser(liste) : renvoie un tableau NumPy de même taille, de moyenne 0 et d'écart-type 1.", en: "Write normaliser(liste): return a NumPy array of the same size, with mean 0 and standard deviation 1." },
    starter: "import numpy as np\n\ndef normaliser(liste):\n    pass\n",
    hint: { fr: "x = np.array(liste, dtype=float) ; return (x - x.mean()) / x.std()", en: "x = np.array(liste, dtype=float); return (x - x.mean()) / x.std()" },
    solution: "import numpy as np\n\ndef normaliser(liste):\n    x = np.array(liste, dtype=float)\n    return (x - x.mean()) / x.std()",
    checks: ["abs(normaliser([1, 2, 3]).mean()) < 1e-9", "abs(normaliser([1, 2, 3]).std() - 1) < 1e-9", "abs(normaliser([10, 20, 30, 40]).std() - 1) < 1e-9", "len(normaliser([5, 7, 9])) == 3"],
  },
  {
    id: "ds-np-vector", lang: 'py', group: "ds-numpy",
    packages: ["numpy"],
    title: { fr: "Vecteurs et distances", en: "Vectors and distances" },
    explain: { fr: "Un point de données est un vecteur : une taille et un poids → [1.70, 65]. La distance euclidienne entre deux points est la racine de la somme des carrés des écarts. Avec NumPy, (a - b) ** 2 calcule tous les carrés d'un coup, .sum() les additionne : c'est la base des méthodes de voisinage et du regroupement (clustering).", en: "A data point is a vector: a height and a weight → [1.70, 65]. The Euclidean distance between two points is the square root of the sum of squared differences. With NumPy, (a - b) ** 2 squares everything at once, .sum() adds them: this is the basis of neighbour methods and clustering." },
    example: "import numpy as np\na = np.array([0, 0]); b = np.array([3, 4])\nprint(np.sqrt(((a - b) ** 2).sum()))",
    task: { fr: "Écris distance(a, b) : distance euclidienne entre deux listes de même longueur.", en: "Write distance(a, b): Euclidean distance between two equal-length lists." },
    starter: "import numpy as np\n\ndef distance(a, b):\n    pass\n",
    hint: { fr: "np.sqrt(((np.array(a) - np.array(b)) ** 2).sum())", en: "np.sqrt(((np.array(a) - np.array(b)) ** 2).sum())" },
    solution: "import numpy as np\n\ndef distance(a, b):\n    a, b = np.array(a, dtype=float), np.array(b, dtype=float)\n    return float(np.sqrt(((a - b) ** 2).sum()))",
    checks: ["abs(distance([0, 0], [3, 4]) - 5) < 1e-9", "distance([1, 2, 3], [1, 2, 3]) == 0", "abs(distance([0, 0, 0], [1, 1, 1]) - 3 ** 0.5) < 1e-9"],
  },
  {
    id: "ds-np-matrix", lang: 'py', group: "ds-numpy",
    packages: ["numpy"],
    title: { fr: "Matrices et axes", en: "Matrices and axes" },
    explain: { fr: "Un jeu de données est une matrice : une ligne par individu, une colonne par variable. L'argument axis choisit le sens du calcul : M.mean(axis=0) donne la moyenne de chaque colonne, axis=1 celle de chaque ligne. Grâce au « broadcasting », M - moyennes retire à chaque ligne le vecteur des moyennes de colonnes.", en: "A dataset is a matrix: one row per individual, one column per variable. The axis argument picks the direction: M.mean(axis=0) gives each column's mean, axis=1 each row's. Thanks to broadcasting, M - means subtracts the column-mean vector from every row." },
    example: "import numpy as np\nM = np.array([[1, 2], [3, 4]])\nprint(M.mean(axis=0))",
    task: { fr: "Écris centrer(M) : renvoie la matrice M (liste de listes) dont chaque colonne a été recentrée sur 0 (on retire la moyenne de la colonne).", en: "Write centrer(M): return the matrix M (list of lists) with each column recentred on 0 (subtract the column mean)." },
    starter: "import numpy as np\n\ndef centrer(M):\n    pass\n",
    hint: { fr: "A = np.array(M, dtype=float) ; return A - A.mean(axis=0)", en: "A = np.array(M, dtype=float); return A - A.mean(axis=0)" },
    solution: "import numpy as np\n\ndef centrer(M):\n    A = np.array(M, dtype=float)\n    return A - A.mean(axis=0)",
    checks: ["np.allclose(centrer([[1, 2], [3, 4]]).mean(axis=0), 0)", "np.allclose(centrer([[1, 10], [3, 30]]), [[-1, -10], [1, 10]])", "centrer([[1, 2], [3, 4], [5, 6]]).shape == (3, 2)"],
  },
  {
    id: "ds-pd-groupby", lang: 'py', group: "ds-pandas",
    packages: ["numpy", "pandas"],
    title: { fr: "pandas : groupes et agrégats", en: "pandas: groups and aggregates" },
    explain: { fr: "pandas manipule des tableaux de données (DataFrame) avec des colonnes nommées, comme une feuille de calcul programmable. df.groupby('ville')['prix'].mean() regroupe les lignes par ville puis calcule la moyenne des prix de chaque groupe : la question « combien en moyenne par catégorie ? » de tout analyste de données.", en: "pandas handles data tables (DataFrame) with named columns, like a programmable spreadsheet. df.groupby('city')['price'].mean() groups rows by city then computes each group's mean price: the “how much on average per category?” question every analyst asks." },
    example: "import pandas as pd\ndf = pd.DataFrame({'ville': ['A', 'A', 'B'], 'prix': [10, 20, 5]})\nprint(df.groupby('ville')['prix'].mean())",
    task: { fr: "Écris moyenne_par_groupe(df, groupe, valeur) : renvoie un dictionnaire {groupe: moyenne de valeur}.", en: "Write moyenne_par_groupe(df, groupe, valeur): return a dict {group: mean of value}." },
    starter: "import pandas as pd\n\ndef moyenne_par_groupe(df, groupe, valeur):\n    pass\n",
    hint: { fr: "df.groupby(groupe)[valeur].mean().to_dict()", en: "df.groupby(groupe)[valeur].mean().to_dict()" },
    solution: "import pandas as pd\n\ndef moyenne_par_groupe(df, groupe, valeur):\n    return df.groupby(groupe)[valeur].mean().to_dict()",
    checks: ["moyenne_par_groupe(pd.DataFrame({'v': ['A', 'A', 'B'], 'p': [10, 20, 5]}), 'v', 'p') == {'A': 15.0, 'B': 5.0}", "moyenne_par_groupe(pd.DataFrame({'g': ['x'], 'n': [4]}), 'g', 'n') == {'x': 4.0}"],
  },
  {
    id: "ds-pd-clean", lang: 'py', group: "ds-pandas",
    packages: ["numpy", "pandas"],
    title: { fr: "Nettoyer des données", en: "Cleaning data" },
    explain: { fr: "Les vrais jeux de données sont sales : valeurs manquantes (NaN), doublons. Un analyste passe l'essentiel de son temps à nettoyer. df['age'].fillna(valeur) remplace les manquants ; df.drop_duplicates() supprime les lignes identiques. Remplacer par la médiane est plus robuste que par la moyenne quand il y a des valeurs extrêmes.", en: "Real datasets are dirty: missing values (NaN), duplicates. An analyst spends most of their time cleaning. df['age'].fillna(value) replaces missing ones; df.drop_duplicates() removes identical rows. Filling with the median is more robust than the mean when there are extreme values." },
    example: "import numpy as np, pandas as pd\ndf = pd.DataFrame({'age': [20, np.nan, 40]})\nprint(df['age'].median())",
    task: { fr: "Écris nettoyer(df) : supprime les lignes en double, puis remplace les âges manquants (colonne 'age') par la médiane de cette colonne. Renvoie le DataFrame.", en: "Write nettoyer(df): drop duplicate rows, then fill missing ages (column 'age') with that column's median. Return the DataFrame." },
    starter: "import numpy as np\nimport pandas as pd\n\ndef nettoyer(df):\n    pass\n",
    hint: { fr: "d = df.drop_duplicates().copy() ; d['age'] = d['age'].fillna(d['age'].median()) ; return d", en: "d = df.drop_duplicates().copy(); d['age'] = d['age'].fillna(d['age'].median()); return d" },
    solution: "import numpy as np\nimport pandas as pd\n\ndef nettoyer(df):\n    d = df.drop_duplicates().copy()\n    d['age'] = d['age'].fillna(d['age'].median())\n    return d",
    checks: ["nettoyer(pd.DataFrame({'age': [20.0, 20.0, np.nan, 40.0]}))['age'].tolist() == [20.0, 30.0, 40.0]", "len(nettoyer(pd.DataFrame({'age': [1.0, 1.0, 1.0]}))) == 1", "nettoyer(pd.DataFrame({'age': [10.0, np.nan]}))['age'].isna().sum() == 0"],
  },
  {
    id: "ds-pd-merge", lang: 'py', group: "ds-pandas",
    packages: ["numpy", "pandas"],
    title: { fr: "Joindre des tables", en: "Joining tables" },
    explain: { fr: "Les données vivent souvent dans plusieurs tables : clients d'un côté, commandes de l'autre. pd.merge(a, b, on='id') les relie par une clé commune (une « jointure », comme en SQL). On agrège ensuite avec groupby.", en: "Data often lives in several tables: customers on one side, orders on the other. pd.merge(a, b, on='id') links them by a common key (a “join”, as in SQL). Then aggregate with groupby." },
    example: "import pandas as pd\nclients = pd.DataFrame({'id': [1, 2], 'nom': ['Amina', 'Bruno']})\ncmd = pd.DataFrame({'id': [1, 1, 2], 'montant': [10, 5, 7]})\nprint(pd.merge(clients, cmd, on='id'))",
    task: { fr: "Écris total_par_client(clients, commandes) : tables avec colonne 'id' (clients : 'nom'; commandes : 'montant'). Renvoie {nom: somme des montants}.", en: "Write total_par_client(clients, commandes): tables with an 'id' column (clients: 'nom'; orders: 'montant'). Return {nom: sum of amounts}." },
    starter: "import pandas as pd\n\ndef total_par_client(clients, commandes):\n    pass\n",
    hint: { fr: "m = pd.merge(clients, commandes, on='id') ; m.groupby('nom')['montant'].sum().to_dict()", en: "m = pd.merge(clients, commandes, on='id'); m.groupby('nom')['montant'].sum().to_dict()" },
    solution: "import pandas as pd\n\ndef total_par_client(clients, commandes):\n    m = pd.merge(clients, commandes, on='id')\n    return m.groupby('nom')['montant'].sum().to_dict()",
    checks: ["total_par_client(pd.DataFrame({'id': [1, 2], 'nom': ['Amina', 'Bruno']}), pd.DataFrame({'id': [1, 1, 2], 'montant': [10, 5, 7]})) == {'Amina': 15, 'Bruno': 7}", "total_par_client(pd.DataFrame({'id': [1], 'nom': ['Z']}), pd.DataFrame({'id': [2], 'montant': [9]})) == {}"],
  },
  {
    id: "ds-montecarlo", lang: 'py', group: "ds-ml",
    packages: ["numpy"],
    title: { fr: "Probabilités : simulation de Monte-Carlo", en: "Probability: Monte Carlo simulation" },
    explain: { fr: "Quand un calcul exact est difficile, on simule : on tire beaucoup de nombres au hasard et on compte. Pour estimer π : on tire des points dans le carré [0,1]², la part qui tombe dans le quart de disque (x²+y² ≤ 1) vaut π/4. La « loi des grands nombres » garantit que l'estimation s'améliore avec n. rng = np.random.default_rng(graine) rend le hasard reproductible.", en: "When an exact computation is hard, simulate: draw many random numbers and count. To estimate π: draw points in the square [0,1]²; the share falling inside the quarter disc (x²+y² ≤ 1) is π/4. The law of large numbers guarantees the estimate improves with n. rng = np.random.default_rng(seed) makes randomness reproducible." },
    example: "import numpy as np\nrng = np.random.default_rng(0)\nx = rng.random(5)\nprint(x)",
    task: { fr: "Écris estime_pi(n, graine) : estimation de π avec n points tirés par np.random.default_rng(graine).", en: "Write estime_pi(n, graine): estimate of π with n points drawn by np.random.default_rng(graine)." },
    starter: "import numpy as np\n\ndef estime_pi(n, graine):\n    pass\n",
    hint: { fr: "x, y = rng.random(n), rng.random(n) ; 4 * ((x**2 + y**2) <= 1).mean()", en: "x, y = rng.random(n), rng.random(n); 4 * ((x**2 + y**2) <= 1).mean()" },
    solution: "import numpy as np\n\ndef estime_pi(n, graine):\n    rng = np.random.default_rng(graine)\n    x, y = rng.random(n), rng.random(n)\n    return float(4 * ((x ** 2 + y ** 2) <= 1).mean())",
    checks: ["abs(estime_pi(400000, 0) - 3.14159) < 0.02", "estime_pi(1000, 5) == estime_pi(1000, 5)", "0 <= estime_pi(10, 1) <= 4"],
  },
  {
    id: "ds-corr", lang: 'py', group: "ds-ml",
    packages: ["numpy"],
    title: { fr: "Corrélation", en: "Correlation" },
    explain: { fr: "La corrélation de Pearson mesure à quel point deux variables évoluent ensemble : +1 (parfaitement liées, même sens), -1 (sens opposés), 0 (aucun lien linéaire). np.corrcoef(x, y)[0, 1] la calcule. Attention : corrélation n'est pas causalité — deux courbes peuvent monter ensemble sans que l'une cause l'autre.", en: "Pearson correlation measures how much two variables move together: +1 (perfectly linked, same direction), -1 (opposite), 0 (no linear link). np.corrcoef(x, y)[0, 1] computes it. Careful: correlation is not causation — two curves can rise together without one causing the other." },
    example: "import numpy as np\nprint(np.corrcoef([1, 2, 3], [2, 4, 6])[0, 1])",
    task: { fr: "Écris correlation(x, y) : coefficient de corrélation de Pearson (un nombre).", en: "Write correlation(x, y): Pearson correlation coefficient (a number)." },
    starter: "import numpy as np\n\ndef correlation(x, y):\n    pass\n",
    hint: { fr: "return np.corrcoef(x, y)[0, 1]", en: "return np.corrcoef(x, y)[0, 1]" },
    solution: "import numpy as np\n\ndef correlation(x, y):\n    return float(np.corrcoef(x, y)[0, 1])",
    checks: ["abs(correlation([1, 2, 3], [2, 4, 6]) - 1) < 1e-9", "abs(correlation([1, 2, 3], [3, 2, 1]) + 1) < 1e-9", "abs(correlation([1, 2, 3, 4], [1, 3, 2, 4]) - 0.8) < 1e-9"],
  },
  {
    id: "ds-regression", lang: 'py', group: "ds-ml",
    packages: ["numpy"],
    title: { fr: "Régression linéaire", en: "Linear regression" },
    explain: { fr: "La régression linéaire cherche la droite y = pente × x + ordonnée qui passe « au plus près » des points, au sens des moindres carrés. Avec NumPy : on empile une colonne de x et une colonne de 1, et np.linalg.lstsq résout le système. C'est le plus simple des modèles d'apprentissage automatique, et la brique de base des réseaux de neurones (un neurone = une régression + une activation).", en: "Linear regression finds the line y = slope × x + intercept that passes “closest” to the points, in the least-squares sense. With NumPy: stack a column of x and a column of 1s, and np.linalg.lstsq solves the system. It is the simplest machine learning model and the building block of neural networks (a neuron = a regression + an activation)." },
    example: "import numpy as np\nA = np.column_stack([[1, 2, 3], [1, 1, 1]])\nsol = np.linalg.lstsq(A, [3, 5, 7], rcond=None)[0]\nprint(sol)",
    task: { fr: "Écris regression(x, y) : renvoie (pente, ordonnee) de la droite des moindres carrés.", en: "Write regression(x, y): return (slope, intercept) of the least-squares line." },
    starter: "import numpy as np\n\ndef regression(x, y):\n    pass\n",
    hint: { fr: "A = np.column_stack([x, np.ones(len(x))]) ; pente, ordonnee = np.linalg.lstsq(A, y, rcond=None)[0]", en: "A = np.column_stack([x, np.ones(len(x))]); slope, intercept = np.linalg.lstsq(A, y, rcond=None)[0]" },
    solution: "import numpy as np\n\ndef regression(x, y):\n    x = np.array(x, dtype=float)\n    A = np.column_stack([x, np.ones(len(x))])\n    pente, ordonnee = np.linalg.lstsq(A, np.array(y, dtype=float), rcond=None)[0]\n    return float(pente), float(ordonnee)",
    checks: ["np.allclose(regression([1, 2, 3], [3, 5, 7]), (2, 1))", "np.allclose(regression([0, 1], [5, 5]), (0, 5))", "np.allclose(regression([0, 1, 2, 3], [1, 3, 5, 7.0]), (2, 1))"],
  },
  {
    id: "ds-knn", lang: 'py', group: "ds-ml",
    packages: ["numpy"],
    title: { fr: "Classification : k plus proches voisins", en: "Classification: k nearest neighbours" },
    explain: { fr: "Pour classer un nouveau point, k-NN regarde les k points connus les plus proches et prend l'étiquette majoritaire. Pas d'entraînement : le « modèle » est le jeu de données lui-même. Le choix de k règle le compromis : trop petit → sensible au bruit, trop grand → lissé à l'excès.", en: "To classify a new point, k-NN looks at the k closest known points and takes the majority label. No training: the “model” is the dataset itself. Choosing k sets the trade-off: too small → noise-sensitive, too large → over-smoothed." },
    example: "from collections import Counter\nprint(Counter(['a', 'b', 'a']).most_common(1)[0][0])",
    task: { fr: "Écris knn(X, y, point, k) : X liste de points, y étiquettes ; renvoie l'étiquette majoritaire parmi les k points de X les plus proches de point (distance euclidienne).", en: "Write knn(X, y, point, k): X list of points, y labels; return the majority label among the k points of X closest to point (Euclidean distance)." },
    starter: "import numpy as np\nfrom collections import Counter\n\ndef knn(X, y, point, k):\n    pass\n",
    hint: { fr: "Calcule la distance à chaque point, np.argsort(d)[:k] donne les indices des plus proches, puis Counter.", en: "Compute the distance to each point, np.argsort(d)[:k] gives the nearest indices, then Counter." },
    solution: "import numpy as np\nfrom collections import Counter\n\ndef knn(X, y, point, k):\n    d = np.sqrt(((np.array(X, dtype=float) - np.array(point, dtype=float)) ** 2).sum(axis=1))\n    proches = np.argsort(d, kind='stable')[:k]\n    return Counter(y[i] for i in proches).most_common(1)[0][0]",
    checks: ["knn([[0, 0], [0, 1], [5, 5], [5, 6]], ['a', 'a', 'b', 'b'], [0.2, 0.4], 3) == 'a'", "knn([[0, 0], [0, 1], [5, 5], [5, 6]], ['a', 'a', 'b', 'b'], [5, 5.5], 1) == 'b'", "knn([[1], [2], [10]], [0, 0, 1], [9], 1) == 1"],
  },
  {
    id: "ds-eval", lang: 'py', group: "ds-ml",
    title: { fr: "Évaluer : précision et rappel", en: "Evaluating: precision and recall" },
    explain: { fr: "Un modèle qui prédit « malade / pas malade » peut se tromper de deux façons. Précision = parmi ceux que j'ai déclarés positifs, la part qui l'est vraiment. Rappel = parmi les vrais positifs, la part que j'ai retrouvée. Avec 1 % de malades, un modèle qui répond toujours « sain » a 99 % d'exactitude… et 0 % de rappel : l'exactitude seule trompe.", en: "A model predicting “sick / healthy” can be wrong in two ways. Precision = among those I flagged positive, the share that truly is. Recall = among the true positives, the share I found. With 1% sick people, a model always answering “healthy” has 99% accuracy… and 0% recall: accuracy alone misleads." },
    example: "vrai = [1, 0, 1, 1]\npred = [1, 1, 0, 1]\ntp = sum(1 for v, p in zip(vrai, pred) if v == 1 and p == 1)\nprint(tp)",
    task: { fr: "Écris precision_rappel(y_vrai, y_pred) : listes de 0/1 ; renvoie (precision, rappel) pour la classe 1. Si le dénominateur est 0, renvoie 0 pour cette valeur.", en: "Write precision_rappel(y_vrai, y_pred): lists of 0/1; return (precision, recall) for class 1. If a denominator is 0, return 0 for that value." },
    starter: "def precision_rappel(y_vrai, y_pred):\n    pass\n",
    hint: { fr: "tp = vrais positifs, fp = faux positifs, fn = faux négatifs. precision = tp / (tp + fp), rappel = tp / (tp + fn).", en: "tp = true positives, fp = false positives, fn = false negatives. precision = tp / (tp + fp), recall = tp / (tp + fn)." },
    solution: "def precision_rappel(y_vrai, y_pred):\n    tp = sum(1 for v, p in zip(y_vrai, y_pred) if v == 1 and p == 1)\n    fp = sum(1 for v, p in zip(y_vrai, y_pred) if v == 0 and p == 1)\n    fn = sum(1 for v, p in zip(y_vrai, y_pred) if v == 1 and p == 0)\n    precision = tp / (tp + fp) if tp + fp else 0\n    rappel = tp / (tp + fn) if tp + fn else 0\n    return precision, rappel",
    checks: ["precision_rappel([1, 0, 1, 1], [1, 1, 0, 1]) == (2 / 3, 2 / 3)", "precision_rappel([1, 1, 1], [0, 0, 0]) == (0, 0)", "precision_rappel([0, 0], [1, 1]) == (0, 0)", "precision_rappel([1, 0], [1, 0]) == (1, 1)"],
  },
  {
    id: "ds-split", lang: 'py', group: "ds-ml",
    packages: ["numpy"],
    title: { fr: "Séparer entraînement et test", en: "Train / test split" },
    explain: { fr: "On n'évalue jamais un modèle sur les données qui ont servi à l'entraîner : il pourrait les avoir apprises par cœur. On met de côté une part (ex. 20 %) comme jeu de test, jamais vu pendant l'entraînement. Il faut mélanger avant de couper, de façon reproductible (graine fixée), et couper à la même place les entrées et les étiquettes.", en: "You never evaluate a model on the data it was trained on: it may have memorised it. Set aside a share (e.g. 20%) as a test set, never seen in training. Shuffle before cutting, reproducibly (fixed seed), and cut inputs and labels at the same place." },
    example: "import numpy as np\nrng = np.random.default_rng(0)\nprint(rng.permutation(5))",
    task: { fr: "Écris separer(X, y, part_test, graine) : renvoie (X_train, y_train, X_test, y_test), les listes étant mélangées par np.random.default_rng(graine).permutation ; la taille du test est round(len(X) * part_test).", en: "Write separer(X, y, part_test, graine): return (X_train, y_train, X_test, y_test), shuffled with np.random.default_rng(graine).permutation; the test size is round(len(X) * part_test)." },
    starter: "import numpy as np\n\ndef separer(X, y, part_test, graine):\n    pass\n",
    hint: { fr: "idx = rng.permutation(len(X)) ; n_test = round(len(X) * part_test) ; test = idx[:n_test] ; train = idx[n_test:]", en: "idx = rng.permutation(len(X)); n_test = round(len(X) * part_test); test = idx[:n_test]; train = idx[n_test:]" },
    solution: "import numpy as np\n\ndef separer(X, y, part_test, graine):\n    rng = np.random.default_rng(graine)\n    idx = rng.permutation(len(X))\n    n_test = round(len(X) * part_test)\n    test, train = idx[:n_test], idx[n_test:]\n    return [X[i] for i in train], [y[i] for i in train], [X[i] for i in test], [y[i] for i in test]",
    checks: ["len(separer(list(range(10)), list(range(10)), 0.2, 0)[2]) == 2", "(r := separer(list(range(10)), list(range(10)), 0.3, 1), sorted(r[0] + r[2]) == list(range(10)))[-1]", "(r := separer(list(range(10)), [x * 10 for x in range(10)], 0.3, 1), all(b == a * 10 for a, b in zip(r[0], r[1])))[-1]", "separer(list(range(10)), list(range(10)), 0.3, 7) == separer(list(range(10)), list(range(10)), 0.3, 7)"],
  },
]
