import type { Lesson } from './lessons'

// Parcours Deep learning : réseaux de neurones écrits à la main avec NumPy (Python dans le navigateur). Contenu original.
export const dlLessons: Lesson[] = [
  {
    id: "dl-neuron", lang: 'py', group: "dl",
    packages: ["numpy"],
    title: { fr: "Le neurone artificiel", en: "The artificial neuron" },
    explain: { fr: "Un neurone artificiel fait trois choses : il pondère ses entrées (produit scalaire w·x), ajoute un biais b, puis passe le résultat dans une fonction d'activation. Avec la sigmoïde 1 / (1 + e^-z), la sortie est comprise entre 0 et 1 : on peut la lire comme une probabilité. Un réseau de neurones n'est rien d'autre que beaucoup de ces neurones branchés les uns aux autres.", en: "An artificial neuron does three things: it weighs its inputs (dot product w·x), adds a bias b, then passes the result through an activation function. With the sigmoid 1 / (1 + e^-z) the output lies between 0 and 1: it can be read as a probability. A neural network is nothing but many of these neurons wired together." },
    example: "import numpy as np\nz = np.dot([1, 2], [0.5, 0.25]) + 0.1\nprint(1 / (1 + np.exp(-z)))",
    task: { fr: "Écris neurone(x, w, b) : sigmoïde de (w·x + b).", en: "Write neurone(x, w, b): sigmoid of (w·x + b)." },
    starter: "import numpy as np\n\ndef neurone(x, w, b):\n    pass\n",
    hint: { fr: "z = np.dot(w, x) + b ; return 1 / (1 + np.exp(-z))", en: "z = np.dot(w, x) + b; return 1 / (1 + np.exp(-z))" },
    solution: "import numpy as np\n\ndef neurone(x, w, b):\n    z = np.dot(w, x) + b\n    return 1 / (1 + np.exp(-z))",
    checks: ["abs(neurone([0], [0], 0) - 0.5) < 1e-9", "abs(neurone([1, 1], [1, 1], -2) - 0.5) < 1e-9", "neurone([100], [1], 0) > 0.99", "neurone([-100], [1], 0) < 0.01"],
  },
  {
    id: "dl-activations", lang: 'py', group: "dl",
    packages: ["numpy"],
    title: { fr: "Fonctions d'activation", en: "Activation functions" },
    explain: { fr: "Sans activation non linéaire, empiler des couches ne sert à rien (une composition de fonctions linéaires reste linéaire). ReLU = max(0, z) est la plus utilisée dans les couches cachées. Softmax transforme un vecteur de scores en probabilités qui somment à 1 : c'est la sortie des classifieurs multi-classes. Piège classique : exp(1000) déborde. Astuce : soustraire le maximum avant exp ne change pas le résultat et évite le débordement.", en: "Without a non-linear activation, stacking layers is pointless (a composition of linear functions stays linear). ReLU = max(0, z) is the most used in hidden layers. Softmax turns a score vector into probabilities summing to 1: it is the output of multi-class classifiers. Classic trap: exp(1000) overflows. Trick: subtracting the maximum before exp does not change the result and avoids overflow." },
    example: "import numpy as np\nz = np.array([1.0, 2.0, 3.0])\ne = np.exp(z - z.max())\nprint(e / e.sum())",
    task: { fr: "Écris relu(z) et softmax(z) (z : tableau 1D). softmax doit résister à des scores énormes comme [1000, 1000].", en: "Write relu(z) and softmax(z) (z: 1D array). softmax must withstand huge scores like [1000, 1000]." },
    starter: "import numpy as np\n\ndef relu(z):\n    pass\n\ndef softmax(z):\n    pass\n",
    hint: { fr: "relu : np.maximum(0, z). softmax : e = np.exp(z - z.max()) puis e / e.sum().", en: "relu: np.maximum(0, z). softmax: e = np.exp(z - z.max()) then e / e.sum()." },
    solution: "import numpy as np\n\ndef relu(z):\n    return np.maximum(0, z)\n\ndef softmax(z):\n    z = np.array(z, dtype=float)\n    e = np.exp(z - z.max())\n    return e / e.sum()",
    checks: ["list(relu(np.array([-1.0, 0.0, 2.0]))) == [0.0, 0.0, 2.0]", "np.allclose(softmax([1000, 1000]), [0.5, 0.5])", "abs(softmax([1, 2, 3]).sum() - 1) < 1e-9", "np.allclose(softmax([0, 0, 0, 0]), 0.25)", "int(np.argmax(softmax([1, 5, 2]))) == 1"],
  },
  {
    id: "dl-loss", lang: 'py', group: "dl",
    packages: ["numpy"],
    title: { fr: "Fonctions de perte", en: "Loss functions" },
    explain: { fr: "Entraîner un modèle = minimiser une « perte » qui mesure son erreur. Pour une valeur à prédire : l'erreur quadratique moyenne (MSE). Pour une probabilité : l'entropie croisée binaire −[y·log(p) + (1−y)·log(1−p)], qui punit sévèrement un modèle sûr de lui et faux. Si p vaut exactement 0 ou 1, log donne l'infini : on « borne » p dans [ε, 1−ε].", en: "Training a model = minimizing a “loss” that measures its error. For a value to predict: mean squared error (MSE). For a probability: binary cross-entropy −[y·log(p) + (1−y)·log(1−p)], which severely punishes a confident wrong model. If p is exactly 0 or 1, log gives infinity: clip p into [ε, 1−ε]." },
    example: "import numpy as np\ny = np.array([1, 0]); p = np.array([0.9, 0.2])\nprint(np.mean((y - p) ** 2))",
    task: { fr: "Écris mse(y, p) et entropie_croisee(y, p) (moyennes sur les exemples ; borne p entre 1e-12 et 1 - 1e-12).", en: "Write mse(y, p) and entropie_croisee(y, p) (means over examples; clip p between 1e-12 and 1 - 1e-12)." },
    starter: "import numpy as np\n\ndef mse(y, p):\n    pass\n\ndef entropie_croisee(y, p):\n    pass\n",
    hint: { fr: "np.clip(p, 1e-12, 1 - 1e-12) puis -np.mean(y*np.log(p) + (1-y)*np.log(1-p)).", en: "np.clip(p, 1e-12, 1 - 1e-12) then -np.mean(y*np.log(p) + (1-y)*np.log(1-p))." },
    solution: "import numpy as np\n\ndef mse(y, p):\n    y, p = np.array(y, dtype=float), np.array(p, dtype=float)\n    return float(np.mean((y - p) ** 2))\n\ndef entropie_croisee(y, p):\n    y = np.array(y, dtype=float)\n    p = np.clip(np.array(p, dtype=float), 1e-12, 1 - 1e-12)\n    return float(-np.mean(y * np.log(p) + (1 - y) * np.log(1 - p)))",
    checks: ["mse([1, 2], [1, 4]) == 2", "mse([3], [3]) == 0", "abs(entropie_croisee([1, 0], [0.9, 0.1]) + np.log(0.9)) < 1e-9", "entropie_croisee([1], [0]) < 40", "entropie_croisee([1], [0.99]) < entropie_croisee([1], [0.6])"],
  },
  {
    id: "dl-gradient", lang: 'py', group: "dl",
    title: { fr: "Descente de gradient", en: "Gradient descent" },
    explain: { fr: "Le gradient indique dans quel sens la perte augmente le plus vite ; on avance donc dans le sens opposé, à pas de taille « taux d'apprentissage » (lr) : x ← x − lr × f'(x). C'est LE mécanisme d'apprentissage de tous les réseaux de neurones. Ici f(x) = (x − 3)², dont la dérivée est 2(x − 3) et le minimum x = 3. Si lr est trop grand, l'algorithme diverge au lieu de converger : à tester !", en: "The gradient says in which direction the loss grows fastest; so we step the opposite way, with step size “learning rate” (lr): x ← x − lr × f'(x). This is THE learning mechanism of all neural networks. Here f(x) = (x − 3)², whose derivative is 2(x − 3) and minimum x = 3. If lr is too large the algorithm diverges instead of converging: try it!" },
    example: "x = 0.0\nfor _ in range(3):\n    x = x - 0.1 * 2 * (x - 3)\n    print(x)",
    task: { fr: "Écris descente(x0, lr, n) : n pas de descente de gradient sur f(x) = (x − 3)² depuis x0 ; renvoie le x final.", en: "Write descente(x0, lr, n): n gradient descent steps on f(x) = (x − 3)² from x0; return the final x." },
    starter: "def descente(x0, lr, n):\n    x = x0\n    # répète n fois\n    return x\n",
    hint: { fr: "À chaque pas : x = x - lr * 2 * (x - 3).", en: "Each step: x = x - lr * 2 * (x - 3)." },
    solution: "def descente(x0, lr, n):\n    x = x0\n    for _ in range(n):\n        x = x - lr * 2 * (x - 3)\n    return x",
    checks: ["abs(descente(0, 0.1, 200) - 3) < 1e-6", "descente(10, 0.1, 0) == 10", "abs(descente(0, 1.1, 50)) > 100", "abs(descente(0, 0.5, 1) - 3) < 1e-9"],
  },
  {
    id: "dl-linreg-gd", lang: 'py', group: "dl",
    packages: ["numpy"],
    title: { fr: "Régression linéaire par descente de gradient", en: "Linear regression by gradient descent" },
    explain: { fr: "Au lieu de résoudre la régression d'un coup, on l'apprend : on part de w = 0, b = 0, puis on corrige à chaque pas. Avec prédiction p = w·x + b et perte MSE, les gradients sont dw = 2·moyenne((p − y)·x) et db = 2·moyenne(p − y). C'est exactement la boucle d'entraînement d'un vrai réseau, en minuscule.", en: "Instead of solving the regression at once, we learn it: start from w = 0, b = 0, then correct at each step. With prediction p = w·x + b and MSE loss, the gradients are dw = 2·mean((p − y)·x) and db = 2·mean(p − y). It is exactly the training loop of a real network, in miniature." },
    example: "import numpy as np\nx = np.array([0.0, 1.0]); y = np.array([2.0, 5.0])\nw, b = 0.0, 0.0\np = w * x + b\nprint(2 * np.mean((p - y) * x))",
    task: { fr: "Écris entraine(x, y, lr, n) : renvoie (w, b) après n pas de descente (x, y : tableaux 1D).", en: "Write entraine(x, y, lr, n): return (w, b) after n descent steps (x, y: 1D arrays)." },
    starter: "import numpy as np\n\ndef entraine(x, y, lr, n):\n    x, y = np.array(x, dtype=float), np.array(y, dtype=float)\n    w, b = 0.0, 0.0\n    # n pas\n    return w, b\n",
    hint: { fr: "p = w * x + b ; w -= lr * 2 * np.mean((p - y) * x) ; b -= lr * 2 * np.mean(p - y)", en: "p = w * x + b; w -= lr * 2 * np.mean((p - y) * x); b -= lr * 2 * np.mean(p - y)" },
    solution: "import numpy as np\n\ndef entraine(x, y, lr, n):\n    x, y = np.array(x, dtype=float), np.array(y, dtype=float)\n    w, b = 0.0, 0.0\n    for _ in range(n):\n        p = w * x + b\n        dw = 2 * np.mean((p - y) * x)\n        db = 2 * np.mean(p - y)\n        w -= lr * dw\n        b -= lr * db\n    return w, b",
    checks: ["(r := entraine(np.linspace(0, 1, 20), 3 * np.linspace(0, 1, 20) + 2, 0.5, 5000), abs(r[0] - 3) < 0.05 and abs(r[1] - 2) < 0.05)[-1]", "(r := entraine([0, 1, 2], [1, 3, 5], 0.1, 3000), abs(r[0] - 2) < 0.05 and abs(r[1] - 1) < 0.05)[-1]", "entraine([0, 1], [0, 1], 0.1, 0) == (0.0, 0.0)"],
  },
  {
    id: "dl-logreg", lang: 'py', group: "dl",
    packages: ["numpy"],
    title: { fr: "Classification : régression logistique", en: "Classification: logistic regression" },
    explain: { fr: "Pour classer (0 ou 1), on applique la sigmoïde à w·x + b et on lit le résultat comme P(classe = 1). Avec la perte d'entropie croisée, le gradient est étonnamment simple : p − y. Donc dw = Xᵀ(p − y) / n et db = moyenne(p − y). Un neurone entraîné ainsi, c'est déjà un classifieur — et c'est la dernière couche de la plupart des réseaux de classification.", en: "To classify (0 or 1), apply the sigmoid to w·x + b and read the result as P(class = 1). With the cross-entropy loss the gradient is surprisingly simple: p − y. So dw = Xᵀ(p − y) / n and db = mean(p − y). A neuron trained this way is already a classifier — and it is the last layer of most classification networks." },
    example: "import numpy as np\nX = np.array([[0, 0], [1, 1]]); w = np.zeros(2)\nprint(X @ w)",
    task: { fr: "Écris entraine_logistique(X, y, lr, n) : renvoie (w, b) (w : vecteur) après n pas de descente sur l'entropie croisée.", en: "Write entraine_logistique(X, y, lr, n): return (w, b) (w: vector) after n descent steps on cross-entropy." },
    starter: "import numpy as np\n\ndef entraine_logistique(X, y, lr, n):\n    X, y = np.array(X, dtype=float), np.array(y, dtype=float)\n    w, b = np.zeros(X.shape[1]), 0.0\n    # n pas\n    return w, b\n",
    hint: { fr: "p = 1 / (1 + np.exp(-(X @ w + b))) ; w -= lr * X.T @ (p - y) / len(y) ; b -= lr * np.mean(p - y)", en: "p = 1 / (1 + np.exp(-(X @ w + b))); w -= lr * X.T @ (p - y) / len(y); b -= lr * np.mean(p - y)" },
    solution: "import numpy as np\n\ndef entraine_logistique(X, y, lr, n):\n    X, y = np.array(X, dtype=float), np.array(y, dtype=float)\n    w, b = np.zeros(X.shape[1]), 0.0\n    for _ in range(n):\n        p = 1 / (1 + np.exp(-(X @ w + b)))\n        w = w - lr * X.T @ (p - y) / len(y)\n        b = b - lr * np.mean(p - y)\n    return w, b",
    checks: ["(lambda r: [int(1 / (1 + np.exp(-(np.dot(x, r[0]) + r[1]))) > 0.5) for x in [[0, 0], [0, 1], [1, 0], [1, 1]]])(entraine_logistique([[0, 0], [0, 1], [1, 0], [1, 1]], [0, 0, 0, 1], 1.0, 5000)) == [0, 0, 0, 1]", "(lambda r: [int(1 / (1 + np.exp(-(np.dot(x, r[0]) + r[1]))) > 0.5) for x in [[0], [1], [2], [3]]])(entraine_logistique([[0], [1], [2], [3]], [0, 0, 1, 1], 1.0, 5000)) == [0, 0, 1, 1]"],
  },
  {
    id: "dl-forward", lang: 'py', group: "dl-reseaux",
    packages: ["numpy"],
    title: { fr: "Réseau à deux couches : propagation avant", en: "Two-layer network: forward pass" },
    explain: { fr: "Un réseau de neurones alterne multiplications matricielles et activations. Couche cachée : h = relu(W1·x + b1). Sortie : p = sigmoïde(W2·h + b2). On l'appelle « propagation avant » (forward). Chaque ligne de W1 est un neurone de la couche cachée ; ces neurones apprennent à détecter des motifs que la sortie combine.", en: "A neural network alternates matrix multiplications and activations. Hidden layer: h = relu(W1·x + b1). Output: p = sigmoid(W2·h + b2). This is called the “forward pass”. Each row of W1 is a hidden neuron; these neurons learn to detect patterns that the output combines." },
    example: "import numpy as np\nW = np.array([[1, -1], [0.5, 0.5]]); x = np.array([2, 1])\nprint(W @ x)",
    task: { fr: "Écris forward(x, W1, b1, W2, b2) : ReLU sur la couche cachée, sigmoïde en sortie ; renvoie le tableau de sortie.", en: "Write forward(x, W1, b1, W2, b2): ReLU on the hidden layer, sigmoid at the output; return the output array." },
    starter: "import numpy as np\n\ndef forward(x, W1, b1, W2, b2):\n    pass\n",
    hint: { fr: "h = np.maximum(0, W1 @ x + b1) ; z = W2 @ h + b2 ; sigmoïde de z", en: "h = np.maximum(0, W1 @ x + b1); z = W2 @ h + b2; sigmoid of z" },
    solution: "import numpy as np\n\ndef forward(x, W1, b1, W2, b2):\n    h = np.maximum(0, W1 @ x + b1)\n    z = W2 @ h + b2\n    return 1 / (1 + np.exp(-z))",
    checks: ["abs(np.ravel(forward(np.array([2.0, 1.0]), np.array([[1.0, -1.0], [0.5, 0.5]]), np.zeros(2), np.array([[1.0, 1.0]]), np.array([-2.0])))[0] - 0.6224593) < 1e-6", "abs(np.ravel(forward(np.array([0.0, 0.0]), np.eye(2), np.zeros(2), np.array([[1.0, 1.0]]), np.zeros(1)))[0] - 0.5) < 1e-9", "np.ravel(forward(np.array([-5.0]), np.array([[1.0]]), np.zeros(1), np.array([[10.0]]), np.zeros(1)))[0] == 0.5"],
  },
  {
    id: "dl-xor", lang: 'py', group: "dl-reseaux",
    packages: ["numpy"],
    title: { fr: "Rétropropagation : apprendre le XOR", en: "Backpropagation: learning XOR" },
    explain: { fr: "Le XOR (vrai si exactement une entrée est vraie) n'est pas séparable par une droite : un neurone seul n'y arrive pas, il faut une couche cachée. La rétropropagation applique la règle de dérivation en chaîne de la sortie vers l'entrée. Avec sortie sigmoïde + entropie croisée : dz2 = p − y ; dW2 = hᵀ·dz2 / n ; db2 = moyenne(dz2) ; dh = dz2·W2ᵀ ; dz1 = dh·(1 − h²) (dérivée de tanh) ; dW1 = Xᵀ·dz1 / n ; db1 = moyenne(dz1).", en: "XOR (true if exactly one input is true) is not separable by a line: a single neuron cannot do it, you need a hidden layer. Backpropagation applies the chain rule from output to input. With sigmoid output + cross-entropy: dz2 = p − y; dW2 = hᵀ·dz2 / n; db2 = mean(dz2); dh = dz2·W2ᵀ; dz1 = dh·(1 − h²) (derivative of tanh); dW1 = Xᵀ·dz1 / n; db1 = mean(dz1)." },
    example: "import numpy as np\nh = np.tanh(np.array([[0.5, -1.0]]))\nprint(1 - h ** 2)",
    task: { fr: "Complète la rétropropagation dans entraine_xor : après l'entraînement, la fonction renvoyée doit prédire correctement les 4 cas du XOR.", en: "Complete the backpropagation in entraine_xor: after training, the returned function must predict the 4 XOR cases correctly." },
    starter: "import numpy as np\n\ndef sigmoide(z):\n    return 1 / (1 + np.exp(-z))\n\ndef entraine_xor(graine=0, n=8000, lr=1.0):\n    rng = np.random.default_rng(graine)\n    X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=float)\n    y = np.array([[0], [1], [1], [0]], dtype=float)\n    W1, b1 = rng.normal(size=(2, 6)), np.zeros(6)\n    W2, b2 = rng.normal(size=(6, 1)), np.zeros(1)\n    for _ in range(n):\n        h = np.tanh(X @ W1 + b1)\n        p = sigmoide(h @ W2 + b2)\n        # --- rétropropagation à écrire ---\n        dz2 = None\n        dW2 = None\n        db2 = None\n        dh = None\n        dz1 = None\n        dW1 = None\n        db1 = None\n        # --- mise à jour ---\n        W1 -= lr * dW1\n        b1 -= lr * db1\n        W2 -= lr * dW2\n        b2 -= lr * db2\n    return lambda x: sigmoide(np.tanh(np.array(x, dtype=float) @ W1 + b1) @ W2 + b2)\n",
    hint: { fr: "dz2 = p - y ; dW2 = h.T @ dz2 / len(X) ; db2 = dz2.mean(axis=0) ; dh = dz2 @ W2.T ; dz1 = dh * (1 - h ** 2) ; dW1 = X.T @ dz1 / len(X) ; db1 = dz1.mean(axis=0)", en: "dz2 = p - y; dW2 = h.T @ dz2 / len(X); db2 = dz2.mean(axis=0); dh = dz2 @ W2.T; dz1 = dh * (1 - h ** 2); dW1 = X.T @ dz1 / len(X); db1 = dz1.mean(axis=0)" },
    solution: "import numpy as np\n\ndef sigmoide(z):\n    return 1 / (1 + np.exp(-z))\n\ndef entraine_xor(graine=0, n=8000, lr=1.0):\n    rng = np.random.default_rng(graine)\n    X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=float)\n    y = np.array([[0], [1], [1], [0]], dtype=float)\n    W1, b1 = rng.normal(size=(2, 6)), np.zeros(6)\n    W2, b2 = rng.normal(size=(6, 1)), np.zeros(1)\n    for _ in range(n):\n        h = np.tanh(X @ W1 + b1)\n        p = sigmoide(h @ W2 + b2)\n        dz2 = p - y\n        dW2 = h.T @ dz2 / len(X)\n        db2 = dz2.mean(axis=0)\n        dh = dz2 @ W2.T\n        dz1 = dh * (1 - h ** 2)\n        dW1 = X.T @ dz1 / len(X)\n        db1 = dz1.mean(axis=0)\n        W1 -= lr * dW1\n        b1 -= lr * db1\n        W2 -= lr * dW2\n        b2 -= lr * db2\n    return lambda x: sigmoide(np.tanh(np.array(x, dtype=float) @ W1 + b1) @ W2 + b2)\n",
    checks: ["[int(entraine_xor(0)([a, b])[0] > 0.5) for a, b in [(0, 0), (0, 1), (1, 0), (1, 1)]] == [0, 1, 1, 0]", "[int(entraine_xor(1)([a, b])[0] > 0.5) for a, b in [(0, 0), (0, 1), (1, 0), (1, 1)]] == [0, 1, 1, 0]", "[int(entraine_xor(2)([a, b])[0] > 0.5) for a, b in [(0, 0), (0, 1), (1, 0), (1, 1)]] == [0, 1, 1, 0]"],
  },
  {
    id: "dl-overfit", lang: 'py', group: "dl-reseaux",
    packages: ["numpy"],
    title: { fr: "Surapprentissage", en: "Overfitting" },
    explain: { fr: "Un modèle trop puissant apprend le bruit des données d'entraînement au lieu du motif réel : erreur d'entraînement minuscule, erreur sur de nouvelles données énorme. On le détecte avec un jeu de validation. Ici le « modèle » est un polynôme de degré d (np.polyfit) : plus d est grand, plus il colle aux points d'entraînement… jusqu'à l'excès. Choisir le degré qui minimise l'erreur de VALIDATION est la méthode de base pour régler la complexité d'un modèle.", en: "A model that is too powerful learns the noise of the training data instead of the real pattern: tiny training error, huge error on new data. You detect it with a validation set. Here the “model” is a degree-d polynomial (np.polyfit): the larger d, the closer it hugs training points… to excess. Picking the degree that minimizes VALIDATION error is the basic way to tune a model's complexity." },
    example: "import numpy as np\nc = np.polyfit([0, 1, 2], [0, 1, 4], 2)\nprint(np.polyval(c, 3))",
    task: { fr: "Écris meilleur_degre(x_tr, y_tr, x_val, y_val, degres) : pour chaque degré, ajuste un polynôme sur l'entraînement et mesure l'erreur quadratique moyenne sur la validation ; renvoie le degré à l'erreur la plus basse.", en: "Write meilleur_degre(x_tr, y_tr, x_val, y_val, degres): for each degree, fit a polynomial on training and measure mean squared error on validation; return the degree with the lowest error." },
    starter: "import numpy as np\n\ndef meilleur_degre(x_tr, y_tr, x_val, y_val, degres):\n    pass\n",
    hint: { fr: "c = np.polyfit(x_tr, y_tr, d) ; erreur = np.mean((np.polyval(c, x_val) - y_val) ** 2) ; garde le d de plus petite erreur", en: "c = np.polyfit(x_tr, y_tr, d); err = np.mean((np.polyval(c, x_val) - y_val) ** 2); keep the d with the smallest error" },
    solution: "import numpy as np\n\ndef meilleur_degre(x_tr, y_tr, x_val, y_val, degres):\n    meilleur, erreur_min = None, None\n    for d in degres:\n        c = np.polyfit(x_tr, y_tr, d)\n        e = np.mean((np.polyval(c, np.array(x_val)) - np.array(y_val)) ** 2)\n        if erreur_min is None or e < erreur_min:\n            meilleur, erreur_min = d, e\n    return meilleur",
    checks: ["meilleur_degre([0, 1, 2, 3], [0, 1, 4, 9], [4, 5], [16, 25], [1, 2, 3]) == 2", "meilleur_degre([0, 1, 2, 3, 4], [1.1, 2.9, 5.2, 6.8, 9.1], [5, 6], [11, 13], [1, 2, 3, 4]) == 1", "(lambda r: meilleur_degre(np.linspace(0, 3, 12), np.sin(np.linspace(0, 3, 12)) + r.normal(0, 0.2, 12), np.linspace(0.1, 2.9, 15), np.sin(np.linspace(0.1, 2.9, 15)), [1, 3, 5, 9]))(np.random.default_rng(0)) in [3, 5]"],
  },
  {
    id: "dl-adam", lang: 'py', group: "dl-reseaux",
    packages: ["numpy"],
    title: { fr: "L'optimiseur Adam", en: "The Adam optimizer" },
    explain: { fr: "La descente de gradient simple est lente sur les vrais réseaux. Adam garde deux moyennes mobiles du gradient g : m (la direction, premier moment) et v (l'amplitude, second moment). Corrigées de leur biais de départ (m̂ = m / (1 − β1^t), v̂ = v / (1 − β2^t)), elles donnent la mise à jour w ← w − lr · m̂ / (√v̂ + ε). Chaque paramètre a ainsi son propre pas adaptatif. C'est l'optimiseur par défaut de l'apprentissage profond.", en: "Plain gradient descent is slow on real networks. Adam keeps two moving averages of the gradient g: m (the direction, first moment) and v (the magnitude, second moment). Corrected for their start-up bias (m̂ = m / (1 − β1^t), v̂ = v / (1 − β2^t)), they give the update w ← w − lr · m̂ / (√v̂ + ε). Each parameter thus has its own adaptive step. It is the default optimizer of deep learning." },
    example: "b1, t = 0.9, 1\nprint(1 - b1 ** t)",
    task: { fr: "Écris adam(w, g, m, v, t, lr=0.001, b1=0.9, b2=0.999, eps=1e-8) : un pas d'Adam ; renvoie (w, m, v) mis à jour (t commence à 1).", en: "Write adam(w, g, m, v, t, lr=0.001, b1=0.9, b2=0.999, eps=1e-8): one Adam step; return updated (w, m, v) (t starts at 1)." },
    starter: "import numpy as np\n\ndef adam(w, g, m, v, t, lr=0.001, b1=0.9, b2=0.999, eps=1e-8):\n    pass\n",
    hint: { fr: "m = b1*m + (1-b1)*g ; v = b2*v + (1-b2)*g**2 ; m_chap = m/(1-b1**t) ; v_chap = v/(1-b2**t) ; w = w - lr*m_chap/(np.sqrt(v_chap)+eps)", en: "m = b1*m + (1-b1)*g; v = b2*v + (1-b2)*g**2; m_hat = m/(1-b1**t); v_hat = v/(1-b2**t); w = w - lr*m_hat/(np.sqrt(v_hat)+eps)" },
    solution: "import numpy as np\n\ndef adam(w, g, m, v, t, lr=0.001, b1=0.9, b2=0.999, eps=1e-8):\n    m = b1 * m + (1 - b1) * g\n    v = b2 * v + (1 - b2) * g ** 2\n    m_chap = m / (1 - b1 ** t)\n    v_chap = v / (1 - b2 ** t)\n    w = w - lr * m_chap / (np.sqrt(v_chap) + eps)\n    return w, m, v",
    checks: ["abs(adam(1.0, 2.0, 0.0, 0.0, 1)[0] - (1.0 - 0.001)) < 1e-6", "abs(adam(1.0, 2.0, 0.0, 0.0, 1)[1] - 0.2) < 1e-12", "abs(adam(1.0, 2.0, 0.0, 0.0, 1)[2] - 0.004) < 1e-12", "abs(adam(0.0, -3.0, 0.0, 0.0, 1, lr=0.1)[0] - 0.1) < 1e-6"],
  },
  {
    id: "dl-batches", lang: 'py', group: "dl-reseaux",
    packages: ["numpy"],
    title: { fr: "Mini-lots (mini-batches)", en: "Mini-batches" },
    explain: { fr: "Sur des millions d'exemples, on ne calcule pas le gradient sur tout le jeu à chaque pas : on le calcule sur de petits « lots » mélangés. Un passage complet sur les données s'appelle une époque. Mélanger à chaque époque évite que le modèle apprenne l'ordre des exemples.", en: "On millions of examples you do not compute the gradient on the whole set at each step: you compute it on small shuffled “batches”. One full pass over the data is called an epoch. Shuffling each epoch prevents the model from learning the order of examples." },
    example: "import numpy as np\nrng = np.random.default_rng(0)\nprint(rng.permutation(6))",
    task: { fr: "Écris lots(n, taille, graine) : liste de listes d'indices (0..n-1) mélangés par np.random.default_rng(graine).permutation, découpés en lots de `taille` (le dernier peut être plus petit).", en: "Write lots(n, taille, graine): list of lists of indices (0..n-1) shuffled with np.random.default_rng(graine).permutation, cut into batches of `taille` (the last may be smaller)." },
    starter: "import numpy as np\n\ndef lots(n, taille, graine):\n    pass\n",
    hint: { fr: "idx = rng.permutation(n) ; [list(idx[i:i + taille]) for i in range(0, n, taille)]", en: "idx = rng.permutation(n); [list(idx[i:i + taille]) for i in range(0, n, taille)]" },
    solution: "import numpy as np\n\ndef lots(n, taille, graine):\n    idx = np.random.default_rng(graine).permutation(n)\n    return [[int(j) for j in idx[i:i + taille]] for i in range(0, n, taille)]",
    checks: ["len(lots(10, 4, 0)) == 3", "[len(l) for l in lots(10, 4, 0)] == [4, 4, 2]", "sorted(sum(lots(10, 4, 1), [])) == list(range(10))", "lots(8, 4, 3) == lots(8, 4, 3)", "lots(0, 4, 0) == []"],
  },
  {
    id: "dl-conv", lang: 'py', group: "dl-reseaux",
    packages: ["numpy"],
    title: { fr: "Convolution : voir des motifs", en: "Convolution: seeing patterns" },
    explain: { fr: "Les réseaux convolutifs (CNN) reconnaissent des images en faisant glisser un petit filtre (« noyau ») sur l'image : à chaque position, on multiplie le filtre par la zone qu'il recouvre et on additionne. Un filtre [[1, -1]] réagit aux contours verticaux. Les premières couches d'un CNN apprennent ainsi seules des détecteurs de contours, puis de formes, puis d'objets.", en: "Convolutional networks (CNNs) recognise images by sliding a small filter (“kernel”) over the image: at each position, multiply the filter by the area it covers and sum. A filter [[1, -1]] reacts to vertical edges. The first layers of a CNN thus learn edge detectors on their own, then shapes, then objects." },
    example: "import numpy as np\nI = np.arange(9).reshape(3, 3)\nprint(I[0:2, 0:2])",
    task: { fr: "Écris convolution(image, noyau) : image et noyau sont des tableaux 2D ; renvoie la convolution « valide » (sans bord) : sortie[i][j] = somme(image[i:i+h, j:j+l] * noyau).", en: "Write convolution(image, noyau): image and kernel are 2D arrays; return the “valid” convolution (no padding): out[i][j] = sum(image[i:i+h, j:j+w] * kernel)." },
    starter: "import numpy as np\n\ndef convolution(image, noyau):\n    image, noyau = np.array(image, dtype=float), np.array(noyau, dtype=float)\n    h, l = noyau.shape\n    sortie = np.zeros((image.shape[0] - h + 1, image.shape[1] - l + 1))\n    # double boucle\n    return sortie\n",
    hint: { fr: "for i, for j : sortie[i, j] = (image[i:i+h, j:j+l] * noyau).sum()", en: "for i, for j: out[i, j] = (image[i:i+h, j:j+w] * kernel).sum()" },
    solution: "import numpy as np\n\ndef convolution(image, noyau):\n    image, noyau = np.array(image, dtype=float), np.array(noyau, dtype=float)\n    h, l = noyau.shape\n    sortie = np.zeros((image.shape[0] - h + 1, image.shape[1] - l + 1))\n    for i in range(sortie.shape[0]):\n        for j in range(sortie.shape[1]):\n            sortie[i, j] = (image[i:i + h, j:j + l] * noyau).sum()\n    return sortie",
    checks: ["np.allclose(convolution([[0, 0, 1, 1]], [[1, -1]]), [[0, -1, 0]])", "convolution(np.ones((5, 5)), np.ones((3, 3))).shape == (3, 3)", "np.allclose(convolution([[1, 2], [3, 4]], [[1, 0], [0, 1]]), [[5]])", "np.allclose(convolution(np.arange(9).reshape(3, 3), [[1]]), np.arange(9).reshape(3, 3))"],
  },
  {
    id: "dl-attention", lang: 'py', group: "dl-reseaux",
    packages: ["numpy"],
    title: { fr: "Attention : le cœur des Transformers", en: "Attention: the heart of Transformers" },
    explain: { fr: "Les grands modèles de langage reposent sur le mécanisme d'attention. Chaque élément (mot) pose une question (Q), les autres éléments offrent une clé (K) et une valeur (V). La pertinence = Q·Kᵀ / √d ; softmax la transforme en poids qui somment à 1 ; le résultat est la moyenne pondérée des valeurs : attention(Q, K, V) = softmax(Q·Kᵀ / √d) · V. d est la taille des vecteurs Q et K. Le softmax est appliqué sur chaque ligne.", en: "Large language models rely on the attention mechanism. Each element (word) asks a question (Q), the other elements offer a key (K) and a value (V). Relevance = Q·Kᵀ / √d; softmax turns it into weights summing to 1; the result is the weighted average of values: attention(Q, K, V) = softmax(Q·Kᵀ / √d) · V. d is the size of the Q and K vectors. Softmax applies on each row." },
    example: "import numpy as np\nQ = np.eye(2); K = np.eye(2)\nprint(Q @ K.T)",
    task: { fr: "Écris attention(Q, K, V) (tableaux 2D, une ligne par élément) : renvoie softmax(Q·Kᵀ/√d)·V avec softmax appliqué ligne par ligne.", en: "Write attention(Q, K, V) (2D arrays, one row per element): return softmax(Q·Kᵀ/√d)·V with softmax applied row by row." },
    starter: "import numpy as np\n\ndef attention(Q, K, V):\n    pass\n",
    hint: { fr: "scores = Q @ K.T / np.sqrt(Q.shape[1]) ; poids = exp(scores - max par ligne) / somme par ligne ; poids @ V", en: "scores = Q @ K.T / np.sqrt(Q.shape[1]); weights = exp(scores - row max) / row sum; weights @ V" },
    solution: "import numpy as np\n\ndef attention(Q, K, V):\n    Q, K, V = (np.array(a, dtype=float) for a in (Q, K, V))\n    scores = Q @ K.T / np.sqrt(Q.shape[1])\n    e = np.exp(scores - scores.max(axis=1, keepdims=True))\n    poids = e / e.sum(axis=1, keepdims=True)\n    return poids @ V",
    checks: ["np.allclose(attention([[0.0, 0.0]], [[1.0, 2.0], [3.0, 4.0]], [[10.0], [20.0]]), [[15.0]])", "attention(np.ones((3, 4)), np.ones((5, 4)), np.ones((5, 2))).shape == (3, 2)", "np.allclose(attention([[100.0, 0.0]], [[1.0, 0.0], [0.0, 1.0]], [[1.0], [9.0]]), [[1.0]], atol=1e-6)", "np.allclose(attention([[1.0, 0.0], [0.0, 1.0]], [[1.0, 0.0], [0.0, 1.0]], [[1.0, 0.0], [0.0, 1.0]]).sum(axis=1), 1.0)"],
  },
  {
    id: "dl-capstone", lang: 'py', group: "dl-reseaux",
    packages: ["numpy"],
    title: { fr: "Projet : ta première IA de A à Z", en: "Project: your first AI from A to Z" },
    explain: { fr: "Tu as tous les ingrédients : données, séparation entraînement/test, modèle, perte, descente de gradient, évaluation. Ici, de petites images 4×4 (aplaties en 16 nombres) contiennent soit une ligne horizontale (classe 0), soit une ligne verticale (classe 1), plus du bruit. À toi d'entraîner un classifieur et de montrer qu'il généralise à des images jamais vues.", en: "You have all the ingredients: data, train/test split, model, loss, gradient descent, evaluation. Here small 4×4 images (flattened into 16 numbers) contain either a horizontal line (class 0) or a vertical line (class 1), plus noise. Train a classifier and show it generalizes to unseen images." },
    example: "import numpy as np\nrng = np.random.default_rng(0)\nprint(rng.random((2, 2)).round(2))",
    task: { fr: "Écris entraine(X, y) qui renvoie une fonction predit(X) → tableau de 0/1. Elle doit dépasser 90 % d'exactitude sur des images de test jamais vues.", en: "Write entraine(X, y) returning a function predit(X) → array of 0/1. It must exceed 90% accuracy on unseen test images." },
    starter: "import numpy as np\n\ndef donnees(graine, n=200):\n    rng = np.random.default_rng(graine)\n    X, y = [], []\n    for _ in range(n):\n        img = np.zeros((4, 4))\n        c = int(rng.integers(0, 2))\n        k = int(rng.integers(0, 4))\n        if c == 0:\n            img[k, :] = 1\n        else:\n            img[:, k] = 1\n        img += rng.normal(0, 0.3, (4, 4))\n        X.append(img.ravel())\n        y.append(c)\n    return np.array(X), np.array(y)\n\ndef entraine(X, y):\n    # entraîne un modèle (régression logistique ou petit réseau)\n    def predit(Xn):\n        return np.zeros(len(Xn), dtype=int)\n    return predit\n",
    hint: { fr: "Une régression logistique sur 16 entrées suffit : reprends ta boucle de descente de gradient ; ou une couche cachée.", en: "A logistic regression on 16 inputs is enough: reuse your gradient descent loop; or add a hidden layer." },
    solution: "import numpy as np\n\ndef donnees(graine, n=200):\n    rng = np.random.default_rng(graine)\n    X, y = [], []\n    for _ in range(n):\n        img = np.zeros((4, 4))\n        c = int(rng.integers(0, 2))\n        k = int(rng.integers(0, 4))\n        if c == 0:\n            img[k, :] = 1\n        else:\n            img[:, k] = 1\n        img += rng.normal(0, 0.3, (4, 4))\n        X.append(img.ravel())\n        y.append(c)\n    return np.array(X), np.array(y)\n\ndef entraine(X, y):\n    X, y = np.array(X, dtype=float), np.array(y, dtype=float)\n    # deux couches : 16 -> 8 (tanh) -> 1 (sigmoïde)\n    rng = np.random.default_rng(0)\n    W1, b1 = rng.normal(0, 0.5, (16, 8)), np.zeros(8)\n    W2, b2 = rng.normal(0, 0.5, (8, 1)), np.zeros(1)\n    sig = lambda z: 1 / (1 + np.exp(-z))\n    for _ in range(1500):\n        h = np.tanh(X @ W1 + b1)\n        p = sig(h @ W2 + b2)\n        dz2 = p - y.reshape(-1, 1)\n        dW2, db2 = h.T @ dz2 / len(X), dz2.mean(axis=0)\n        dz1 = (dz2 @ W2.T) * (1 - h ** 2)\n        dW1, db1 = X.T @ dz1 / len(X), dz1.mean(axis=0)\n        W1 -= 0.5 * dW1; b1 -= 0.5 * db1; W2 -= 0.5 * dW2; b2 -= 0.5 * db2\n    def predit(Xn):\n        h = np.tanh(np.array(Xn, dtype=float) @ W1 + b1)\n        return (sig(h @ W2 + b2).ravel() > 0.5).astype(int)\n    return predit\n",
    checks: ["(lambda Xa, ya, Xt, yt: (entraine(Xa, ya)(Xt) == yt).mean() > 0.9)(*donnees(0), *donnees(1, 300))", "len(entraine(*donnees(2))(donnees(3, 10)[0])) == 10", "set(np.unique(entraine(*donnees(0))(donnees(4, 50)[0]))) <= {0, 1}"],
  },
]
