import type { Lesson } from './lessons'

// Lecture de code : l'élève prédit la sortie sans exécuter. Les réponses sont calculées par un vrai Python à la génération. Contenu original.
export const readLessons: Lesson[] = [
  {
    id: "py-lire-1", lang: 'py', group: 'py-lecture',
    title: { fr: "Lire : Boucle et condition", en: "Reading: Boucle et condition" },
    explain: { fr: "Lire du code est une compétence à part entière : prédis, sans lancer quoi que ce soit, ce que le programme affiche. Écris exactement la sortie, une ligne par affichage.", en: "Reading code is a skill of its own: predict, without running anything, what the program prints. Write the exact output, one line per print." },
    example: '',
    task: { fr: 'Que s\'affiche-t-il ?', en: 'What does it print?' },
    starter: '',
    hint: { fr: 'Déroule le programme à la main, ligne par ligne (le débogueur « Pas à pas » peut t\'aider à vérifier après coup).', en: 'Trace the program by hand, line by line (the “Step by step” debugger can help you check afterwards).' },
    solution: "1\n2\n4\n5",
    checks: [],
    predict: { code: "for i in range(1, 8):\n    if i % 3 == 0:\n        continue\n    if i > 5:\n        break\n    print(i)", answer: "1\n2\n4\n5", why: { fr: "continue saute le reste du tour ; break arrête la boucle. 3 est sauté ; à 6 (multiple de 3) on saute aussi ; à 7 on dépasse 5 donc stop avant d'imprimer.", en: "continue skips the rest of the turn; break stops the loop. 3 and 6 are skipped; at 7 we exceed 5 so we stop before printing." } },
  },
  {
    id: "py-lire-2", lang: 'py', group: 'py-lecture',
    title: { fr: "Lire : Tranches de liste", en: "Reading: Tranches de liste" },
    explain: { fr: "Lire du code est une compétence à part entière : prédis, sans lancer quoi que ce soit, ce que le programme affiche. Écris exactement la sortie, une ligne par affichage.", en: "Reading code is a skill of its own: predict, without running anything, what the program prints. Write the exact output, one line per print." },
    example: '',
    task: { fr: 'Que s\'affiche-t-il ?', en: 'What does it print?' },
    starter: '',
    hint: { fr: 'Déroule le programme à la main, ligne par ligne (le débogueur « Pas à pas » peut t\'aider à vérifier après coup).', en: 'Trace the program by hand, line by line (the “Step by step” debugger can help you check afterwards).' },
    solution: "[20, 30, 40]\n[40, 50]\n[10, 30, 50]",
    checks: [],
    predict: { code: "x = [10, 20, 30, 40, 50]\nprint(x[1:4])\nprint(x[-2:])\nprint(x[::2])", answer: "[20, 30, 40]\n[40, 50]\n[10, 30, 50]", why: { fr: "x[a:b] prend de a (inclus) à b (exclu). x[-2:] : les 2 derniers. x[::2] : un élément sur deux.", en: "x[a:b] takes from a (inclusive) to b (exclusive). x[-2:] : the last 2. x[::2] : every other item." } },
  },
  {
    id: "py-lire-3", lang: 'py', group: 'py-lecture',
    title: { fr: "Lire : Deux noms, une seule liste", en: "Reading: Deux noms, une seule liste" },
    explain: { fr: "Lire du code est une compétence à part entière : prédis, sans lancer quoi que ce soit, ce que le programme affiche. Écris exactement la sortie, une ligne par affichage.", en: "Reading code is a skill of its own: predict, without running anything, what the program prints. Write the exact output, one line per print." },
    example: '',
    task: { fr: 'Que s\'affiche-t-il ?', en: 'What does it print?' },
    starter: '',
    hint: { fr: 'Déroule le programme à la main, ligne par ligne (le débogueur « Pas à pas » peut t\'aider à vérifier après coup).', en: 'Trace the program by hand, line by line (the “Step by step” debugger can help you check afterwards).' },
    solution: "[1, 2, 3]\n[1, 2, 3, 4]",
    checks: [],
    predict: { code: "a = [1, 2]\nb = a\nb.append(3)\nc = a[:]\nc.append(4)\nprint(a)\nprint(c)", answer: "[1, 2, 3]\n[1, 2, 3, 4]", why: { fr: "b = a ne copie pas : b et a désignent la MÊME liste. a[:] fait une vraie copie : c évolue seul.", en: "b = a does not copy: b and a name the SAME list. a[:] makes a real copy: c evolves alone." } },
  },
  {
    id: "py-lire-4", lang: 'py', group: 'py-lecture',
    title: { fr: "Lire : Division entière et reste", en: "Reading: Division entière et reste" },
    explain: { fr: "Lire du code est une compétence à part entière : prédis, sans lancer quoi que ce soit, ce que le programme affiche. Écris exactement la sortie, une ligne par affichage.", en: "Reading code is a skill of its own: predict, without running anything, what the program prints. Write the exact output, one line per print." },
    example: '',
    task: { fr: 'Que s\'affiche-t-il ?', en: 'What does it print?' },
    starter: '',
    hint: { fr: 'Déroule le programme à la main, ligne par ligne (le débogueur « Pas à pas » peut t\'aider à vérifier après coup).', en: 'Trace the program by hand, line by line (the “Step by step” debugger can help you check afterwards).' },
    solution: "3 1\n-4 1",
    checks: [],
    predict: { code: "print(7 // 2, 7 % 2)\nprint(-7 // 2, -7 % 2)", answer: "3 1\n-4 1", why: { fr: "// arrondit vers le bas (pas vers zéro) : -7 // 2 vaut -4, et le reste garde le signe du diviseur : -7 % 2 vaut 1. Toujours : (a // b) * b + a % b == a.", en: "// rounds down (not toward zero): -7 // 2 is -4, and the remainder keeps the divisor's sign: -7 % 2 is 1. Always: (a // b) * b + a % b == a." } },
  },
  {
    id: "py-lire-5", lang: 'py', group: 'py-lecture',
    title: { fr: "Lire : Compréhension de liste", en: "Reading: Compréhension de liste" },
    explain: { fr: "Lire du code est une compétence à part entière : prédis, sans lancer quoi que ce soit, ce que le programme affiche. Écris exactement la sortie, une ligne par affichage.", en: "Reading code is a skill of its own: predict, without running anything, what the program prints. Write the exact output, one line per print." },
    example: '',
    task: { fr: 'Que s\'affiche-t-il ?', en: 'What does it print?' },
    starter: '',
    hint: { fr: 'Déroule le programme à la main, ligne par ligne (le débogueur « Pas à pas » peut t\'aider à vérifier après coup).', en: 'Trace the program by hand, line by line (the “Step by step” debugger can help you check afterwards).' },
    solution: "[1, 9, 25]\n{'un': 2, 'trois': 5}",
    checks: [],
    predict: { code: "print([x * x for x in range(6) if x % 2 == 1])\nprint({c: len(c) for c in [\"un\", \"trois\"]})", answer: "[1, 9, 25]\n{'un': 2, 'trois': 5}", why: { fr: "La condition filtre (x impair : 1, 3, 5) puis chaque x est élevé au carré. Le dictionnaire associe chaque mot à sa longueur.", en: "The condition filters (odd x: 1, 3, 5) then each x is squared. The dictionary maps each word to its length." } },
  },
  {
    id: "py-lire-6", lang: 'py', group: 'py-lecture',
    title: { fr: "Lire : Récursivité : l'ordre des affichages", en: "Reading: Récursivité : l'ordre des affichages" },
    explain: { fr: "Lire du code est une compétence à part entière : prédis, sans lancer quoi que ce soit, ce que le programme affiche. Écris exactement la sortie, une ligne par affichage.", en: "Reading code is a skill of its own: predict, without running anything, what the program prints. Write the exact output, one line per print." },
    example: '',
    task: { fr: 'Que s\'affiche-t-il ?', en: 'What does it print?' },
    starter: '',
    hint: { fr: 'Déroule le programme à la main, ligne par ligne (le débogueur « Pas à pas » peut t\'aider à vérifier après coup).', en: 'Trace the program by hand, line by line (the “Step by step” debugger can help you check afterwards).' },
    solution: "avant 2\navant 1\naprès 1\naprès 2",
    checks: [],
    predict: { code: "def f(n):\n    if n == 0:\n        return\n    print(\"avant\", n)\n    f(n - 1)\n    print(\"après\", n)\n\nf(2)", answer: "avant 2\navant 1\naprès 1\naprès 2", why: { fr: "L'appel f(2) affiche « avant 2 », appelle f(1) (qui affiche « avant 1 », appelle f(0) qui rend la main, puis « après 1 »), et seulement ensuite « après 2 ». Les « après » sortent à l'envers.", en: "The call f(2) prints “avant 2”, calls f(1) (which prints “avant 1”, calls f(0) which returns, then “après 1”), and only then “après 2”. The “après” lines come out reversed." } },
  },
  {
    id: "py-lire-7", lang: 'py', group: 'py-lecture',
    title: { fr: "Lire : while … else", en: "Reading: while … else" },
    explain: { fr: "Lire du code est une compétence à part entière : prédis, sans lancer quoi que ce soit, ce que le programme affiche. Écris exactement la sortie, une ligne par affichage.", en: "Reading code is a skill of its own: predict, without running anything, what the program prints. Write the exact output, one line per print." },
    example: '',
    task: { fr: 'Que s\'affiche-t-il ?', en: 'What does it print?' },
    starter: '',
    hint: { fr: 'Déroule le programme à la main, ligne par ligne (le débogueur « Pas à pas » peut t\'aider à vérifier après coup).', en: 'Trace the program by hand, line by line (the “Step by step” debugger can help you check afterwards).' },
    solution: "4",
    checks: [],
    predict: { code: "n = 10\nwhile n > 0:\n    n -= 3\n    if n == 4:\n        break\nelse:\n    print(\"fini\")\nprint(n)", answer: "4", why: { fr: "else d'une boucle s'exécute seulement si la boucle se termine SANS break. n passe par 7, 4 : à 4 on casse la boucle → pas de « fini ».", en: "A loop's else runs only if the loop ends WITHOUT break. n goes 7, 4: at 4 we break → no “fini”." } },
  },
  {
    id: "py-lire-8", lang: 'py', group: 'py-lecture',
    title: { fr: "Lire : Fermeture : une fonction qui se souvient", en: "Reading: Fermeture : une fonction qui se souvient" },
    explain: { fr: "Lire du code est une compétence à part entière : prédis, sans lancer quoi que ce soit, ce que le programme affiche. Écris exactement la sortie, une ligne par affichage.", en: "Reading code is a skill of its own: predict, without running anything, what the program prints. Write the exact output, one line per print." },
    example: '',
    task: { fr: 'Que s\'affiche-t-il ?', en: 'What does it print?' },
    starter: '',
    hint: { fr: 'Déroule le programme à la main, ligne par ligne (le débogueur « Pas à pas » peut t\'aider à vérifier après coup).', en: 'Trace the program by hand, line by line (the “Step by step” debugger can help you check afterwards).' },
    solution: "1 2 1",
    checks: [],
    predict: { code: "def compteur():\n    n = 0\n    def plus():\n        nonlocal n\n        n += 1\n        return n\n    return plus\n\na = compteur()\nb = compteur()\nprint(a(), a(), b())", answer: "1 2 1", why: { fr: "Chaque appel de compteur() crée son propre n. a garde le sien (1 puis 2), b a le sien (1).", en: "Each call to compteur() creates its own n. a keeps its own (1 then 2), b has its own (1)." } },
  },
  {
    id: "py-lire-9", lang: 'py', group: 'py-lecture',
    title: { fr: "Lire : try / except / finally", en: "Reading: try / except / finally" },
    explain: { fr: "Lire du code est une compétence à part entière : prédis, sans lancer quoi que ce soit, ce que le programme affiche. Écris exactement la sortie, une ligne par affichage.", en: "Reading code is a skill of its own: predict, without running anything, what the program prints. Write the exact output, one line per print." },
    example: '',
    task: { fr: 'Que s\'affiche-t-il ?', en: 'What does it print?' },
    starter: '',
    hint: { fr: 'Déroule le programme à la main, ligne par ligne (le débogueur « Pas à pas » peut t\'aider à vérifier après coup).', en: 'Trace the program by hand, line by line (the “Step by step” debugger can help you check afterwards).' },
    solution: "essai\nfin\n5\nessai\nerreur\nfin\n-1",
    checks: [],
    predict: { code: "def test(x):\n    try:\n        print(\"essai\")\n        return 10 // x\n    except ZeroDivisionError:\n        print(\"erreur\")\n        return -1\n    finally:\n        print(\"fin\")\n\nprint(test(2))\nprint(test(0))", answer: "essai\nfin\n5\nessai\nerreur\nfin\n-1", why: { fr: "finally s'exécute TOUJOURS, avant que return ne rende la valeur. Pour test(2) : essai, fin, puis 5. Pour test(0) : essai, erreur, fin, puis -1.", en: "finally ALWAYS runs, before return hands back the value. For test(2): essai, fin, then 5. For test(0): essai, erreur, fin, then -1." } },
  },
  {
    id: "py-lire-10", lang: 'py', group: 'py-lecture',
    title: { fr: "Lire : Tri stable avec clé", en: "Reading: Tri stable avec clé" },
    explain: { fr: "Lire du code est une compétence à part entière : prédis, sans lancer quoi que ce soit, ce que le programme affiche. Écris exactement la sortie, une ligne par affichage.", en: "Reading code is a skill of its own: predict, without running anything, what the program prints. Write the exact output, one line per print." },
    example: '',
    task: { fr: 'Que s\'affiche-t-il ?', en: 'What does it print?' },
    starter: '',
    hint: { fr: 'Déroule le programme à la main, ligne par ligne (le débogueur « Pas à pas » peut t\'aider à vérifier après coup).', en: 'Trace the program by hand, line by line (the “Step by step” debugger can help you check afterwards).' },
    solution: "['fig', 'kiwi', 'pomme', 'ananas', 'dattes']\n['ananas', 'dattes', 'pomme', 'kiwi', 'fig']",
    checks: [],
    predict: { code: "mots = [\"kiwi\", \"fig\", \"pomme\", \"ananas\", \"dattes\"]\nprint(sorted(mots, key=len))\nprint(sorted(mots, key=lambda m: (-len(m), m)))", answer: "['fig', 'kiwi', 'pomme', 'ananas', 'dattes']\n['ananas', 'dattes', 'pomme', 'kiwi', 'fig']", why: { fr: "sorted est STABLE : à longueur égale, l'ordre d'origine est gardé (ananas et dattes ont 6 lettres : ananas, qui était avant dans la liste, reste avant). Avec la clé (-len, m) : plus longs d'abord, puis ordre alphabétique.", en: "sorted is STABLE: for equal length the original order is kept (ananas and dattes both have 6 letters: ananas, earlier in the list, stays first). With the key (-len, m): longest first, then alphabetical." } },
  },
  {
    id: "py-lire-11", lang: 'py', group: 'py-lecture',
    title: { fr: "Lire : zip et enumerate", en: "Reading: zip et enumerate" },
    explain: { fr: "Lire du code est une compétence à part entière : prédis, sans lancer quoi que ce soit, ce que le programme affiche. Écris exactement la sortie, une ligne par affichage.", en: "Reading code is a skill of its own: predict, without running anything, what the program prints. Write the exact output, one line per print." },
    example: '',
    task: { fr: 'Que s\'affiche-t-il ?', en: 'What does it print?' },
    starter: '',
    hint: { fr: 'Déroule le programme à la main, ligne par ligne (le débogueur « Pas à pas » peut t\'aider à vérifier après coup).', en: 'Trace the program by hand, line by line (the “Step by step” debugger can help you check afterwards).' },
    solution: "1 a 12\n2 b 15",
    checks: [],
    predict: { code: "noms = [\"a\", \"b\", \"c\"]\nnotes = [12, 15]\nfor i, (n, v) in enumerate(zip(noms, notes), start=1):\n    print(i, n, v)", answer: "1 a 12\n2 b 15", why: { fr: "zip s'arrête au plus court (2 paires). enumerate(..., start=1) numérote à partir de 1.", en: "zip stops at the shortest (2 pairs). enumerate(..., start=1) numbers from 1." } },
  },
  {
    id: "py-lire-12", lang: 'py', group: 'py-lecture',
    title: { fr: "Lire : Chaînes : méthodes enchaînées", en: "Reading: Chaînes : méthodes enchaînées" },
    explain: { fr: "Lire du code est une compétence à part entière : prédis, sans lancer quoi que ce soit, ce que le programme affiche. Écris exactement la sortie, une ligne par affichage.", en: "Reading code is a skill of its own: predict, without running anything, what the program prints. Write the exact output, one line per print." },
    example: '',
    task: { fr: 'Que s\'affiche-t-il ?', en: 'What does it print?' },
    starter: '',
    hint: { fr: 'Déroule le programme à la main, ligne par ligne (le débogueur « Pas à pas » peut t\'aider à vérifier après coup).', en: 'Trace the program by hand, line by line (the “Step by step” debugger can help you check afterwards).' },
    solution: "['bonjour', 'le', 'monde']\nB L M",
    checks: [],
    predict: { code: "s = \"  Bonjour, Le Monde  \"\nprint(s.strip().lower().replace(\",\", \"\").split())\nprint(\" \".join(w[0] for w in s.split()))", answer: "['bonjour', 'le', 'monde']\nB L M", why: { fr: "strip retire les espaces, lower met en minuscules, replace retire la virgule, split découpe en mots. La 2e ligne prend la première lettre de chaque mot.", en: "strip removes spaces, lower lowercases, replace removes the comma, split cuts into words. The 2nd line takes each word's first letter." } },
  },
  {
    id: "py-lire-13", lang: 'py', group: 'py-lecture',
    title: { fr: "Lire : Valeur par défaut piégeuse", en: "Reading: Valeur par défaut piégeuse" },
    explain: { fr: "Lire du code est une compétence à part entière : prédis, sans lancer quoi que ce soit, ce que le programme affiche. Écris exactement la sortie, une ligne par affichage.", en: "Reading code is a skill of its own: predict, without running anything, what the program prints. Write the exact output, one line per print." },
    example: '',
    task: { fr: 'Que s\'affiche-t-il ?', en: 'What does it print?' },
    starter: '',
    hint: { fr: 'Déroule le programme à la main, ligne par ligne (le débogueur « Pas à pas » peut t\'aider à vérifier après coup).', en: 'Trace the program by hand, line by line (the “Step by step” debugger can help you check afterwards).' },
    solution: "[1]\n[1, 2]\n[3]",
    checks: [],
    predict: { code: "def ajoute(x, liste=[]):\n    liste.append(x)\n    return liste\n\nprint(ajoute(1))\nprint(ajoute(2))\nprint(ajoute(3, []))", answer: "[1]\n[1, 2]\n[3]", why: { fr: "La liste par défaut est créée UNE seule fois, à la définition de la fonction : elle est partagée entre les appels. Piège classique de Python : utiliser None puis créer la liste dans la fonction.", en: "The default list is created ONCE, when the function is defined: it is shared between calls. A classic Python trap: use None then create the list inside the function." } },
  },
]
