import type { Lesson } from './lessons'

// Parcours Neurones : intègre-et-tire à fuite, courbe fréquence-courant, règles de Hebb et d'Oja, STDP. Contenu original.
export const neuroLessons: Lesson[] = [
  {
    id: "neu-lif", lang: 'py', group: "neuro",
    title: { fr: "Un neurone qui s'allume : le modèle intègre-et-tire", en: "A neuron that fires: integrate-and-fire" },
    explain: { fr: "Un neurone accumule des charges électriques : sa TENSION v monte quand il reçoit du courant et redescend doucement vers sa valeur de repos (il « fuit »). Quand v atteint un SEUIL, il envoie une IMPULSION (un « pic ») puis repart du repos. C'est le modèle INTÈGRE-ET-TIRE À FUITE (LIF). On le simule pas à pas : v += dt · (−(v − repos) + I) / tau.", en: "A neuron accumulates electrical charge: its VOLTAGE v rises when it receives current and slowly decays back to rest (it “leaks”). When v reaches a THRESHOLD, it sends a SPIKE then restarts from rest. That is the LEAKY INTEGRATE-AND-FIRE (LIF) model. Simulate it step by step: v += dt · (−(v − rest) + I) / tau." },
    example: "v, dt, tau = 0.0, 0.1, 10.0\nfor _ in range(3):\n    v += dt * (-v + 2.0) / tau\nprint(round(v, 4))",
    task: { fr: "Écris simuler_lif(courant, duree=100, dt=0.1, tau=10.0, seuil=1.0, repos=0.0) → liste des instants des pics (en ms, arrondis à 6 décimales). À chaque pas k (de 0 à duree/dt − 1) : mets v à jour, puis si v ≥ seuil, note l'instant (k + 1)·dt et remets v au repos.", en: "Write simuler_lif(courant, duree=100, dt=0.1, tau=10.0, seuil=1.0, repos=0.0) → list of spike times (ms, rounded to 6 decimals). At each step k (0 to duree/dt − 1): update v, then if v ≥ seuil, record time (k + 1)·dt and reset v to rest." },
    starter: "def simuler_lif(courant, duree=100, dt=0.1, tau=10.0, seuil=1.0, repos=0.0):\n    pass\n",
    hint: { fr: "for k in range(int(round(duree / dt))) ; round((k + 1) * dt, 6).", en: "for k in range(int(round(duree / dt))); round((k + 1) * dt, 6)." },
    solution: "def simuler_lif(courant, duree=100, dt=0.1, tau=10.0, seuil=1.0, repos=0.0):\n    v = repos\n    pics = []\n    for k in range(int(round(duree / dt))):\n        v += dt * (-(v - repos) + courant) / tau\n        if v >= seuil:\n            pics.append(round((k + 1) * dt, 6))\n            v = repos\n    return pics",
    checks: ["simuler_lif(0.0) == []", "simuler_lif(0.9) == []", "len(simuler_lif(2.0)) > 0", "len(simuler_lif(3.0)) > len(simuler_lif(2.0))", "(lambda p: all(abs((b - a) - (p[1] - p[0])) < 0.11 for a, b in zip(p, p[1:])))(simuler_lif(2.0))", "abs(simuler_lif(2.0)[0] - 6.9) < 0.2"],
  },
  {
    id: "neu-frequence", lang: 'py', group: "neuro",
    title: { fr: "Plus de courant, plus de pics : la courbe fréquence-courant", en: "More current, more spikes: the frequency-current curve" },
    explain: { fr: "Le cerveau code l'intensité par la FRÉQUENCE des impulsions : un stimulus fort fait « tirer » le neurone plus souvent. Sous un courant minimal (le RHÉOBASE), il ne tire jamais. La théorie du modèle LIF donne la période entre deux pics : T = tau · ln(I / (I − seuil)) quand I > seuil. On compare la formule à la simulation.", en: "The brain encodes intensity by spike FREQUENCY: a strong stimulus makes the neuron “fire” more often. Below a minimal current (the RHEOBASE), it never fires. LIF theory gives the period between two spikes: T = tau · ln(I / (I − threshold)) when I > threshold. Compare the formula with the simulation." },
    example: "import math\nprint(round(10 * math.log(2 / (2 - 1)), 3))",
    task: { fr: "Le simulateur simuler_lif est fourni. Écris frequence(courant, duree=1000) → pics par seconde (duree en ms). Puis periode_theorique(courant, tau=10.0, seuil=1.0) → tau·ln(I/(I − seuil)) en ms, ou None si I ≤ seuil. Puis rheobase(courants) → le plus petit courant de la liste qui donne au moins un pic (None sinon).", en: "The simulator simuler_lif is provided. Write frequence(courant, duree=1000) → spikes per second (duree in ms). Then periode_theorique(courant, tau=10.0, seuil=1.0) → tau·ln(I/(I − seuil)) in ms, or None if I ≤ seuil. Then rheobase(courants) → the smallest current in the list giving at least one spike (None otherwise)." },
    starter: "def simuler_lif(courant, duree=100, dt=0.1, tau=10.0, seuil=1.0, repos=0.0):\n    v = repos\n    pics = []\n    for k in range(int(round(duree / dt))):\n        v += dt * (-(v - repos) + courant) / tau\n        if v >= seuil:\n            pics.append(round((k + 1) * dt, 6))\n            v = repos\n    return pics\n\nimport math\n\ndef frequence(courant, duree=1000):\n    pass\n\ndef periode_theorique(courant, tau=10.0, seuil=1.0):\n    pass\n\ndef rheobase(courants):\n    pass\n",
    hint: { fr: "frequence = len(simuler_lif(courant, duree)) * 1000 / duree. Pour rheobase, parcours sorted(courants).", en: "frequence = len(simuler_lif(courant, duree)) * 1000 / duree. For rheobase, loop over sorted(courants)." },
    solution: "def simuler_lif(courant, duree=100, dt=0.1, tau=10.0, seuil=1.0, repos=0.0):\n    v = repos\n    pics = []\n    for k in range(int(round(duree / dt))):\n        v += dt * (-(v - repos) + courant) / tau\n        if v >= seuil:\n            pics.append(round((k + 1) * dt, 6))\n            v = repos\n    return pics\n\nimport math\n\ndef frequence(courant, duree=1000):\n    return len(simuler_lif(courant, duree)) * 1000 / duree\n\ndef periode_theorique(courant, tau=10.0, seuil=1.0):\n    if courant <= seuil:\n        return None\n    return tau * math.log(courant / (courant - seuil))\n\ndef rheobase(courants):\n    for c in sorted(courants):\n        if simuler_lif(c, 300):\n            return c\n    return None",
    checks: ["frequence(0.5) == 0", "frequence(3.0) > frequence(2.0) > 0", "periode_theorique(1.0) is None and abs(periode_theorique(2.0) - 10 * math.log(2)) < 1e-9", "abs(1000 / frequence(2.0) - periode_theorique(2.0)) < 0.3", "rheobase([2.0, 0.5, 1.2, 0.8]) == 1.2", "rheobase([0.1, 0.2]) is None"],
  },
  {
    id: "neu-hebb", lang: 'py', group: "neuro",
    title: { fr: "Ce qui s'allume ensemble se lie : la règle de Hebb", en: "Fire together, wire together: Hebb's rule" },
    explain: { fr: "Comment le cerveau apprend-il ? Idée de Donald Hebb (1949) : quand un neurone d'entrée et un neurone de sortie sont actifs EN MÊME TEMPS, la connexion entre eux se renforce : w += eta · x · y. Seule, la règle fait grossir les poids sans limite ; la variante d'OJA ajoute un terme d'oubli (− eta · y² · w) qui les garde stables.", en: "How does the brain learn? Donald Hebb's idea (1949): when an input neuron and an output neuron are active AT THE SAME TIME, the connection between them strengthens: w += eta · x · y. Alone, the rule grows weights without bound; OJA's variant adds a forgetting term (− eta · y² · w) that keeps them stable." },
    example: "w, x, y, eta = [0.0, 0.0], [1, 0], 1, 0.5\nprint([wi + eta * xi * y for wi, xi in zip(w, x)])",
    task: { fr: "Écris hebb(w, x, y, eta) → nouvelle liste de poids (w + eta·x·y, élément par élément). Puis oja(w, x, eta) → calcule y = Σ w·x, puis w + eta·y·(x − y·w). Puis entrainer(w, exemples, eta, tours) → applique oja sur chaque exemple, tours fois, et renvoie w.", en: "Write hebb(w, x, y, eta) → new weight list (w + eta·x·y, element-wise). Then oja(w, x, eta) → compute y = Σ w·x, then w + eta·y·(x − y·w). Then entrainer(w, exemples, eta, tours) → apply oja on every example, tours times, and return w." },
    starter: "def hebb(w, x, y, eta):\n    pass\n\ndef oja(w, x, eta):\n    pass\n\ndef entrainer(w, exemples, eta, tours):\n    pass\n",
    hint: { fr: "Listes en compréhension avec zip(w, x). y = sum(a * b for a, b in zip(w, x)).", en: "List comprehensions with zip(w, x). y = sum(a * b for a, b in zip(w, x))." },
    solution: "def hebb(w, x, y, eta):\n    return [wi + eta * xi * y for wi, xi in zip(w, x)]\n\ndef oja(w, x, eta):\n    y = sum(a * b for a, b in zip(w, x))\n    return [wi + eta * y * (xi - y * wi) for wi, xi in zip(w, x)]\n\ndef entrainer(w, exemples, eta, tours):\n    for _ in range(tours):\n        for x in exemples:\n            w = oja(w, x, eta)\n    return w",
    checks: ["hebb([0.0, 0.0], [1, 0], 1, 0.5) == [0.5, 0.0]", "hebb([1.0], [1], 0, 0.5) == [1.0]", "oja([1.0, 0.0], [1, 0], 0.1) == [1.0, 0.0]", "(lambda w: abs(sum(v * v for v in w) - 1) < 0.05)(entrainer([0.3, 0.1], [[1, 1], [0.9, 1.1], [1.1, 0.9]], 0.05, 200))", "(lambda w: abs(w[0] - w[1]) < 0.05)(entrainer([0.3, 0.1], [[1, 1], [0.9, 1.1], [1.1, 0.9]], 0.05, 200))"],
  },
  {
    id: "neu-stdp", lang: 'py', group: "neuro",
    title: { fr: "L'ordre compte : la plasticité selon le moment des pics", en: "Order matters: spike-timing-dependent plasticity" },
    explain: { fr: "Les expériences montrent que l'ORDRE des impulsions compte. Si le neurone d'entrée tire JUSTE AVANT le neurone de sortie (il a pu le causer), la connexion se renforce ; s'il tire juste APRÈS, elle s'affaiblit. L'effet diminue quand l'écart grandit : c'est la STDP. Avec Δt = t_sortie − t_entrée : Δw = A+ · exp(−Δt / tau) si Δt > 0, −A− · exp(Δt / tau) si Δt < 0, 0 si Δt = 0.", en: "Experiments show that spike ORDER matters. If the input neuron fires JUST BEFORE the output neuron (it may have caused it), the connection strengthens; if it fires just AFTER, it weakens. The effect fades as the gap grows: that is STDP. With Δt = t_out − t_in: Δw = A+ · exp(−Δt / tau) if Δt > 0, −A− · exp(Δt / tau) if Δt < 0, 0 if Δt = 0." },
    example: "import math\nprint(round(0.01 * math.exp(-5 / 20), 5))",
    task: { fr: "Écris delta_w(dt, a_plus=0.01, a_moins=0.012, tau=20.0) → la variation de poids. Puis appliquer(w, pics_entree, pics_sortie, wmin=0.0, wmax=1.0) → somme les delta_w de toutes les paires (entrée, sortie), ajoute à w, et borne le résultat entre wmin et wmax.", en: "Write delta_w(dt, a_plus=0.01, a_moins=0.012, tau=20.0) → the weight change. Then appliquer(w, pics_entree, pics_sortie, wmin=0.0, wmax=1.0) → sum delta_w over every (input, output) pair, add to w, and clamp between wmin and wmax." },
    starter: "import math\n\ndef delta_w(dt, a_plus=0.01, a_moins=0.012, tau=20.0):\n    pass\n\ndef appliquer(w, pics_entree, pics_sortie, wmin=0.0, wmax=1.0):\n    pass\n",
    hint: { fr: "Δt = ts − te pour chaque paire. Borner : max(wmin, min(wmax, w)).", en: "Δt = ts − te for each pair. Clamp: max(wmin, min(wmax, w))." },
    solution: "import math\n\ndef delta_w(dt, a_plus=0.01, a_moins=0.012, tau=20.0):\n    if dt > 0:\n        return a_plus * math.exp(-dt / tau)\n    if dt < 0:\n        return -a_moins * math.exp(dt / tau)\n    return 0.0\n\ndef appliquer(w, pics_entree, pics_sortie, wmin=0.0, wmax=1.0):\n    for te in pics_entree:\n        for ts in pics_sortie:\n            w += delta_w(ts - te)\n    return max(wmin, min(wmax, w))",
    checks: ["delta_w(0) == 0", "delta_w(5) > 0 and delta_w(-5) < 0", "delta_w(1) > delta_w(10) > 0", "abs(delta_w(20) - 0.01 * math.exp(-1)) < 1e-12", "appliquer(0.5, [10, 30], [12, 32]) > 0.5", "appliquer(0.5, [12, 32], [10, 30]) < 0.5", "appliquer(0.999, [0] * 50, [1] * 50) == 1.0"],
  },
]
