import type { Lesson } from './lessons'

// Parcours Programmation, partie Python. Contenu original (progression inspirée de la forme des cours ouverts publics, rien de copié).
// Les vérifications sont des expressions Python évaluées après le code de l'élève ; `__out` = texte affiché par print().
export const pyLessons: Lesson[] = [
  {
    id: 'py-print', lang: 'py', group: 'py-bases',
    title: { fr: 'Python : afficher', en: 'Python: print' },
    explain: {
      fr: "Python lit ton programme ligne par ligne. print(...) affiche du texte. Le texte s'écrit entre guillemets.",
      en: 'Python reads your program line by line. print(...) shows text. Text goes between quotes.',
    },
    example: 'print("Bonjour le monde")',
    task: { fr: 'Affiche exactement : Bonjour Finjaro', en: 'Print exactly: Bonjour Finjaro' },
    starter: '# écris ton code ici\n',
    hint: { fr: 'Copie l’exemple et change le texte.', en: 'Copy the example and change the text.' },
    solution: 'print("Bonjour Finjaro")',
    checks: ['__out.strip() == "Bonjour Finjaro"'],
  },
  {
    id: 'py-vars', lang: 'py', group: 'py-bases',
    title: { fr: 'Variables et types', en: 'Variables and types' },
    explain: {
      fr: "Une variable garde une valeur sous un nom : age = 30. Python a des types : entiers (int), décimaux (float), texte (str), vrai/faux (bool). type(x) donne le type.",
      en: 'A variable keeps a value under a name: age = 30. Python has types: integers (int), decimals (float), text (str), true/false (bool). type(x) gives the type.',
    },
    example: 'prenom = "Beau"\nage = 30\nprint(prenom, age + 1)\nprint(type(age))',
    task: { fr: 'Crée une variable total égale à 12 + 8, puis affiche-la.', en: 'Create a variable total equal to 12 + 8, then print it.' },
    starter: 'total = \n',
    hint: { fr: 'total = 12 + 8 puis print(total).', en: 'total = 12 + 8 then print(total).' },
    solution: 'total = 12 + 8\nprint(total)',
    checks: ['total == 20', '__out.strip() == "20"'],
  },
  {
    id: 'py-str', lang: 'py', group: 'py-bases',
    title: { fr: 'Texte et fonctions', en: 'Text and functions' },
    explain: {
      fr: 'Une fonction se définit avec def et renvoie une valeur avec return. Un f-string insère des valeurs dans un texte : f"Bonjour {prenom}".',
      en: 'A function is defined with def and returns a value with return. An f-string inserts values in text: f"Hello {name}".',
    },
    example: 'def double(n):\n    return n * 2\n\nprint(double(21))',
    task: { fr: 'Écris salutation(prenom) qui renvoie « Bonjour » suivi d’un espace et du prénom.', en: 'Write salutation(prenom) returning “Bonjour”, a space, then the name.' },
    starter: 'def salutation(prenom):\n    pass\n',
    hint: { fr: 'return f"Bonjour {prenom}"', en: 'return f"Bonjour {prenom}"' },
    solution: 'def salutation(prenom):\n    return f"Bonjour {prenom}"',
    checks: ['salutation("Amina") == "Bonjour Amina"', 'salutation("Bruno") == "Bonjour Bruno"'],
  },
  {
    id: 'py-cond', lang: 'py', group: 'py-bases',
    title: { fr: 'Conditions', en: 'Conditions' },
    explain: {
      fr: "if / elif / else choisissent un chemin. En Python l'indentation (4 espaces) fait partie du programme : elle délimite le bloc.",
      en: 'if / elif / else choose a path. In Python indentation (4 spaces) is part of the program: it marks the block.',
    },
    example: 'def mention(note):\n    if note >= 10:\n        return "admis"\n    else:\n        return "refusé"',
    task: { fr: 'Écris signe(n) : "positif" si n > 0, "negatif" sinon.', en: 'Write signe(n): "positif" if n > 0, "negatif" otherwise.' },
    starter: 'def signe(n):\n    pass\n',
    hint: { fr: 'if n > 0: return "positif" puis else: return "negatif".', en: 'if n > 0: return "positif" then else: return "negatif".' },
    solution: 'def signe(n):\n    if n > 0:\n        return "positif"\n    else:\n        return "negatif"',
    checks: ['signe(5) == "positif"', 'signe(-3) == "negatif"', 'signe(0) == "negatif"'],
  },
  {
    id: 'py-loops', lang: 'py', group: 'py-bases',
    title: { fr: 'Boucles', en: 'Loops' },
    explain: {
      fr: 'for i in range(n) répète n fois, avec i = 0, 1, … n-1. range(1, n + 1) va de 1 à n. while répète tant qu’une condition est vraie.',
      en: 'for i in range(n) repeats n times, with i = 0, 1, … n-1. range(1, n + 1) goes from 1 to n. while repeats as long as a condition holds.',
    },
    example: 'for i in range(1, 4):\n    print("Tour", i)',
    task: { fr: 'Écris somme(n) qui renvoie 1 + 2 + … + n.', en: 'Write somme(n) returning 1 + 2 + … + n.' },
    starter: 'def somme(n):\n    total = 0\n    # boucle ici\n    return total\n',
    hint: { fr: 'for i in range(1, n + 1): total += i', en: 'for i in range(1, n + 1): total += i' },
    solution: 'def somme(n):\n    total = 0\n    for i in range(1, n + 1):\n        total += i\n    return total',
    checks: ['somme(3) == 6', 'somme(10) == 55', 'somme(0) == 0'],
  },
  {
    id: 'py-lists', lang: 'py', group: 'py-bases',
    title: { fr: 'Listes', en: 'Lists' },
    explain: {
      fr: 'Une liste garde plusieurs valeurs dans l’ordre : [3, 1, 2]. liste[0] est le premier élément ; append ajoute à la fin ; len donne la taille. Une compréhension de liste construit une liste en une ligne : [x * 2 for x in liste].',
      en: 'A list keeps several values in order: [3, 1, 2]. liste[0] is the first item; append adds at the end; len gives the size. A list comprehension builds a list in one line: [x * 2 for x in liste].',
    },
    example: 'nombres = [1, 2, 3]\nnombres.append(4)\nprint([x * 2 for x in nombres])',
    task: { fr: 'Écris carres(liste) qui renvoie la liste des carrés : [1, 2, 3] → [1, 4, 9].', en: 'Write carres(liste) returning the squares: [1, 2, 3] → [1, 4, 9].' },
    starter: 'def carres(liste):\n    pass\n',
    hint: { fr: 'return [x * x for x in liste]', en: 'return [x * x for x in liste]' },
    solution: 'def carres(liste):\n    return [x * x for x in liste]',
    checks: ['carres([1, 2, 3]) == [1, 4, 9]', 'carres([]) == []', 'carres([-2]) == [4]'],
  },
  {
    id: 'py-dict', lang: 'py', group: 'py-bases',
    title: { fr: 'Dictionnaires', en: 'Dictionaries' },
    explain: {
      fr: 'Un dictionnaire associe des clés à des valeurs : {"a": 2}. d["a"] lit ; d["b"] = 1 écrit ; "a" in d teste la présence ; d.get("z", 0) lit avec une valeur par défaut.',
      en: 'A dictionary maps keys to values: {"a": 2}. d["a"] reads; d["b"] = 1 writes; "a" in d tests presence; d.get("z", 0) reads with a default.',
    },
    example: 'ages = {"Amina": 30}\nages["Bruno"] = 25\nprint(ages.get("Zoe", 0))',
    task: { fr: 'Écris compter(mots) qui renvoie combien de fois chaque mot apparaît : ["a","b","a"] → {"a": 2, "b": 1}.', en: 'Write compter(mots) returning how many times each word appears: ["a","b","a"] → {"a": 2, "b": 1}.' },
    starter: 'def compter(mots):\n    resultat = {}\n    # remplis resultat\n    return resultat\n',
    hint: { fr: 'resultat[m] = resultat.get(m, 0) + 1 pour chaque mot m.', en: 'resultat[m] = resultat.get(m, 0) + 1 for each word m.' },
    solution: 'def compter(mots):\n    resultat = {}\n    for m in mots:\n        resultat[m] = resultat.get(m, 0) + 1\n    return resultat',
    checks: ['compter(["a", "b", "a"]) == {"a": 2, "b": 1}', 'compter([]) == {}'],
  },
  {
    id: 'py-recursion', lang: 'py', group: 'py-algo',
    title: { fr: 'Récursivité', en: 'Recursion' },
    explain: {
      fr: 'Une fonction récursive s’appelle elle-même sur un problème plus petit. Il faut toujours un cas de base qui s’arrête. Exemple : 4! = 4 × 3!, et 0! = 1.',
      en: 'A recursive function calls itself on a smaller problem. It always needs a base case that stops. Example: 4! = 4 × 3!, and 0! = 1.',
    },
    example: 'def compte_a_rebours(n):\n    if n == 0:\n        return\n    print(n)\n    compte_a_rebours(n - 1)',
    task: { fr: 'Écris factorielle(n) de façon récursive.', en: 'Write factorielle(n) recursively.' },
    starter: 'def factorielle(n):\n    pass\n',
    hint: { fr: 'Si n == 0 renvoie 1, sinon n * factorielle(n - 1).', en: 'If n == 0 return 1, else n * factorielle(n - 1).' },
    solution: 'def factorielle(n):\n    if n == 0:\n        return 1\n    return n * factorielle(n - 1)',
    checks: ['factorielle(0) == 1', 'factorielle(5) == 120', 'factorielle(10) == 3628800'],
  },
  {
    id: 'py-search', lang: 'py', group: 'py-algo',
    title: { fr: 'Recherche dichotomique', en: 'Binary search' },
    explain: {
      fr: 'Dans une liste TRIÉE, on peut chercher en coupant l’intervalle en deux à chaque pas : au lieu de n comparaisons, il en faut environ log₂(n). On compare avec le milieu, puis on garde la moitié gauche ou droite.',
      en: 'In a SORTED list you can search by halving the range at each step: instead of n comparisons you need about log₂(n). Compare with the middle, then keep the left or right half.',
    },
    example: 'milieu = (bas + haut) // 2   # division entière',
    task: { fr: 'Écris recherche(liste_triee, x) : renvoie l’indice de x, ou -1 s’il est absent.', en: 'Write recherche(liste_triee, x): return the index of x, or -1 if absent.' },
    starter: 'def recherche(liste_triee, x):\n    bas, haut = 0, len(liste_triee) - 1\n    # tant que bas <= haut ...\n    return -1\n',
    hint: { fr: 'while bas <= haut: calcule le milieu ; si égal, renvoie-le ; si trop petit, bas = milieu + 1 ; sinon haut = milieu - 1.', en: 'while bas <= haut: compute the middle; if equal return it; if too small, bas = milieu + 1; else haut = milieu - 1.' },
    solution: 'def recherche(liste_triee, x):\n    bas, haut = 0, len(liste_triee) - 1\n    while bas <= haut:\n        milieu = (bas + haut) // 2\n        if liste_triee[milieu] == x:\n            return milieu\n        if liste_triee[milieu] < x:\n            bas = milieu + 1\n        else:\n            haut = milieu - 1\n    return -1',
    checks: ['recherche([1, 3, 5, 7, 9], 7) == 3', 'recherche([1, 3, 5, 7, 9], 1) == 0', 'recherche([1, 3, 5, 7, 9], 4) == -1', 'recherche([], 1) == -1', 'recherche(list(range(0, 2000000, 2)), 1999998) == 999999'],
  },
  {
    id: 'py-sort', lang: 'py', group: 'py-algo',
    title: { fr: 'Tri par sélection', en: 'Selection sort' },
    explain: {
      fr: 'Le tri par sélection cherche le plus petit élément du reste de la liste et le place en tête, puis recommence. Il fait environ n² comparaisons : on dit qu’il est en O(n²).',
      en: 'Selection sort finds the smallest item in the rest of the list and puts it first, then repeats. It does about n² comparisons: we say it is O(n²).',
    },
    example: 'liste = [3, 1, 2]\nliste[0], liste[1] = liste[1], liste[0]   # échange',
    task: { fr: 'Écris tri(liste) qui renvoie une nouvelle liste triée, SANS utiliser sorted() ni .sort().', en: 'Write tri(liste) returning a new sorted list WITHOUT using sorted() or .sort().' },
    starter: 'def tri(liste):\n    l = list(liste)\n    # pour chaque position i, cherche le plus petit à partir de i\n    return l\n',
    hint: { fr: 'Pour i de 0 à len-1 : trouve j (≥ i) du minimum, échange l[i] et l[j].', en: 'For i from 0 to len-1: find j (≥ i) of the minimum, swap l[i] and l[j].' },
    solution: 'def tri(liste):\n    l = list(liste)\n    for i in range(len(l)):\n        j = i\n        for k in range(i + 1, len(l)):\n            if l[k] < l[j]:\n                j = k\n        l[i], l[j] = l[j], l[i]\n    return l',
    checks: ['tri([3, 1, 2]) == [1, 2, 3]', 'tri([]) == []', 'tri([5, 5, 1]) == [1, 5, 5]', 'tri([9, 8, 7, 6, 5, 4]) == [4, 5, 6, 7, 8, 9]', '(l0 := [2, 1], tri(l0) == [1, 2] and l0 == [2, 1])[-1]'],
  },
  {
    id: 'py-stack', lang: 'py', group: 'py-algo',
    title: { fr: 'Piles', en: 'Stacks' },
    explain: {
      fr: 'Une pile est une structure « dernier arrivé, premier sorti » : on empile (append) et on dépile (pop). Une liste Python s’en sert très bien. Les piles servent à vérifier des parenthèses, annuler une action, parcourir un arbre…',
      en: 'A stack is “last in, first out”: you push (append) and pop. A Python list works well. Stacks check parentheses, undo actions, walk trees…',
    },
    example: 'pile = []\npile.append("(")\npile.pop()',
    task: { fr: 'Écris equilibre(s) : True si les parenthèses ( ) de s sont bien fermées dans le bon ordre.', en: 'Write equilibre(s): True if the parentheses ( ) in s are correctly closed in order.' },
    starter: 'def equilibre(s):\n    pile = []\n    # parcours chaque caractère\n    return len(pile) == 0\n',
    hint: { fr: '"(" → append ; ")" → si la pile est vide renvoie False, sinon pop.', en: '"(" → append; ")" → if the stack is empty return False, else pop.' },
    solution: 'def equilibre(s):\n    pile = []\n    for c in s:\n        if c == "(":\n            pile.append(c)\n        elif c == ")":\n            if not pile:\n                return False\n            pile.pop()\n    return len(pile) == 0',
    checks: ['equilibre("(())") == True', 'equilibre("(()") == False', 'equilibre("())(") == False', 'equilibre("") == True', 'equilibre("a(b)c") == True'],
  },
  {
    id: 'py-set', lang: 'py', group: 'py-algo',
    title: { fr: 'Ensembles et coût', en: 'Sets and cost' },
    explain: {
      fr: 'Un ensemble (set) teste « x est-il dedans ? » en temps presque constant, alors qu’une liste doit tout parcourir. Choisir la bonne structure change le coût : comparer chaque paire de n éléments coûte n², passer par un ensemble coûte n.',
      en: 'A set tests “is x inside?” in near-constant time, while a list must scan everything. Choosing the right structure changes the cost: comparing every pair of n items costs n², using a set costs n.',
    },
    example: 'vus = set()\nvus.add(3)\nprint(3 in vus)',
    task: { fr: 'Écris a_doublons(liste) : True si un élément apparaît deux fois. Doit rester rapide sur 200 000 éléments.', en: 'Write a_doublons(liste): True if an item appears twice. It must stay fast on 200,000 items.' },
    starter: 'def a_doublons(liste):\n    vus = set()\n    # ...\n    return False\n',
    hint: { fr: 'Pour chaque x : s’il est dans vus renvoie True, sinon vus.add(x).', en: 'For each x: if it is in vus return True, else vus.add(x).' },
    solution: 'def a_doublons(liste):\n    vus = set()\n    for x in liste:\n        if x in vus:\n            return True\n        vus.add(x)\n    return False',
    checks: ['a_doublons([1, 2, 3]) == False', 'a_doublons([1, 2, 1]) == True', 'a_doublons([]) == False', 'a_doublons(list(range(200000))) == False', 'a_doublons(list(range(200000)) + [5]) == True'],
  },
  {
    id: 'py-memo', lang: 'py', group: 'py-algo',
    title: { fr: 'Mémoïsation', en: 'Memoization' },
    explain: {
      fr: 'Calculer fibonacci(n) = fibonacci(n-1) + fibonacci(n-2) de façon naïve refait les mêmes calculs un nombre exponentiel de fois. En gardant les résultats déjà calculés dans un dictionnaire, chaque valeur n’est calculée qu’une fois.',
      en: 'Computing fibonacci(n) = fibonacci(n-1) + fibonacci(n-2) naively repeats the same work exponentially often. Keeping computed results in a dictionary computes each value only once.',
    },
    example: 'cache = {}\ndef f(n):\n    if n not in cache:\n        cache[n] = ...  # calcul\n    return cache[n]',
    task: { fr: 'Écris fibonacci(n) (0, 1, 1, 2, 3, 5…) avec un cache : fibonacci(80) doit répondre tout de suite.', en: 'Write fibonacci(n) (0, 1, 1, 2, 3, 5…) with a cache: fibonacci(80) must answer immediately.' },
    starter: 'cache = {}\n\ndef fibonacci(n):\n    pass\n',
    hint: { fr: 'Cas de base : n < 2 → n. Sinon calcule, range dans cache[n], renvoie cache[n].', en: 'Base case: n < 2 → n. Otherwise compute, store in cache[n], return cache[n].' },
    solution: 'cache = {}\n\ndef fibonacci(n):\n    if n < 2:\n        return n\n    if n not in cache:\n        cache[n] = fibonacci(n - 1) + fibonacci(n - 2)\n    return cache[n]',
    checks: ['fibonacci(0) == 0', 'fibonacci(1) == 1', 'fibonacci(10) == 55', 'fibonacci(80) == 23416728348467685'],
  },
  {
    id: 'py-class', lang: 'py', group: 'py-algo',
    title: { fr: 'Classes', en: 'Classes' },
    explain: {
      fr: 'Une classe regroupe des données et des actions. __init__ prépare un nouvel objet ; self désigne l’objet lui-même. Chaque objet a ses propres valeurs.',
      en: 'A class groups data and actions. __init__ sets up a new object; self is the object itself. Each object has its own values.',
    },
    example: 'class Chien:\n    def __init__(self, nom):\n        self.nom = nom\n    def parle(self):\n        return self.nom + " aboie"',
    task: { fr: 'Écris une classe Compteur : valeur commence à 0 ; la méthode incremente() ajoute 1.', en: 'Write a class Compteur: valeur starts at 0; the method incremente() adds 1.' },
    starter: 'class Compteur:\n    pass\n',
    hint: { fr: 'Dans __init__ : self.valeur = 0. Dans incremente : self.valeur += 1.', en: 'In __init__: self.valeur = 0. In incremente: self.valeur += 1.' },
    solution: 'class Compteur:\n    def __init__(self):\n        self.valeur = 0\n\n    def incremente(self):\n        self.valeur += 1',
    checks: ['Compteur().valeur == 0', '(c := Compteur(), c.incremente(), c.incremente(), c.valeur)[-1] == 2', '(a := Compteur(), b := Compteur(), a.incremente(), b.valeur)[-1] == 0'],
  },

  {
    id: 'py-text', lang: 'py', group: 'py-bases',
    title: { fr: 'Traiter du texte', en: 'Working with text' },
    explain: {
      fr: 'Un texte se découpe avec split() (en mots), se recolle avec " ".join(liste), se met en minuscules avec lower(). Une liste se retourne avec liste[::-1].',
      en: 'Text is cut with split() (into words), joined back with " ".join(list), lowercased with lower(). A list is reversed with list[::-1].',
    },
    example: 'mots = "un deux trois".split()\nprint(mots)\nprint(" ".join(mots))',
    task: { fr: 'Écris inverser_mots(phrase) : "un deux trois" → "trois deux un".', en: 'Write inverser_mots(phrase): "un deux trois" → "trois deux un".' },
    starter: 'def inverser_mots(phrase):\n    pass\n',
    hint: { fr: 'return " ".join(phrase.split()[::-1])', en: 'return " ".join(phrase.split()[::-1])' },
    solution: 'def inverser_mots(phrase):\n    return " ".join(phrase.split()[::-1])',
    checks: ['inverser_mots("un deux trois") == "trois deux un"', 'inverser_mots("seul") == "seul"', 'inverser_mots("") == ""'],
  },
  {
    id: 'py-sortkey', lang: 'py', group: 'py-bases',
    title: { fr: 'Tuples et tri avec clé', en: 'Tuples and key sorting' },
    explain: {
      fr: 'Un tuple est une liste figée : ("Amina", 30). sorted(liste, key=...) trie selon un critère que tu choisis ; lambda p: p[1] est une mini-fonction qui renvoie le 2e élément.',
      en: 'A tuple is a frozen list: ("Amina", 30). sorted(list, key=...) sorts by a criterion you choose; lambda p: p[1] is a tiny function returning the 2nd item.',
    },
    example: 'gens = [("Amina", 30), ("Bruno", 25)]\nprint(sorted(gens, key=lambda p: p[1]))',
    task: { fr: 'Écris plus_jeune(gens) : renvoie le nom de la personne la plus jeune dans une liste de (nom, age).', en: 'Write plus_jeune(gens): return the name of the youngest person in a list of (name, age).' },
    starter: 'def plus_jeune(gens):\n    pass\n',
    hint: { fr: 'sorted(gens, key=lambda p: p[1])[0][0]', en: 'sorted(gens, key=lambda p: p[1])[0][0]' },
    solution: 'def plus_jeune(gens):\n    return sorted(gens, key=lambda p: p[1])[0][0]',
    checks: ['plus_jeune([("Amina", 30), ("Bruno", 25)]) == "Bruno"', 'plus_jeune([("Zoe", 9)]) == "Zoe"'],
  },
  {
    id: 'py-graph', lang: 'py', group: 'py-algo',
    title: { fr: 'Graphes : parcours en largeur', en: 'Graphs: breadth-first search' },
    explain: {
      fr: 'Un graphe relie des sommets par des arêtes ; on le range dans un dictionnaire : {"A": ["B", "C"]}. Le parcours en largeur visite d’abord les voisins, puis les voisins des voisins, avec une file : il trouve le plus court chemin en nombre d’arêtes.',
      en: 'A graph links vertices with edges; store it in a dictionary: {"A": ["B", "C"]}. Breadth-first search visits neighbours first, then their neighbours, using a queue: it finds the shortest path in number of edges.',
    },
    example: 'file = [("A", 0)]\nvus = {"A"}\nsommet, d = file.pop(0)',
    task: { fr: 'Écris distance(graphe, depart, arrivee) : nombre minimum d’arêtes, ou -1 si aucun chemin.', en: 'Write distance(graphe, depart, arrivee): minimum number of edges, or -1 if no path.' },
    starter: 'def distance(graphe, depart, arrivee):\n    file = [(depart, 0)]\n    vus = {depart}\n    # tant que la file n’est pas vide ...\n    return -1\n',
    hint: { fr: 'Sors (sommet, d) de la file ; si c’est l’arrivée renvoie d ; ajoute chaque voisin non vu avec d + 1.', en: 'Pop (vertex, d) from the queue; if it is the target return d; push each unseen neighbour with d + 1.' },
    solution: 'def distance(graphe, depart, arrivee):\n    file = [(depart, 0)]\n    vus = {depart}\n    while file:\n        sommet, d = file.pop(0)\n        if sommet == arrivee:\n            return d\n        for v in graphe.get(sommet, []):\n            if v not in vus:\n                vus.add(v)\n                file.append((v, d + 1))\n    return -1',
    checks: ['distance({"A": ["B", "C"], "B": ["D"], "C": ["D"], "D": []}, "A", "D") == 2', 'distance({"A": ["B"], "B": []}, "A", "A") == 0', 'distance({"A": ["B"], "B": [], "C": []}, "A", "C") == -1', 'distance({"A": ["B", "C"], "B": ["A"], "C": ["A", "D"], "D": []}, "B", "D") == 3'],
  },
  {
    id: 'py-linked', lang: 'py', group: 'py-algo',
    title: { fr: 'Liste chaînée', en: 'Linked list' },
    explain: {
      fr: 'Une liste chaînée est faite de maillons : chacun garde une valeur et le maillon suivant. Ajouter en tête est immédiat (pas de décalage), mais accéder au k-ième élément oblige à parcourir la chaîne.',
      en: 'A linked list is made of nodes: each keeps a value and the next node. Adding at the head is instant (no shifting), but reaching the k-th item means walking the chain.',
    },
    example: 'class Noeud:\n    def __init__(self, valeur, suivant=None):\n        self.valeur = valeur\n        self.suivant = suivant',
    task: { fr: 'Complète la classe Liste : ajoute(x) met x en tête ; en_liste() renvoie les valeurs de la tête à la fin sous forme de liste Python.', en: 'Complete class Liste: ajoute(x) puts x at the head; en_liste() returns the values from head to end as a Python list.' },
    starter: 'class Noeud:\n    def __init__(self, valeur, suivant=None):\n        self.valeur = valeur\n        self.suivant = suivant\n\nclass Liste:\n    def __init__(self):\n        self.tete = None\n\n    def ajoute(self, x):\n        pass\n\n    def en_liste(self):\n        pass\n',
    hint: { fr: 'ajoute : self.tete = Noeud(x, self.tete). en_liste : parcours n = self.tete ; tant que n : ajoute n.valeur, n = n.suivant.', en: 'ajoute: self.tete = Noeud(x, self.tete). en_liste: walk n = self.tete; while n: append n.valeur, n = n.suivant.' },
    solution: 'class Noeud:\n    def __init__(self, valeur, suivant=None):\n        self.valeur = valeur\n        self.suivant = suivant\n\nclass Liste:\n    def __init__(self):\n        self.tete = None\n\n    def ajoute(self, x):\n        self.tete = Noeud(x, self.tete)\n\n    def en_liste(self):\n        res = []\n        n = self.tete\n        while n:\n            res.append(n.valeur)\n            n = n.suivant\n        return res',
    checks: ['Liste().en_liste() == []', '(l := Liste(), l.ajoute(1), l.ajoute(2), l.ajoute(3), l.en_liste())[-1] == [3, 2, 1]'],
  },
  {
    id: 'py-projet-texte', lang: 'py', group: 'py-projets',
    title: { fr: 'Projet 1 : analyseur de texte', en: 'Project 1: text analyzer' },
    explain: {
      fr: 'Premier mini-projet : tu assembles plusieurs notions (texte, listes, dictionnaires, tri). Découpe le texte en mots en minuscules, compte-les, et donne trois résultats.',
      en: 'First mini-project: you combine several notions (text, lists, dictionaries, sorting). Split the text into lowercase words, count them, and return three results.',
    },
    example: 'mots = "Le chat et le chien".lower().split()',
    task: { fr: 'Écris analyse(texte) : renvoie {"mots": nombre de mots, "uniques": nombre de mots différents, "frequent": le mot le plus fréquent (en cas d’égalité, le premier par ordre alphabétique)}.', en: 'Write analyse(texte): return {"mots": word count, "uniques": distinct words, "frequent": the most frequent word (ties: first alphabetically)}.' },
    starter: 'def analyse(texte):\n    pass\n',
    hint: { fr: 'Compte avec un dictionnaire ; pour le plus fréquent : min(compte, key=lambda m: (-compte[m], m)).', en: 'Count with a dictionary; for the most frequent: min(counts, key=lambda m: (-counts[m], m)).' },
    solution: 'def analyse(texte):\n    mots = texte.lower().split()\n    compte = {}\n    for m in mots:\n        compte[m] = compte.get(m, 0) + 1\n    return {"mots": len(mots), "uniques": len(compte), "frequent": min(compte, key=lambda m: (-compte[m], m))}',
    checks: ['analyse("Le chat et le chien") == {"mots": 5, "uniques": 4, "frequent": "le"}', 'analyse("b a b a") == {"mots": 4, "uniques": 2, "frequent": "a"}', 'analyse("seul") == {"mots": 1, "uniques": 1, "frequent": "seul"}'],
  },
  {
    id: 'py-projet-stock', lang: 'py', group: 'py-projets',
    title: { fr: 'Projet 2 : gestion de stock', en: 'Project 2: stock manager' },
    explain: {
      fr: 'Second mini-projet : une classe qui garde des données (dictionnaire) et refuse les actions impossibles avec une exception. raise ValueError("message") interrompt l’action et signale l’erreur.',
      en: 'Second mini-project: a class that keeps data (a dictionary) and refuses impossible actions with an exception. raise ValueError("message") stops the action and signals the error.',
    },
    example: 'if quantite < 0:\n    raise ValueError("quantité négative")',
    task: { fr: 'Écris la classe Stock : ajoute(nom, n) ; retire(nom, n) qui lève ValueError si le stock est insuffisant ; quantite(nom) (0 si inconnu) ; total() = somme de toutes les quantités.', en: 'Write class Stock: ajoute(nom, n); retire(nom, n) raising ValueError if stock is insufficient; quantite(nom) (0 if unknown); total() = sum of all quantities.' },
    starter: 'class Stock:\n    def __init__(self):\n        self.articles = {}\n\n    def ajoute(self, nom, n):\n        pass\n\n    def retire(self, nom, n):\n        pass\n\n    def quantite(self, nom):\n        pass\n\n    def total(self):\n        pass\n',
    hint: { fr: 'retire : si self.quantite(nom) < n → raise ValueError("stock insuffisant"). total : sum(self.articles.values()).', en: 'retire: if self.quantite(nom) < n → raise ValueError("stock insuffisant"). total: sum(self.articles.values()).' },
    solution: 'class Stock:\n    def __init__(self):\n        self.articles = {}\n\n    def ajoute(self, nom, n):\n        self.articles[nom] = self.quantite(nom) + n\n\n    def retire(self, nom, n):\n        if self.quantite(nom) < n:\n            raise ValueError("stock insuffisant")\n        self.articles[nom] -= n\n\n    def quantite(self, nom):\n        return self.articles.get(nom, 0)\n\n    def total(self):\n        return sum(self.articles.values())',
    checks: ['(s := Stock(), s.ajoute("pomme", 5), s.ajoute("pomme", 2), s.quantite("pomme"))[-1] == 7', '(s := Stock(), s.ajoute("a", 3), s.retire("a", 1), s.quantite("a"))[-1] == 2', '__raises(lambda: Stock().retire("x", 1), ValueError)', 'Stock().quantite("inconnu") == 0', '(s := Stock(), s.ajoute("a", 3), s.ajoute("b", 4), s.total())[-1] == 7'],
  },
]
