import type { Lesson } from './lessons'

// Visualisation et projet Data science : graphiques tracés par l'élève (courbe, nuage, barres) et projet pandas. Contenu original.
export const vizLessons: Lesson[] = [
  {
    id: "viz-courbe", lang: 'py', group: "ds-viz",
    title: { fr: "Tracer une courbe", en: "Plotting a curve" },
    explain: { fr: "Un graphique raconte ce que cent nombres ne montrent pas. Dans Finjaro Learn, tu disposes de trois fonctions de tracé : courbe(x, y, titre), nuage(x, y, titre) et barres(etiquettes, valeurs, titre). Elles dessinent sous ton code. Une courbe relie des points dans l'ordre : parfaite pour une fonction ou une évolution dans le temps.", en: "A chart tells what a hundred numbers cannot. In Finjaro Learn you have three plotting functions: courbe(x, y, titre), nuage(x, y, titre) and barres(etiquettes, valeurs, titre). They draw under your code. A curve joins points in order: perfect for a function or a trend over time." },
    example: "courbe([0, 1, 2], [0, 1, 4], 'y = x au carré')",
    task: { fr: "Écris trace_carres(n) : trace la courbe de y = x² pour x = 0, 1, …, n (n+1 points) avec le titre « Carrés ».", en: "Write trace_carres(n): plot the curve y = x² for x = 0, 1, …, n (n+1 points) with the title “Carrés”." },
    starter: "def trace_carres(n):\n    pass\n",
    hint: { fr: "x = list(range(n + 1)) ; y = [v * v for v in x] ; courbe(x, y, 'Carrés')", en: "x = list(range(n + 1)); y = [v * v for v in x]; courbe(x, y, 'Carrés')" },
    solution: "def trace_carres(n):\n    x = list(range(n + 1))\n    y = [v * v for v in x]\n    courbe(x, y, 'Carrés')",
    checks: ["(trace_carres(4), __figs[-1]['y'])[-1] == [0, 1, 4, 9, 16]", "(trace_carres(2), __figs[-1]['titre'])[-1] == 'Carrés'", "(trace_carres(3), __figs[-1]['type'])[-1] == 'courbe'", "(trace_carres(5), len(__figs[-1]['x']))[-1] == 6"],
  },
  {
    id: "viz-histo", lang: 'py', group: "ds-viz",
    packages: ["numpy"],
    title: { fr: "Histogramme : voir la distribution", en: "Histogram: seeing the distribution" },
    explain: { fr: "Avant tout modèle, un analyste regarde la distribution de ses données : où se concentrent les valeurs ? y a-t-il des valeurs aberrantes ? Un histogramme découpe l'axe en intervalles (« bacs ») et compte les valeurs de chacun : np.histogram(valeurs, bins=5) renvoie (comptes, bords). On le trace avec barres().", en: "Before any model, an analyst looks at the distribution of the data: where do values concentrate? are there outliers? A histogram splits the axis into intervals (“bins”) and counts the values in each: np.histogram(values, bins=5) returns (counts, edges). Plot it with barres()." },
    example: "import numpy as np\ncomptes, bords = np.histogram([1, 2, 2, 3, 9], bins=4)\nprint(comptes, bords)",
    task: { fr: "Écris histo(valeurs, bacs) : calcule les comptes avec np.histogram et trace barres(étiquettes, comptes, « Distribution ») où l'étiquette de chaque bac est le début du bac arrondi à 1 décimale. Renvoie la liste des comptes.", en: "Write histo(valeurs, bacs): compute the counts with np.histogram and plot barres(labels, counts, “Distribution”) where each bin's label is the bin start rounded to 1 decimal. Return the list of counts." },
    starter: "import numpy as np\n\ndef histo(valeurs, bacs):\n    pass\n",
    hint: { fr: "comptes, bords = np.histogram(valeurs, bins=bacs) ; étiquettes = [round(b, 1) for b in bords[:-1]]", en: "counts, edges = np.histogram(values, bins=bins); labels = [round(b, 1) for b in edges[:-1]]" },
    solution: "import numpy as np\n\ndef histo(valeurs, bacs):\n    comptes, bords = np.histogram(valeurs, bins=bacs)\n    barres([round(float(b), 1) for b in bords[:-1]], comptes, 'Distribution')\n    return [int(c) for c in comptes]",
    checks: ["histo([1, 2, 2, 3, 9], 4) == [3, 1, 0, 1]", "(histo([0, 10], 2), __figs[-1]['type'])[-1] == 'barres'", "sum(histo([1, 1, 2, 5, 5, 5], 3)) == 6", "(histo([0, 5, 10], 2), __figs[-1]['x'])[-1] == ['0.0', '5.0']"],
  },
  {
    id: "viz-nuage", lang: 'py', group: "ds-viz",
    packages: ["numpy"],
    title: { fr: "Nuage de points et droite de régression", en: "Scatter plot and regression line" },
    explain: { fr: "Un nuage de points montre la relation entre deux variables. On y superpose la droite de régression : si les points s'alignent autour, la relation est presque linéaire ; sinon la droite est un mauvais modèle. Toujours regarder le graphique avant de faire confiance à un coefficient de corrélation : des jeux de données très différents peuvent avoir la même corrélation.", en: "A scatter plot shows the relationship between two variables. Overlay the regression line: if points line up around it, the relation is nearly linear; otherwise the line is a poor model. Always look at the chart before trusting a correlation coefficient: very different datasets can have the same correlation." },
    example: "nuage([1, 2, 3], [2, 4, 5])",
    task: { fr: "Écris nuage_et_droite(x, y) : trace d'abord nuage(x, y), puis courbe(x_trie, y_droite) avec la droite des moindres carrés (np.polyfit(x, y, 1)) évaluée aux x triés. Renvoie (pente, ordonnee).", en: "Write nuage_et_droite(x, y): first plot nuage(x, y), then courbe(sorted_x, line_y) with the least-squares line (np.polyfit(x, y, 1)) evaluated at the sorted x. Return (slope, intercept)." },
    starter: "import numpy as np\n\ndef nuage_et_droite(x, y):\n    pass\n",
    hint: { fr: "pente, ordonnee = np.polyfit(x, y, 1) ; xs = sorted(x) ; courbe(xs, [pente * v + ordonnee for v in xs])", en: "slope, intercept = np.polyfit(x, y, 1); xs = sorted(x); courbe(xs, [slope * v + intercept for v in xs])" },
    solution: "import numpy as np\n\ndef nuage_et_droite(x, y):\n    pente, ordonnee = np.polyfit(x, y, 1)\n    nuage(x, y, 'Données')\n    xs = sorted(x)\n    courbe(xs, [pente * v + ordonnee for v in xs], 'Droite')\n    return float(pente), float(ordonnee)",
    checks: ["np.allclose(nuage_et_droite([0, 1, 2], [1, 3, 5]), (2, 1))", "(nuage_et_droite([0, 1, 2], [1, 3, 5]), [f['type'] for f in __figs[-2:]])[-1] == ['nuage', 'courbe']", "(nuage_et_droite([2, 0, 1], [5, 1, 3]), __figs[-1]['x'])[-1] == [0.0, 1.0, 2.0]", "(nuage_et_droite([0, 1], [0, 2]), np.allclose(__figs[-1]['y'], [0, 2]))[-1]"],
  },
  {
    id: "viz-perte", lang: 'py', group: "ds-viz",
    packages: ["numpy"],
    title: { fr: "Courbe d'apprentissage", en: "Learning curve" },
    explain: { fr: "Quand on entraîne un modèle, on trace la perte à chaque époque : c'est la courbe d'apprentissage. Elle doit descendre. Si elle monte ou oscille fort, le taux d'apprentissage est trop grand ; si elle stagne tout en haut, le modèle n'apprend pas. C'est LE réflexe de diagnostic de tout ingénieur en apprentissage automatique.", en: "When training a model, you plot the loss at each epoch: the learning curve. It should go down. If it rises or oscillates wildly, the learning rate is too large; if it stagnates at the top, the model is not learning. It is THE diagnostic reflex of every machine learning engineer." },
    example: "pertes = [4.0, 2.5, 1.7]\ncourbe(range(len(pertes)), pertes)",
    task: { fr: "Écris entraine_et_trace(x, y, lr, n) : descente de gradient sur y ≈ w·x + b (comme dans le parcours Deep learning), en mémorisant la perte MSE avant chaque pas ; trace courbe(époques, pertes, « Perte ») ; renvoie la liste des pertes (n valeurs).", en: "Write entraine_et_trace(x, y, lr, n): gradient descent on y ≈ w·x + b (as in the Deep learning track), recording the MSE loss before each step; plot courbe(epochs, losses, “Perte”); return the list of losses (n values)." },
    starter: "import numpy as np\n\ndef entraine_et_trace(x, y, lr, n):\n    x, y = np.array(x, dtype=float), np.array(y, dtype=float)\n    w, b = 0.0, 0.0\n    pertes = []\n    # n pas\n    return pertes\n",
    hint: { fr: "À chaque pas : p = w*x + b ; pertes.append(np.mean((p - y) ** 2)) ; puis mets à jour w et b ; à la fin courbe(range(n), pertes, 'Perte').", en: "At each step: p = w*x + b; losses.append(np.mean((p - y) ** 2)); then update w and b; at the end courbe(range(n), losses, 'Perte')." },
    solution: "import numpy as np\n\ndef entraine_et_trace(x, y, lr, n):\n    x, y = np.array(x, dtype=float), np.array(y, dtype=float)\n    w, b = 0.0, 0.0\n    pertes = []\n    for _ in range(n):\n        p = w * x + b\n        pertes.append(float(np.mean((p - y) ** 2)))\n        w -= lr * 2 * np.mean((p - y) * x)\n        b -= lr * 2 * np.mean(p - y)\n    courbe(range(n), pertes, 'Perte')\n    return pertes",
    checks: ["len(entraine_et_trace([0, 1, 2], [1, 3, 5], 0.1, 50)) == 50", "(lambda p: p[-1] < p[0] / 100)(entraine_et_trace([0, 1, 2], [1, 3, 5], 0.1, 200))", "(entraine_et_trace([0, 1, 2], [1, 3, 5], 0.1, 10), __figs[-1]['titre'])[-1] == 'Perte'", "(lambda p: p[-1] > p[0])(entraine_et_trace([0, 1, 2], [1, 3, 5], 0.9, 20))"],
  },
  {
    id: "viz-confusion", lang: 'py', group: "ds-viz",
    title: { fr: "Matrice de confusion", en: "Confusion matrix" },
    explain: { fr: "Pour un classifieur, la matrice de confusion compte les quatre cas : vrais positifs (VP), faux positifs (FP), faux négatifs (FN), vrais négatifs (VN). Le diagramme en barres de ces quatre nombres montre d'un coup d'œil où le modèle se trompe — et pour un diagnostic médical, un FN (malade non détecté) n'a pas du tout le même coût qu'un FP.", en: "For a classifier, the confusion matrix counts the four cases: true positives (TP), false positives (FP), false negatives (FN), true negatives (TN). A bar chart of these four numbers shows at a glance where the model errs — and for a medical diagnosis, an FN (missed sick person) has a very different cost from an FP." },
    example: "vrai, pred = [1, 0], [1, 1]\nprint(sum(1 for v, p in zip(vrai, pred) if v == 1 and p == 1))",
    task: { fr: "Écris confusion(y_vrai, y_pred) : renvoie le dictionnaire {'VP': …, 'FP': …, 'FN': …, 'VN': …} et trace barres(['VP', 'FP', 'FN', 'VN'], valeurs, « Confusion »).", en: "Write confusion(y_vrai, y_pred): return the dict {'VP': …, 'FP': …, 'FN': …, 'VN': …} and plot barres(['VP', 'FP', 'FN', 'VN'], values, “Confusion”)." },
    starter: "def confusion(y_vrai, y_pred):\n    pass\n",
    hint: { fr: "Compte avec sum(1 for v, p in zip(...) if v == 1 and p == 1) etc. pour les quatre combinaisons.", en: "Count with sum(1 for v, p in zip(...) if v == 1 and p == 1) etc. for the four combinations." },
    solution: "def confusion(y_vrai, y_pred):\n    paires = list(zip(y_vrai, y_pred))\n    c = {\n        'VP': sum(1 for v, p in paires if v == 1 and p == 1),\n        'FP': sum(1 for v, p in paires if v == 0 and p == 1),\n        'FN': sum(1 for v, p in paires if v == 1 and p == 0),\n        'VN': sum(1 for v, p in paires if v == 0 and p == 0),\n    }\n    barres(['VP', 'FP', 'FN', 'VN'], [c['VP'], c['FP'], c['FN'], c['VN']], 'Confusion')\n    return c",
    checks: ["confusion([1, 0, 1, 0], [1, 1, 0, 0]) == {'VP': 1, 'FP': 1, 'FN': 1, 'VN': 1}", "confusion([1, 1], [1, 1]) == {'VP': 2, 'FP': 0, 'FN': 0, 'VN': 0}", "(confusion([1, 0, 0], [1, 0, 1]), __figs[-1]['y'])[-1] == [1.0, 1.0, 0.0, 1.0]", "(confusion([], []), __figs[-1]['type'])[-1] == 'barres'"],
  },
  {
    id: "ds-projet-ventes", lang: 'py', group: "ds-viz",
    packages: ["numpy", "pandas"],
    title: { fr: "Projet : rapport de ventes", en: "Project: sales report" },
    explain: { fr: "Projet de fin de parcours Data science : tu reçois une table de ventes (colonnes produit, mois, quantite, prix_unitaire) et tu produis un rapport. Tu combines pandas (colonne calculée, groupby, tri) et un graphique. C'est le quotidien d'un data analyst : transformer une table brute en réponses claires.", en: "Data science capstone: you receive a sales table (columns produit, mois, quantite, prix_unitaire) and produce a report. You combine pandas (computed column, groupby, sorting) and a chart. It is a data analyst's daily work: turning a raw table into clear answers." },
    example: "import pandas as pd\ndf = pd.DataFrame({'quantite': [2, 3], 'prix_unitaire': [10, 5]})\ndf['ca'] = df['quantite'] * df['prix_unitaire']\nprint(df['ca'].sum())",
    task: { fr: "Écris rapport(df) : ajoute le chiffre d'affaires par ligne (quantite × prix_unitaire), puis renvoie {'ca_total': somme, 'meilleur_produit': le produit au plus grand chiffre d'affaires total, 'meilleur_mois': le mois au plus grand chiffre d'affaires total}. Trace barres(mois, ca_par_mois, « CA par mois ») (mois dans l'ordre alphabétique).", en: "Write rapport(df): add per-row revenue (quantite × prix_unitaire), then return {'ca_total': sum, 'meilleur_produit': the product with the highest total revenue, 'meilleur_mois': the month with the highest total revenue}. Plot barres(months, revenue_per_month, “CA par mois”) (months in alphabetical order)." },
    starter: "import numpy as np\nimport pandas as pd\n\ndef rapport(df):\n    pass\n",
    hint: { fr: "df = df.assign(ca=df.quantite * df.prix_unitaire) ; par_produit = df.groupby('produit')['ca'].sum() ; .idxmax() donne la clé du maximum.", en: "df = df.assign(ca=df.quantite * df.prix_unitaire); by_product = df.groupby('produit')['ca'].sum(); .idxmax() gives the key of the maximum." },
    solution: "import numpy as np\nimport pandas as pd\n\ndef rapport(df):\n    d = df.assign(ca=df['quantite'] * df['prix_unitaire'])\n    par_produit = d.groupby('produit')['ca'].sum()\n    par_mois = d.groupby('mois')['ca'].sum().sort_index()\n    barres(list(par_mois.index), list(par_mois.values), 'CA par mois')\n    return {'ca_total': float(d['ca'].sum()), 'meilleur_produit': par_produit.idxmax(), 'meilleur_mois': par_mois.idxmax()}",
    checks: ["rapport(pd.DataFrame({'produit': ['a', 'b', 'a'], 'mois': ['jan', 'jan', 'fev'], 'quantite': [1, 2, 3], 'prix_unitaire': [10, 20, 5]})) == {'ca_total': 65.0, 'meilleur_produit': 'b', 'meilleur_mois': 'jan'}", "(rapport(pd.DataFrame({'produit': ['a', 'b', 'a'], 'mois': ['jan', 'jan', 'fev'], 'quantite': [1, 2, 3], 'prix_unitaire': [10, 20, 5]})), __figs[-1]['x'])[-1] == ['fev', 'jan']", "(rapport(pd.DataFrame({'produit': ['a'], 'mois': ['m'], 'quantite': [2], 'prix_unitaire': [3]})), __figs[-1]['y'])[-1] == [6.0]", "rapport(pd.DataFrame({'produit': ['x', 'y'], 'mois': ['m', 'm'], 'quantite': [1, 1], 'prix_unitaire': [5, 9]}))['meilleur_produit'] == 'y'"],
  },
]
